// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ed6753aa35e27ad4764a749b35d849473835fb530fcba666ac607635b1333c06
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// Package crawlberg provides Go bindings for the crawlberg library.
package crawlberg

/*
#cgo CFLAGS: -I${SRCDIR}/include
#cgo darwin,arm64 LDFLAGS: -L${SRCDIR}/.lib/macos-arm64 -Wl,-rpath,${SRCDIR}/.lib/macos-arm64 -lcrawlberg_ffi
#cgo darwin,amd64 LDFLAGS: -L${SRCDIR}/.lib/macos-x86_64 -Wl,-rpath,${SRCDIR}/.lib/macos-x86_64 -lcrawlberg_ffi
#cgo linux,amd64 LDFLAGS: -L${SRCDIR}/.lib/linux-x86_64 -Wl,-rpath,${SRCDIR}/.lib/linux-x86_64 -lcrawlberg_ffi
#cgo linux,arm64 LDFLAGS: -L${SRCDIR}/.lib/linux-aarch64 -Wl,-rpath,${SRCDIR}/.lib/linux-aarch64 -lcrawlberg_ffi
#cgo windows,amd64 LDFLAGS: -L${SRCDIR}/.lib/windows-x86_64 -lcrawlberg_ffi
#include "crawlberg.h"
*/
import "C"

import (
	"encoding/json"
	"errors"
	"fmt"
	"unsafe"
)

// lastError retrieves the last error from the FFI layer.
func lastError() error {
	code := int32(C.cberg_last_error_code())
	if code == 0 {
		return nil
	}
	ctx := C.cberg_last_error_context()
	if ctx == nil {
		return fmt.Errorf("[%d] native error", code)
	}
	message := C.GoString(ctx)
	return fmt.Errorf("[%d] %s", code, message)
}

// unmarshalBytes copies a C byte buffer into a Go []byte.
//
// The pointer is treated as a NUL-terminated C string; binary payloads
// that may contain interior NULs should be exposed by the FFI with an
// explicit length out-parameter instead.
func unmarshalBytes(ptr *C.uint8_t) []byte {
	if ptr == nil {
		return nil
	}
	return []byte(C.GoString((*C.char)(unsafe.Pointer(ptr))))
}

// Ptr returns a pointer to the given value.
//
// Used by data DTOs to construct pointers for optional fields without the
// functional-options pattern boilerplate. For example:
//
//	&MyStruct{Field: Ptr("value"), OtherField: Ptr(42)}
func Ptr[T any](v T) *T {
	return &v
}

var (
	ErrNotFound            = errors.New("not_found")
	ErrUnauthorized        = errors.New("unauthorized")
	ErrForbidden           = errors.New("forbidden")
	ErrWafBlocked          = errors.New("forbidden: waf/blocked")
	ErrTimeout             = errors.New("timeout")
	ErrRateLimited         = errors.New("rate_limited")
	ErrServerError         = errors.New("server_error")
	ErrBadGateway          = errors.New("bad_gateway")
	ErrGone                = errors.New("gone")
	ErrConnection          = errors.New("connection")
	ErrDns                 = errors.New("DNS")
	ErrSsl                 = errors.New("SSL")
	ErrDataLoss            = errors.New("data_loss")
	ErrBrowserError        = errors.New("browser")
	ErrBrowserTimeout      = errors.New("browser_timeout")
	ErrInvalidConfig       = errors.New("invalid_config")
	ErrUnsupported         = errors.New("unsupported")
	ErrSsrfPolicyViolation = errors.New("ssrf_policy_violation")
	ErrOther               = errors.New("other")
	ErrDeniedByPolicy      = errors.New("denied by SSRF policy")
	ErrNotOnAllowlist      = errors.New("host not on allowlist")
	ErrDnsResolutionFailed = errors.New("DNS resolution failed")
	ErrInvalidUrl          = errors.New("invalid URL")
	ErrDisallowedScheme    = errors.New("disallowed scheme")
	ErrTooManyRedirects    = errors.New("too many redirects")
)

// CrawlError is a structured error type.
type CrawlError struct {
	Code    string
	Message string
}

func (e CrawlError) Error() string { return e.Message }

// SsrfError is a structured error type.
type SsrfError struct {
	Code    string
	Message string
}

func (e SsrfError) Error() string { return e.Message }

// BrowserMode is an enumeration type.
type BrowserMode string

const (
	BrowserModeAuto    BrowserMode = "auto"
	BrowserModeAlways  BrowserMode = "always"
	BrowserModeNever   BrowserMode = "never"
	BrowserModeStealth BrowserMode = "stealth"
)

// BrowserWait is an enumeration type.
type BrowserWait string

const (
	BrowserWaitNetworkIdle BrowserWait = "network_idle"
	BrowserWaitSelector    BrowserWait = "selector"
	BrowserWaitFixed       BrowserWait = "fixed"
)

// BrowserBackend is an enumeration type.
type BrowserBackend string

const (
	BrowserBackendChromiumoxide BrowserBackend = "chromiumoxide"
	BrowserBackendNative        BrowserBackend = "native"
)

// AuthConfig authentication configuration.
// Variants: Basic, Bearer, Header
// Sealed interface -- use one of AuthConfigBasic, AuthConfigBearer.
type AuthConfig interface {
	isAuthConfig()
	Type() string
}

// AuthConfigBasic hTTP Basic authentication.
type AuthConfigBasic struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (AuthConfigBasic) isAuthConfig() {}
func (AuthConfigBasic) Type() string  { return "basic" }
func (v AuthConfigBasic) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type     string `json:"type"`
		Username string `json:"username"`
		Password string `json:"password"`
	}
	return json.Marshal(aux{
		Type:     v.Type(),
		Username: v.Username,
		Password: v.Password,
	})
}

// AuthConfigBearer bearer token authentication.
type AuthConfigBearer struct {
	Token string `json:"token"`
}

func (AuthConfigBearer) isAuthConfig() {}
func (AuthConfigBearer) Type() string  { return "bearer" }
func (v AuthConfigBearer) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type  string `json:"type"`
		Token string `json:"token"`
	}
	return json.Marshal(aux{
		Type:  v.Type(),
		Token: v.Token,
	})
}

// AuthConfigHeader custom authentication header.
type AuthConfigHeader struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

func (AuthConfigHeader) isAuthConfig() {}
func (AuthConfigHeader) Type() string  { return "header" }
func (v AuthConfigHeader) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type  string `json:"type"`
		Name  string `json:"name"`
		Value string `json:"value"`
	}
	return json.Marshal(aux{
		Type:  v.Type(),
		Name:  v.Name,
		Value: v.Value,
	})
}

// UnmarshalAuthConfig decodes JSON data into the appropriate concrete AuthConfig variant.
func UnmarshalAuthConfig(data []byte) (AuthConfig, error) {
	var wire struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &wire); err != nil {
		return nil, err
	}

	switch wire.Type {
	case "basic":
		var v AuthConfigBasic
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "bearer":
		var v AuthConfigBearer
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "header":
		var v AuthConfigHeader
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	}
	return nil, fmt.Errorf("unknown AuthConfig type: %q", wire.Type)
}

// LinkType is an enumeration type.
type LinkType string

const (
	LinkTypeInternal LinkType = "internal"
	LinkTypeExternal LinkType = "external"
	LinkTypeAnchor   LinkType = "anchor"
	LinkTypeDocument LinkType = "document"
)

// ImageSource is an enumeration type.
type ImageSource string

const (
	ImageSourceImg           ImageSource = "img"
	ImageSourcePictureSource ImageSource = "picture_source"
	ImageSourceOgImage       ImageSource = "og:image"
	ImageSourceTwitterImage  ImageSource = "twitter:image"
)

// FeedType is an enumeration type.
type FeedType string

const (
	FeedTypeRss      FeedType = "rss"
	FeedTypeAtom     FeedType = "atom"
	FeedTypeJSONFeed FeedType = "json_feed"
)

// AssetCategory is an enumeration type.
type AssetCategory string

const (
	AssetCategoryDocument   AssetCategory = "document"
	AssetCategoryImage      AssetCategory = "image"
	AssetCategoryAudio      AssetCategory = "audio"
	AssetCategoryVideo      AssetCategory = "video"
	AssetCategoryFont       AssetCategory = "font"
	AssetCategoryStylesheet AssetCategory = "stylesheet"
	AssetCategoryScript     AssetCategory = "script"
	AssetCategoryArchive    AssetCategory = "archive"
	AssetCategoryData       AssetCategory = "data"
	AssetCategoryOther      AssetCategory = "other"
)

// CrawlEvent event emitted during a streaming crawl operation.
//
// Not available on `wasm32` targets — streaming requires native concurrency
// primitives (tokio channels, `JoinSet`) that are not supported on wasm32.
//
// Delivered to bindings through each target's native streaming idiom.
// Variants: Page, Error, Complete
// Sealed interface -- use one of CrawlEventPage, CrawlEventError.
type CrawlEvent interface {
	isCrawlEvent()
	Type() string
}

// CrawlEventPage single page has been crawled.
type CrawlEventPage struct {
	Result CrawlPageResult `json:"result"`
}

func (CrawlEventPage) isCrawlEvent() {}
func (CrawlEventPage) Type() string  { return "page" }
func (v CrawlEventPage) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type   string          `json:"type"`
		Result CrawlPageResult `json:"result"`
	}
	return json.Marshal(aux{
		Type:   v.Type(),
		Result: v.Result,
	})
}

// CrawlEventError error occurred while crawling a URL.
type CrawlEventError struct {
	URL   string `json:"url"`
	Error string `json:"error"`
}

func (CrawlEventError) isCrawlEvent() {}
func (CrawlEventError) Type() string  { return "error" }
func (v CrawlEventError) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type  string `json:"type"`
		URL   string `json:"url"`
		Error string `json:"error"`
	}
	return json.Marshal(aux{
		Type:  v.Type(),
		URL:   v.URL,
		Error: v.Error,
	})
}

// CrawlEventComplete crawl has completed.
type CrawlEventComplete struct {
	PagesCrawled uint `json:"pages_crawled"`
}

func (CrawlEventComplete) isCrawlEvent() {}
func (CrawlEventComplete) Type() string  { return "complete" }
func (v CrawlEventComplete) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type         string `json:"type"`
		PagesCrawled uint   `json:"pages_crawled"`
	}
	return json.Marshal(aux{
		Type:         v.Type(),
		PagesCrawled: v.PagesCrawled,
	})
}

// UnmarshalCrawlEvent decodes JSON data into the appropriate concrete CrawlEvent variant.
func UnmarshalCrawlEvent(data []byte) (CrawlEvent, error) {
	var wire struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &wire); err != nil {
		return nil, err
	}

	switch wire.Type {
	case "page":
		var v CrawlEventPage
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "error":
		var v CrawlEventError
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "complete":
		var v CrawlEventComplete
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	}
	return nil, fmt.Errorf("unknown CrawlEvent type: %q", wire.Type)
}

// PageAction single page interaction action.
//
// Actions are serialized with a `type` tag using camelCase naming,
// except `ExecuteJs` which is explicitly renamed to `"executeJs"`.
// Variants: Click, TypeText, Press, Scroll, Wait, Screenshot, ExecuteJs, Scrape
// Sealed interface -- use one of PageActionClick, PageActionTypeText.
type PageAction interface {
	isPageAction()
	Type() string
}

// PageActionClick click on an element matching the given CSS selector.
type PageActionClick struct {
	Selector string `json:"selector"`
}

func (PageActionClick) isPageAction() {}
func (PageActionClick) Type() string  { return "click" }
func (v PageActionClick) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type     string `json:"type"`
		Selector string `json:"selector"`
	}
	return json.Marshal(aux{
		Type:     v.Type(),
		Selector: v.Selector,
	})
}

// PageActionTypeText type text into an element matching the given CSS selector.
type PageActionTypeText struct {
	Selector string `json:"selector"`
	Text     string `json:"text"`
}

func (PageActionTypeText) isPageAction() {}
func (PageActionTypeText) Type() string  { return "type" }
func (v PageActionTypeText) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type     string `json:"type"`
		Selector string `json:"selector"`
		Text     string `json:"text"`
	}
	return json.Marshal(aux{
		Type:     v.Type(),
		Selector: v.Selector,
		Text:     v.Text,
	})
}

// PageActionPress press a keyboard key (e.g. "Enter", "Tab", "Escape").
type PageActionPress struct {
	Key string `json:"key"`
}

func (PageActionPress) isPageAction() {}
func (PageActionPress) Type() string  { return "press" }
func (v PageActionPress) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type string `json:"type"`
		Key  string `json:"key"`
	}
	return json.Marshal(aux{
		Type: v.Type(),
		Key:  v.Key,
	})
}

// PageActionScroll scroll the page or a specific element.
type PageActionScroll struct {
	Direction ScrollDirection `json:"direction"`
	Selector  *string         `json:"selector,omitempty"`
	Amount    *int64          `json:"amount,omitempty"`
}

func (PageActionScroll) isPageAction() {}
func (PageActionScroll) Type() string  { return "scroll" }
func (v PageActionScroll) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type      string          `json:"type"`
		Direction ScrollDirection `json:"direction"`
		Selector  *string         `json:"selector,omitempty"`
		Amount    *int64          `json:"amount,omitempty"`
	}
	return json.Marshal(aux{
		Type:      v.Type(),
		Direction: v.Direction,
		Selector:  v.Selector,
		Amount:    v.Amount,
	})
}

// PageActionWait wait for a duration or for an element to appear.
type PageActionWait struct {
	Milliseconds *int64  `json:"milliseconds,omitempty"`
	Selector     *string `json:"selector,omitempty"`
}

func (PageActionWait) isPageAction() {}
func (PageActionWait) Type() string  { return "wait" }
func (v PageActionWait) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type         string  `json:"type"`
		Milliseconds *int64  `json:"milliseconds,omitempty"`
		Selector     *string `json:"selector,omitempty"`
	}
	return json.Marshal(aux{
		Type:         v.Type(),
		Milliseconds: v.Milliseconds,
		Selector:     v.Selector,
	})
}

// PageActionScreenshot take a screenshot of the current page.
type PageActionScreenshot struct {
	FullPage *bool `json:"fullPage,omitempty"`
}

func (PageActionScreenshot) isPageAction() {}
func (PageActionScreenshot) Type() string  { return "screenshot" }
func (v PageActionScreenshot) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type     string `json:"type"`
		FullPage *bool  `json:"fullPage,omitempty"`
	}
	return json.Marshal(aux{
		Type:     v.Type(),
		FullPage: v.FullPage,
	})
}

// PageActionExecuteJs execute arbitrary JavaScript in the page context.
type PageActionExecuteJs struct {
	Script string `json:"script"`
}

func (PageActionExecuteJs) isPageAction() {}
func (PageActionExecuteJs) Type() string  { return "executeJs" }
func (v PageActionExecuteJs) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type   string `json:"type"`
		Script string `json:"script"`
	}
	return json.Marshal(aux{
		Type:   v.Type(),
		Script: v.Script,
	})
}

// PageActionScrape scrape the current page HTML.
type PageActionScrape struct {
}

func (PageActionScrape) isPageAction() {}
func (PageActionScrape) Type() string  { return "scrape" }
func (v PageActionScrape) MarshalJSON() ([]byte, error) {
	type aux struct {
		Type string `json:"type"`
	}
	return json.Marshal(aux{
		Type: v.Type(),
	})
}

// UnmarshalPageAction decodes JSON data into the appropriate concrete PageAction variant.
func UnmarshalPageAction(data []byte) (PageAction, error) {
	var wire struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &wire); err != nil {
		return nil, err
	}

	switch wire.Type {
	case "click":
		var v PageActionClick
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "type":
		var v PageActionTypeText
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "press":
		var v PageActionPress
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "scroll":
		var v PageActionScroll
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "wait":
		var v PageActionWait
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "screenshot":
		var v PageActionScreenshot
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "executeJs":
		var v PageActionExecuteJs
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "scrape":
		var v PageActionScrape
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	}
	return nil, fmt.Errorf("unknown PageAction type: %q", wire.Type)
}

// ScrollDirection is an enumeration type.
type ScrollDirection string

const (
	ScrollDirectionUp   ScrollDirection = "up"
	ScrollDirectionDown ScrollDirection = "down"
)

// ExtractionMeta metadata about an LLM extraction pass.
type ExtractionMeta struct {
	Cost             *float64 `json:"cost,omitempty"`
	PromptTokens     *uint64  `json:"prompt_tokens,omitempty"`
	CompletionTokens *uint64  `json:"completion_tokens,omitempty"`
	Model            *string  `json:"model,omitempty"`
	ChunksProcessed  uint     `json:"chunks_processed"`
}

// ProxyConfig proxy configuration for HTTP requests.
type ProxyConfig struct {
	URL      string  `json:"url"`
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}

// ContentConfig content extraction and conversion configuration.
//
// Controls how HTML is converted to the output format. Uses
// html-to-markdown-rs as the conversion engine for all formats
// (markdown, plain text, djot).
type ContentConfig struct {
	OutputFormat             *string  `json:"output_format,omitempty"`
	PreprocessingPreset      *string  `json:"preprocessing_preset,omitempty"`
	RemoveNavigation         *bool    `json:"remove_navigation,omitempty"`
	RemoveForms              *bool    `json:"remove_forms,omitempty"`
	StripTags                []string `json:"strip_tags,omitempty"`
	PreserveTags             []string `json:"preserve_tags,omitempty"`
	ExcludeSelectors         []string `json:"exclude_selectors,omitempty"`
	SkipImages               bool     `json:"skip_images"`
	MaxDepth                 *uint    `json:"max_depth,omitempty"`
	Wrap                     bool     `json:"wrap"`
	WrapWidth                *uint    `json:"wrap_width,omitempty"`
	IncludeDocumentStructure *bool    `json:"include_document_structure,omitempty"`
}

// BrowserConfig browser fallback configuration.
type BrowserConfig struct {
	Mode                 *BrowserMode    `json:"mode,omitempty"`
	Backend              *BrowserBackend `json:"backend,omitempty"`
	Endpoint             *string         `json:"endpoint,omitempty"`
	Timeout              *uint64         `json:"timeout,omitempty"`
	Wait                 BrowserWait     `json:"wait,omitempty"`
	WaitSelector         *string         `json:"wait_selector,omitempty"`
	ExtraWait            *uint64         `json:"extra_wait,omitempty"`
	Proxy                *ProxyConfig    `json:"proxy,omitempty"`
	BlockURLPatterns     []string        `json:"block_url_patterns,omitempty"`
	EvalScript           *string         `json:"eval_script,omitempty"`
	RobotsUserAgent      *string         `json:"robots_user_agent,omitempty"`
	CaptureNetworkEvents bool            `json:"capture_network_events"`
	SessionAffinity      *bool           `json:"session_affinity,omitempty"`
}

// CrawlConfig configuration for crawl, scrape, and map operations.
type CrawlConfig struct {
	MaxDepth           *uint             `json:"max_depth,omitempty"`
	MaxPages           *uint             `json:"max_pages,omitempty"`
	MaxConcurrent      *uint             `json:"max_concurrent,omitempty"`
	RespectRobotsTxt   bool              `json:"respect_robots_txt"`
	SoftHTTPErrors     bool              `json:"soft_http_errors"`
	UserAgent          *string           `json:"user_agent,omitempty"`
	StayOnDomain       bool              `json:"stay_on_domain"`
	AllowSubdomains    bool              `json:"allow_subdomains"`
	IncludePaths       []string          `json:"include_paths,omitempty"`
	ExcludePaths       []string          `json:"exclude_paths,omitempty"`
	CustomHeaders      map[string]string `json:"custom_headers,omitempty"`
	RequestTimeout     *uint64           `json:"request_timeout,omitempty"`
	RateLimitMs        *uint64           `json:"rate_limit_ms,omitempty"`
	MaxRedirects       *uint             `json:"max_redirects,omitempty"`
	RetryCount         uint              `json:"retry_count"`
	RetryCodes         []uint16          `json:"retry_codes,omitempty"`
	CookiesEnabled     bool              `json:"cookies_enabled"`
	Auth               AuthConfig        `json:"auth,omitempty"`
	MaxBodySize        *uint             `json:"max_body_size,omitempty"`
	RemoveTags         []string          `json:"remove_tags,omitempty"`
	Content            ContentConfig     `json:"content"`
	MapLimit           *uint             `json:"map_limit,omitempty"`
	MapSearch          *string           `json:"map_search,omitempty"`
	DownloadAssets     bool              `json:"download_assets"`
	AssetTypes         []AssetCategory   `json:"asset_types,omitempty"`
	MaxAssetSize       *uint             `json:"max_asset_size,omitempty"`
	Browser            BrowserConfig     `json:"browser"`
	Proxy              *ProxyConfig      `json:"proxy,omitempty"`
	UserAgents         []string          `json:"user_agents,omitempty"`
	CaptureScreenshot  bool              `json:"capture_screenshot"`
	FollowDocumentUrls bool              `json:"follow_document_urls"`
	DocumentURLDepth   *uint32           `json:"document_url_depth,omitempty"`
	DownloadDocuments  *bool             `json:"download_documents,omitempty"`
	DocumentMaxSize    *uint             `json:"document_max_size,omitempty"`
	DocumentMimeTypes  []string          `json:"document_mime_types,omitempty"`
	WarcOutput         *string           `json:"warc_output,omitempty"`
	BrowserProfile     *string           `json:"browser_profile,omitempty"`
	SaveBrowserProfile bool              `json:"save_browser_profile"`
	Ssrf               SsrfPolicy        `json:"ssrf"`
}

func (s *CrawlConfig) UnmarshalJSON(data []byte) error {
	var raw struct {
		MaxDepth           *uint             `json:"max_depth,omitempty"`
		MaxPages           *uint             `json:"max_pages,omitempty"`
		MaxConcurrent      *uint             `json:"max_concurrent,omitempty"`
		RespectRobotsTxt   bool              `json:"respect_robots_txt"`
		SoftHTTPErrors     bool              `json:"soft_http_errors"`
		UserAgent          *string           `json:"user_agent,omitempty"`
		StayOnDomain       bool              `json:"stay_on_domain"`
		AllowSubdomains    bool              `json:"allow_subdomains"`
		IncludePaths       []string          `json:"include_paths,omitempty"`
		ExcludePaths       []string          `json:"exclude_paths,omitempty"`
		CustomHeaders      map[string]string `json:"custom_headers,omitempty"`
		RequestTimeout     *uint64           `json:"request_timeout,omitempty"`
		RateLimitMs        *uint64           `json:"rate_limit_ms,omitempty"`
		MaxRedirects       *uint             `json:"max_redirects,omitempty"`
		RetryCount         uint              `json:"retry_count"`
		RetryCodes         []uint16          `json:"retry_codes,omitempty"`
		CookiesEnabled     bool              `json:"cookies_enabled"`
		Auth               json.RawMessage   `json:"auth,omitempty"`
		MaxBodySize        *uint             `json:"max_body_size,omitempty"`
		RemoveTags         []string          `json:"remove_tags,omitempty"`
		Content            ContentConfig     `json:"content"`
		MapLimit           *uint             `json:"map_limit,omitempty"`
		MapSearch          *string           `json:"map_search,omitempty"`
		DownloadAssets     bool              `json:"download_assets"`
		AssetTypes         []AssetCategory   `json:"asset_types,omitempty"`
		MaxAssetSize       *uint             `json:"max_asset_size,omitempty"`
		Browser            BrowserConfig     `json:"browser"`
		Proxy              *ProxyConfig      `json:"proxy,omitempty"`
		UserAgents         []string          `json:"user_agents,omitempty"`
		CaptureScreenshot  bool              `json:"capture_screenshot"`
		FollowDocumentUrls bool              `json:"follow_document_urls"`
		DocumentURLDepth   *uint32           `json:"document_url_depth,omitempty"`
		DownloadDocuments  *bool             `json:"download_documents,omitempty"`
		DocumentMaxSize    *uint             `json:"document_max_size,omitempty"`
		DocumentMimeTypes  []string          `json:"document_mime_types,omitempty"`
		WarcOutput         *string           `json:"warc_output,omitempty"`
		BrowserProfile     *string           `json:"browser_profile,omitempty"`
		SaveBrowserProfile bool              `json:"save_browser_profile"`
		Ssrf               SsrfPolicy        `json:"ssrf"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	s.MaxDepth = raw.MaxDepth
	s.MaxPages = raw.MaxPages
	s.MaxConcurrent = raw.MaxConcurrent
	s.RespectRobotsTxt = raw.RespectRobotsTxt
	s.SoftHTTPErrors = raw.SoftHTTPErrors
	s.UserAgent = raw.UserAgent
	s.StayOnDomain = raw.StayOnDomain
	s.AllowSubdomains = raw.AllowSubdomains
	s.IncludePaths = raw.IncludePaths
	s.ExcludePaths = raw.ExcludePaths
	s.CustomHeaders = raw.CustomHeaders
	s.RequestTimeout = raw.RequestTimeout
	s.RateLimitMs = raw.RateLimitMs
	s.MaxRedirects = raw.MaxRedirects
	s.RetryCount = raw.RetryCount
	s.RetryCodes = raw.RetryCodes
	s.CookiesEnabled = raw.CookiesEnabled
	s.MaxBodySize = raw.MaxBodySize
	s.RemoveTags = raw.RemoveTags
	s.Content = raw.Content
	s.MapLimit = raw.MapLimit
	s.MapSearch = raw.MapSearch
	s.DownloadAssets = raw.DownloadAssets
	s.AssetTypes = raw.AssetTypes
	s.MaxAssetSize = raw.MaxAssetSize
	s.Browser = raw.Browser
	s.Proxy = raw.Proxy
	s.UserAgents = raw.UserAgents
	s.CaptureScreenshot = raw.CaptureScreenshot
	s.FollowDocumentUrls = raw.FollowDocumentUrls
	s.DocumentURLDepth = raw.DocumentURLDepth
	s.DownloadDocuments = raw.DownloadDocuments
	s.DocumentMaxSize = raw.DocumentMaxSize
	s.DocumentMimeTypes = raw.DocumentMimeTypes
	s.WarcOutput = raw.WarcOutput
	s.BrowserProfile = raw.BrowserProfile
	s.SaveBrowserProfile = raw.SaveBrowserProfile
	s.Ssrf = raw.Ssrf
	if len(raw.Auth) > 0 && string(raw.Auth) != "null" {
		v, err := UnmarshalAuthConfig(raw.Auth)
		if err != nil {
			return err
		}
		s.Auth = v
	}
	return nil
}

// BrowserExtras browser-specific extras populated when the native browser backend was used.
//
// Available on `ScrapeResult.browser` when `BrowserBackend::Native` handled the request.
type BrowserExtras struct {
	EvalResult    *json.RawMessage `json:"eval_result,omitempty"`
	NetworkEvents []ResponseMeta   `json:"network_events,omitempty"`
	Cookies       []CookieInfo     `json:"cookies,omitempty"`
}

// DownloadedDocument downloaded non-HTML document (PDF, DOCX, image, code file, etc.).
//
// When the crawler encounters non-HTML content and `download_documents` is
// enabled, it downloads the raw bytes and populates this struct instead of
// skipping the resource.
type DownloadedDocument struct {
	URL         string            `json:"url"`
	MimeType    string            `json:"mime_type"`
	Size        uint              `json:"size"`
	Filename    *string           `json:"filename,omitempty"`
	ContentHash string            `json:"content_hash"`
	Headers     map[string]string `json:"headers,omitempty"`
}

// InteractionResult result of executing a sequence of page interaction actions.
type InteractionResult struct {
	ActionResults []ActionResult `json:"action_results,omitempty"`
	FinalHTML     string         `json:"final_html"`
	FinalURL      string         `json:"final_url"`
}

// ActionResult result from a single page action execution.
type ActionResult struct {
	ActionIndex uint             `json:"action_index"`
	ActionType  string           `json:"action_type"`
	Success     bool             `json:"success"`
	Data        *json.RawMessage `json:"data,omitempty"`
	Error       *string          `json:"error,omitempty"`
}

// ScrapeResult result of a single-page scrape operation.
type ScrapeResult struct {
	StatusCode         uint16              `json:"status_code"`
	FinalURL           string              `json:"final_url"`
	ContentType        string              `json:"content_type"`
	HTML               string              `json:"html"`
	BodySize           uint                `json:"body_size"`
	Metadata           PageMetadata        `json:"metadata"`
	Links              []LinkInfo          `json:"links,omitempty"`
	Images             []ImageInfo         `json:"images,omitempty"`
	Feeds              []FeedInfo          `json:"feeds,omitempty"`
	JSONLd             []JSONLdEntry       `json:"json_ld,omitempty"`
	IsAllowed          bool                `json:"is_allowed"`
	CrawlDelay         *uint64             `json:"crawl_delay,omitempty"`
	NoindexDetected    bool                `json:"noindex_detected"`
	NofollowDetected   bool                `json:"nofollow_detected"`
	XRobotsTag         *string             `json:"x_robots_tag,omitempty"`
	IsPdf              bool                `json:"is_pdf"`
	WasSkipped         bool                `json:"was_skipped"`
	DetectedCharset    *string             `json:"detected_charset,omitempty"`
	AuthHeaderSent     bool                `json:"auth_header_sent"`
	ResponseMeta       *ResponseMeta       `json:"response_meta,omitempty"`
	Assets             []DownloadedAsset   `json:"assets,omitempty"`
	JsRenderHint       bool                `json:"js_render_hint"`
	BrowserUsed        bool                `json:"browser_used"`
	Markdown           *MarkdownResult     `json:"markdown,omitempty"`
	ExtractedData      *json.RawMessage    `json:"extracted_data,omitempty"`
	ExtractionMeta     *ExtractionMeta     `json:"extraction_meta,omitempty"`
	DownloadedDocument *DownloadedDocument `json:"downloaded_document,omitempty"`
	Browser            *BrowserExtras      `json:"browser,omitempty"`
}

// CrawlPageResult result of crawling a single page during a crawl operation.
type CrawlPageResult struct {
	URL                string              `json:"url"`
	NormalizedURL      string              `json:"normalized_url"`
	StatusCode         uint16              `json:"status_code"`
	ContentType        string              `json:"content_type"`
	HTML               string              `json:"html"`
	BodySize           uint                `json:"body_size"`
	Metadata           PageMetadata        `json:"metadata"`
	Links              []LinkInfo          `json:"links,omitempty"`
	Images             []ImageInfo         `json:"images,omitempty"`
	Feeds              []FeedInfo          `json:"feeds,omitempty"`
	JSONLd             []JSONLdEntry       `json:"json_ld,omitempty"`
	Depth              uint                `json:"depth"`
	StayedOnDomain     bool                `json:"stayed_on_domain"`
	WasSkipped         bool                `json:"was_skipped"`
	IsPdf              bool                `json:"is_pdf"`
	DetectedCharset    *string             `json:"detected_charset,omitempty"`
	Markdown           *MarkdownResult     `json:"markdown,omitempty"`
	ExtractedData      *json.RawMessage    `json:"extracted_data,omitempty"`
	ExtractionMeta     *ExtractionMeta     `json:"extraction_meta,omitempty"`
	DownloadedDocument *DownloadedDocument `json:"downloaded_document,omitempty"`
	BrowserUsed        bool                `json:"browser_used"`
}

// CrawlResult result of a multi-page crawl operation.
type CrawlResult struct {
	Pages          []CrawlPageResult `json:"pages,omitempty"`
	FinalURL       string            `json:"final_url"`
	RedirectCount  uint              `json:"redirect_count"`
	WasSkipped     bool              `json:"was_skipped"`
	Error          *string           `json:"error,omitempty"`
	Cookies        []CookieInfo      `json:"cookies,omitempty"`
	StayedOnDomain bool              `json:"stayed_on_domain"`
	BrowserUsed    bool              `json:"browser_used"`
}

// SitemapURL uRL entry from a sitemap.
type SitemapURL struct {
	URL        string  `json:"url"`
	Lastmod    *string `json:"lastmod,omitempty"`
	Changefreq *string `json:"changefreq,omitempty"`
	Priority   *string `json:"priority,omitempty"`
}

// MapResult result of a map operation, containing discovered URLs.
type MapResult struct {
	Urls []SitemapURL `json:"urls,omitempty"`
}

// MarkdownResult rich markdown conversion result from HTML processing.
type MarkdownResult struct {
	Content           string            `json:"content"`
	DocumentStructure *json.RawMessage  `json:"document_structure,omitempty"`
	Tables            []json.RawMessage `json:"tables,omitempty"`
	Warnings          []string          `json:"warnings,omitempty"`
	Citations         bool              `json:"citations"`
	FitContent        *string           `json:"fit_content,omitempty"`
}

// LinkInfo information about a link found on a page.
type LinkInfo struct {
	URL      string   `json:"url"`
	Text     string   `json:"text"`
	LinkType LinkType `json:"link_type,omitempty"`
	Rel      *string  `json:"rel,omitempty"`
	Nofollow bool     `json:"nofollow"`
}

// ImageInfo information about an image found on a page.
type ImageInfo struct {
	URL    string      `json:"url"`
	Alt    *string     `json:"alt,omitempty"`
	Width  *uint32     `json:"width,omitempty"`
	Height *uint32     `json:"height,omitempty"`
	Source ImageSource `json:"source,omitempty"`
}

// FeedInfo information about a feed link found on a page.
type FeedInfo struct {
	URL      string   `json:"url"`
	Title    *string  `json:"title,omitempty"`
	FeedType FeedType `json:"feed_type,omitempty"`
}

// JSONLdEntry jSON-LD structured data entry found on a page.
type JSONLdEntry struct {
	SchemaType string  `json:"schema_type"`
	Name       *string `json:"name,omitempty"`
	Raw        string  `json:"raw"`
}

// CookieInfo information about an HTTP cookie received from a response.
type CookieInfo struct {
	Name   string  `json:"name"`
	Value  string  `json:"value"`
	Domain *string `json:"domain,omitempty"`
	Path   *string `json:"path,omitempty"`
}

// DownloadedAsset downloaded asset from a page.
type DownloadedAsset struct {
	URL           string        `json:"url"`
	ContentHash   string        `json:"content_hash"`
	MimeType      *string       `json:"mime_type,omitempty"`
	Size          uint          `json:"size"`
	AssetCategory AssetCategory `json:"asset_category,omitempty"`
	HTMLTag       *string       `json:"html_tag,omitempty"`
}

// ArticleMetadata article metadata extracted from `article:*` Open Graph tags.
type ArticleMetadata struct {
	PublishedTime *string  `json:"published_time,omitempty"`
	ModifiedTime  *string  `json:"modified_time,omitempty"`
	Author        *string  `json:"author,omitempty"`
	Section       *string  `json:"section,omitempty"`
	Tags          []string `json:"tags,omitempty"`
}

// HreflangEntry hreflang alternate link entry.
type HreflangEntry struct {
	Lang string `json:"lang"`
	URL  string `json:"url"`
}

// FaviconInfo information about a favicon or icon link.
type FaviconInfo struct {
	URL      string  `json:"url"`
	Rel      string  `json:"rel"`
	Sizes    *string `json:"sizes,omitempty"`
	MimeType *string `json:"mime_type,omitempty"`
}

// HeadingInfo heading element extracted from the page.
type HeadingInfo struct {
	Level uint8  `json:"level"`
	Text  string `json:"text"`
}

// ResponseMeta response metadata extracted from HTTP headers.
type ResponseMeta struct {
	Etag            *string `json:"etag,omitempty"`
	LastModified    *string `json:"last_modified,omitempty"`
	CacheControl    *string `json:"cache_control,omitempty"`
	Server          *string `json:"server,omitempty"`
	XPoweredBy      *string `json:"x_powered_by,omitempty"`
	ContentLanguage *string `json:"content_language,omitempty"`
	ContentEncoding *string `json:"content_encoding,omitempty"`
}

// PageMetadata metadata extracted from an HTML page's `<meta>` tags and `<title>` element.
type PageMetadata struct {
	Title              *string          `json:"title,omitempty"`
	Description        *string          `json:"description,omitempty"`
	CanonicalURL       *string          `json:"canonical_url,omitempty"`
	Keywords           *string          `json:"keywords,omitempty"`
	Author             *string          `json:"author,omitempty"`
	Viewport           *string          `json:"viewport,omitempty"`
	ThemeColor         *string          `json:"theme_color,omitempty"`
	Generator          *string          `json:"generator,omitempty"`
	Robots             *string          `json:"robots,omitempty"`
	HTMLLang           *string          `json:"html_lang,omitempty"`
	HTMLDir            *string          `json:"html_dir,omitempty"`
	OgTitle            *string          `json:"og_title,omitempty"`
	OgType             *string          `json:"og_type,omitempty"`
	OgImage            *string          `json:"og_image,omitempty"`
	OgDescription      *string          `json:"og_description,omitempty"`
	OgURL              *string          `json:"og_url,omitempty"`
	OgSiteName         *string          `json:"og_site_name,omitempty"`
	OgLocale           *string          `json:"og_locale,omitempty"`
	OgVideo            *string          `json:"og_video,omitempty"`
	OgAudio            *string          `json:"og_audio,omitempty"`
	OgLocaleAlternates []string         `json:"og_locale_alternates,omitempty"`
	TwitterCard        *string          `json:"twitter_card,omitempty"`
	TwitterTitle       *string          `json:"twitter_title,omitempty"`
	TwitterDescription *string          `json:"twitter_description,omitempty"`
	TwitterImage       *string          `json:"twitter_image,omitempty"`
	TwitterSite        *string          `json:"twitter_site,omitempty"`
	TwitterCreator     *string          `json:"twitter_creator,omitempty"`
	DcTitle            *string          `json:"dc_title,omitempty"`
	DcCreator          *string          `json:"dc_creator,omitempty"`
	DcSubject          *string          `json:"dc_subject,omitempty"`
	DcDescription      *string          `json:"dc_description,omitempty"`
	DcPublisher        *string          `json:"dc_publisher,omitempty"`
	DcDate             *string          `json:"dc_date,omitempty"`
	DcType             *string          `json:"dc_type,omitempty"`
	DcFormat           *string          `json:"dc_format,omitempty"`
	DcIdentifier       *string          `json:"dc_identifier,omitempty"`
	DcLanguage         *string          `json:"dc_language,omitempty"`
	DcRights           *string          `json:"dc_rights,omitempty"`
	Article            *ArticleMetadata `json:"article,omitempty"`
	Hreflangs          []HreflangEntry  `json:"hreflangs,omitempty"`
	Favicons           []FaviconInfo    `json:"favicons,omitempty"`
	Headings           []HeadingInfo    `json:"headings,omitempty"`
	WordCount          *uint            `json:"word_count,omitempty"`
}

// CrawlStreamRequest request to begin a single-URL streaming crawl.
//
// Wraps a single seed URL for delivery through the streaming-adapter binding
// surface. Required as a struct because alef's streaming adapter requires a
// named request type — primitives are not supported.
type CrawlStreamRequest struct {
	URL string `json:"url"`
}

// BatchCrawlStreamRequest request to begin a multi-URL streaming crawl.
//
// Wraps a set of seed URLs for delivery through the streaming-adapter binding
// surface. Required as a struct because alef's streaming adapter requires a
// named request type — primitives are not supported.
type BatchCrawlStreamRequest struct {
	Urls []string `json:"urls,omitempty"`
}

// CitationResult result of citation conversion.
type CitationResult struct {
	Content    string              `json:"content"`
	References []CitationReference `json:"references,omitempty"`
}

// CitationReference single numbered reference in a citation list — produced by the citation
// extractor when content uses inline `[N]`-style markers.
type CitationReference struct {
	Index uint   `json:"index"`
	URL   string `json:"url"`
	Text  string `json:"text"`
}

// CrawlEngineHandle is an opaque handle type.
type CrawlEngineHandle struct {
	ptr unsafe.Pointer
}

// Free releases the resources held by this handle.
func (h *CrawlEngineHandle) Free() {
	if h.ptr != nil {
		C.cberg_crawl_engine_handle_free((*C.CBERGCrawlEngineHandle)(h.ptr))
		h.ptr = nil
	}
}

// BatchScrapeResult result from a single URL in a batch scrape operation.
type BatchScrapeResult struct {
	URL    string        `json:"url"`
	Result *ScrapeResult `json:"result,omitempty"`
	Error  *string       `json:"error,omitempty"`
}

// BatchCrawlResult result from a single URL in a batch crawl operation.
type BatchCrawlResult struct {
	URL    string       `json:"url"`
	Result *CrawlResult `json:"result,omitempty"`
	Error  *string      `json:"error,omitempty"`
}

// BatchScrapeResults aggregate result of a batch scrape, exposing per-URL results plus precomputed counts.
//
// The counts are derived once at construction so every binding language can read them
// as plain integer fields without re-iterating the `results` vector.
type BatchScrapeResults struct {
	Results        []BatchScrapeResult `json:"results,omitempty"`
	TotalCount     uint                `json:"total_count"`
	CompletedCount uint                `json:"completed_count"`
	FailedCount    uint                `json:"failed_count"`
}

// BatchCrawlResults aggregate result of a batch crawl, exposing per-URL results plus precomputed counts.
//
// The counts are derived once at construction so every binding language can read them
// as plain integer fields without re-iterating the `results` vector.
type BatchCrawlResults struct {
	Results        []BatchCrawlResult `json:"results,omitempty"`
	TotalCount     uint               `json:"total_count"`
	CompletedCount uint               `json:"completed_count"`
	FailedCount    uint               `json:"failed_count"`
}

// SsrfPolicy sSRF policy configuration.
type SsrfPolicy struct {
	DenyPrivate  *bool  `json:"deny_private,omitempty"`
	MaxRedirects *uint8 `json:"max_redirects,omitempty"`
}

// GenerateCitations convert markdown links to numbered citations.
//
// `[Example](https://example.com)` becomes `Example[1]`
// with `[1]: https://example.com` in the reference list.
// Images `![alt](url)` are preserved unchanged.
func GenerateCitations(markdown string) *CitationResult {
	cMarkdown := C.CString(markdown)
	defer C.free(unsafe.Pointer(cMarkdown))

	ptr := C.cberg_generate_citations(cMarkdown)
	defer C.cberg_citation_result_free(ptr)
	return func() *CitationResult {
		jsonPtr := C.cberg_citation_result_to_json(ptr)
		if jsonPtr == nil {
			return nil
		}
		defer C.cberg_free_string(jsonPtr)
		var result CitationResult
		if err := json.Unmarshal([]byte(C.GoString(jsonPtr)), &result); err != nil {
			return nil
		}
		return &result
	}()
}

// CreateEngine create a new crawl engine with the given configuration.
//
// If `config` is `None`, uses [`CrawlConfig::default()`].
// Returns an error if the configuration is invalid.
func CreateEngine(config *CrawlConfig) (*CrawlEngineHandle, error) {
	jsonBytescConfig, err := json.Marshal(config)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal: %w", err)
	}
	if string(jsonBytescConfig) == "null" {
		jsonBytescConfig = []byte("{}")
	}
	tmpStrcConfig := C.CString(string(jsonBytescConfig))
	cConfig := C.cberg_crawl_config_from_json(tmpStrcConfig)
	C.free(unsafe.Pointer(tmpStrcConfig))
	if cConfig == nil {
		return nil, fmt.Errorf("failed to create crawl_config: %s", C.GoString(C.cberg_last_error_context()))
	}
	defer C.cberg_crawl_config_free(cConfig)

	ptr := C.cberg_create_engine(cConfig)
	if err := lastError(); err != nil {
		if ptr != nil {
			C.cberg_crawl_engine_handle_free(ptr)
		}
		return nil, err
	}
	return &CrawlEngineHandle{ptr: unsafe.Pointer(ptr)}, nil
}

// Scrape a single URL, returning extracted page data.
func Scrape(engine *CrawlEngineHandle, url string) (*ScrapeResult, error) {
	cEngine := (*C.CBERGCrawlEngineHandle)(unsafe.Pointer(engine.ptr))

	curl := C.CString(url)
	defer C.free(unsafe.Pointer(curl))

	ptr := C.cberg_scrape(cEngine, curl)
	if err := lastError(); err != nil {
		if ptr != nil {
			C.cberg_scrape_result_free(ptr)
		}
		return nil, err
	}
	defer C.cberg_scrape_result_free(ptr)
	jsonPtr := C.cberg_scrape_result_to_json(ptr)
	if jsonPtr == nil {
		return nil, fmt.Errorf("failed to convert to JSON")
	}
	defer C.cberg_free_string(jsonPtr)
	var result ScrapeResult
	if err := json.Unmarshal([]byte(C.GoString(jsonPtr)), &result); err != nil {
		return nil, fmt.Errorf("failed to unmarshal: %w", err)
	}
	return &result, nil
}

// Crawl a website starting from `url`, following links up to the configured depth.
func Crawl(engine *CrawlEngineHandle, url string) (*CrawlResult, error) {
	cEngine := (*C.CBERGCrawlEngineHandle)(unsafe.Pointer(engine.ptr))

	curl := C.CString(url)
	defer C.free(unsafe.Pointer(curl))

	ptr := C.cberg_crawl(cEngine, curl)
	if err := lastError(); err != nil {
		if ptr != nil {
			C.cberg_crawl_result_free(ptr)
		}
		return nil, err
	}
	defer C.cberg_crawl_result_free(ptr)
	jsonPtr := C.cberg_crawl_result_to_json(ptr)
	if jsonPtr == nil {
		return nil, fmt.Errorf("failed to convert to JSON")
	}
	defer C.cberg_free_string(jsonPtr)
	var result CrawlResult
	if err := json.Unmarshal([]byte(C.GoString(jsonPtr)), &result); err != nil {
		return nil, fmt.Errorf("failed to unmarshal: %w", err)
	}
	return &result, nil
}

// MapUrls discover all pages on a website by following links and sitemaps.
func MapUrls(engine *CrawlEngineHandle, url string) (*MapResult, error) {
	cEngine := (*C.CBERGCrawlEngineHandle)(unsafe.Pointer(engine.ptr))

	curl := C.CString(url)
	defer C.free(unsafe.Pointer(curl))

	ptr := C.cberg_map_urls(cEngine, curl)
	if err := lastError(); err != nil {
		if ptr != nil {
			C.cberg_map_result_free(ptr)
		}
		return nil, err
	}
	defer C.cberg_map_result_free(ptr)
	jsonPtr := C.cberg_map_result_to_json(ptr)
	if jsonPtr == nil {
		return nil, fmt.Errorf("failed to convert to JSON")
	}
	defer C.cberg_free_string(jsonPtr)
	var result MapResult
	if err := json.Unmarshal([]byte(C.GoString(jsonPtr)), &result); err != nil {
		return nil, fmt.Errorf("failed to unmarshal: %w", err)
	}
	return &result, nil
}

// Interact execute browser actions on a single page.
func Interact(engine *CrawlEngineHandle, url string, actions []PageAction) (*InteractionResult, error) {
	cEngine := (*C.CBERGCrawlEngineHandle)(unsafe.Pointer(engine.ptr))

	curl := C.CString(url)
	defer C.free(unsafe.Pointer(curl))

	jsonBytescActions, err := json.Marshal(actions)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal: %w", err)
	}
	cActions := C.CString(string(jsonBytescActions))
	defer C.free(unsafe.Pointer(cActions))

	ptr := C.cberg_interact(cEngine, curl, cActions)
	if err := lastError(); err != nil {
		if ptr != nil {
			C.cberg_interaction_result_free(ptr)
		}
		return nil, err
	}
	defer C.cberg_interaction_result_free(ptr)
	jsonPtr := C.cberg_interaction_result_to_json(ptr)
	if jsonPtr == nil {
		return nil, fmt.Errorf("failed to convert to JSON")
	}
	defer C.cberg_free_string(jsonPtr)
	var result InteractionResult
	if err := json.Unmarshal([]byte(C.GoString(jsonPtr)), &result); err != nil {
		return nil, fmt.Errorf("failed to unmarshal: %w", err)
	}
	return &result, nil
}

// BatchScrape scrape multiple URLs concurrently.
func BatchScrape(engine *CrawlEngineHandle, urls []string) (*BatchScrapeResults, error) {
	cEngine := (*C.CBERGCrawlEngineHandle)(unsafe.Pointer(engine.ptr))

	jsonBytescUrls, err := json.Marshal(urls)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal: %w", err)
	}
	cUrls := C.CString(string(jsonBytescUrls))
	defer C.free(unsafe.Pointer(cUrls))

	ptr := C.cberg_batch_scrape(cEngine, cUrls)
	if err := lastError(); err != nil {
		if ptr != nil {
			C.cberg_batch_scrape_results_free(ptr)
		}
		return nil, err
	}
	defer C.cberg_batch_scrape_results_free(ptr)
	jsonPtr := C.cberg_batch_scrape_results_to_json(ptr)
	if jsonPtr == nil {
		return nil, fmt.Errorf("failed to convert to JSON")
	}
	defer C.cberg_free_string(jsonPtr)
	var result BatchScrapeResults
	if err := json.Unmarshal([]byte(C.GoString(jsonPtr)), &result); err != nil {
		return nil, fmt.Errorf("failed to unmarshal: %w", err)
	}
	return &result, nil
}

// BatchCrawl crawl multiple seed URLs concurrently, each following links to configured depth.
func BatchCrawl(engine *CrawlEngineHandle, urls []string) (*BatchCrawlResults, error) {
	cEngine := (*C.CBERGCrawlEngineHandle)(unsafe.Pointer(engine.ptr))

	jsonBytescUrls, err := json.Marshal(urls)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal: %w", err)
	}
	cUrls := C.CString(string(jsonBytescUrls))
	defer C.free(unsafe.Pointer(cUrls))

	ptr := C.cberg_batch_crawl(cEngine, cUrls)
	if err := lastError(); err != nil {
		if ptr != nil {
			C.cberg_batch_crawl_results_free(ptr)
		}
		return nil, err
	}
	defer C.cberg_batch_crawl_results_free(ptr)
	jsonPtr := C.cberg_batch_crawl_results_to_json(ptr)
	if jsonPtr == nil {
		return nil, fmt.Errorf("failed to convert to JSON")
	}
	defer C.cberg_free_string(jsonPtr)
	var result BatchCrawlResults
	if err := json.Unmarshal([]byte(C.GoString(jsonPtr)), &result); err != nil {
		return nil, fmt.Errorf("failed to unmarshal: %w", err)
	}
	return &result, nil
}

// CrawlStream wraps the CrawlEngineHandle.CrawlStream streaming adapter,
// exposing it as a module-level function for test and consumer convenience.
func CrawlStream(engine *CrawlEngineHandle, URL string) (<-chan CrawlEvent, error) {
	req := &CrawlStreamRequest{URL: URL}

	return engine.CrawlStream(*req)
}

// BatchCrawlStream wraps the CrawlEngineHandle.BatchCrawlStream streaming adapter,
// exposing it as a module-level function for test and consumer convenience.
func BatchCrawlStream(engine *CrawlEngineHandle, Urls []string) (<-chan CrawlEvent, error) {
	req := &BatchCrawlStreamRequest{Urls: Urls}

	return engine.BatchCrawlStream(*req)
}

// Validate the configuration, returning an error if any values are invalid.
func (r *CrawlConfig) Validate() error {
	jsonBytesRecv, err := json.Marshal(r)
	if err != nil {
		return fmt.Errorf("failed to marshal receiver: %w", err)
	}
	tmpStrRecv := C.CString(string(jsonBytesRecv))
	cRecv := C.cberg_crawl_config_from_json(tmpStrRecv)
	C.free(unsafe.Pointer(tmpStrRecv))
	if cRecv == nil {
		return fmt.Errorf("failed to create receiver: %s", C.GoString(C.cberg_last_error_context()))
	}
	defer C.cberg_crawl_config_free(cRecv)
	C.cberg_crawl_config_validate(cRecv)
	jsonPtrUpdated := C.cberg_crawl_config_to_json(cRecv)
	if jsonPtrUpdated != nil {
		_ = json.Unmarshal([]byte(C.GoString(jsonPtrUpdated)), r)
		C.cberg_free_string(jsonPtrUpdated)
	}
	return lastError()
}

// UniqueNormalizedUrls returns the count of unique normalized URLs encountered during crawling.
func (r *CrawlResult) UniqueNormalizedUrls() (uint, error) {
	jsonBytesRecv, err := json.Marshal(r)
	if err != nil {
		return 0, fmt.Errorf("failed to marshal receiver: %w", err)
	}
	tmpStrRecv := C.CString(string(jsonBytesRecv))
	cRecv := C.cberg_crawl_result_from_json(tmpStrRecv)
	C.free(unsafe.Pointer(tmpStrRecv))
	if cRecv == nil {
		return 0, fmt.Errorf("failed to create receiver: %s", C.GoString(C.cberg_last_error_context()))
	}
	defer C.cberg_crawl_result_free(cRecv)
	ptr := C.cberg_crawl_result_unique_normalized_urls(cRecv)
	return uint(ptr), nil
}

// CrawlStream stream a single-URL crawl, yielding [`CrawlEvent`]s as pages are processed.
//
// Returns an async stream that emits one event per crawled page, plus a
// terminal `Complete` event. On per-URL failure during the crawl, emits an
// `Error` event followed by `Complete`. The stream item type is wrapped in
// a `Result` to surface transport-level errors; today every emit is `Ok`.
//
// Language bindings expose this as the native streaming shape for each
// target. WASM does not expose native streaming wrappers.
func (h *CrawlEngineHandle) CrawlStream(req CrawlStreamRequest) (<-chan CrawlEvent, error) {
	jsonBytescReq, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal: %w", err)
	}
	if string(jsonBytescReq) == "null" {
		jsonBytescReq = []byte("{}")
	}
	tmpStrcReq := C.CString(string(jsonBytescReq))
	cReq := C.cberg_crawl_stream_request_from_json(tmpStrcReq)
	C.free(unsafe.Pointer(tmpStrcReq))
	if cReq == nil {
		return nil, fmt.Errorf("failed to create crawl_stream_request: %s", C.GoString(C.cberg_last_error_context()))
	}
	defer C.cberg_crawl_stream_request_free(cReq)

	handle := C.cberg_crawl_engine_handle_crawl_stream_start((*C.CBERGCrawlEngineHandle)(unsafe.Pointer(h.ptr)), cReq)
	if handle == nil {
		if err := lastError(); err != nil {
			return nil, err
		}
		return nil, fmt.Errorf("failed to start crawl_stream stream")
	}
	ch := make(chan CrawlEvent)
	go func() {
		defer close(ch)
		defer C.cberg_crawl_engine_handle_crawl_stream_free(handle)
		for {
			chunkPtr := C.cberg_crawl_engine_handle_crawl_stream_next(handle)
			if chunkPtr == nil {
				return
			}
			jsonPtr := C.cberg_crawl_event_to_json(chunkPtr)
			if jsonPtr == nil {
				C.cberg_crawl_event_free(chunkPtr)
				return
			}
			chunk, unmarshalErr := UnmarshalCrawlEvent([]byte(C.GoString(jsonPtr)))
			C.cberg_free_string(jsonPtr)
			C.cberg_crawl_event_free(chunkPtr)
			if unmarshalErr != nil {
				return
			}
			ch <- chunk
		}
	}()
	return ch, nil
}

// BatchCrawlStream stream a multi-URL crawl, yielding [`CrawlEvent`]s across all seeds.
//
// Returns an async stream that emits one event per crawled page across all
// seeds, plus terminal `Complete` and `Error` events as appropriate. The
// stream item type is wrapped in a `Result` to surface transport-level
// errors; today every emit is `Ok`.
//
// Language bindings expose this as the native streaming shape for each
// target. WASM does not expose native streaming wrappers.
func (h *CrawlEngineHandle) BatchCrawlStream(req BatchCrawlStreamRequest) (<-chan CrawlEvent, error) {
	jsonBytescReq, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal: %w", err)
	}
	if string(jsonBytescReq) == "null" {
		jsonBytescReq = []byte("{}")
	}
	tmpStrcReq := C.CString(string(jsonBytescReq))
	cReq := C.cberg_batch_crawl_stream_request_from_json(tmpStrcReq)
	C.free(unsafe.Pointer(tmpStrcReq))
	if cReq == nil {
		return nil, fmt.Errorf("failed to create batch_crawl_stream_request: %s", C.GoString(C.cberg_last_error_context()))
	}
	defer C.cberg_batch_crawl_stream_request_free(cReq)

	handle := C.cberg_crawl_engine_handle_batch_crawl_stream_start((*C.CBERGCrawlEngineHandle)(unsafe.Pointer(h.ptr)), cReq)
	if handle == nil {
		if err := lastError(); err != nil {
			return nil, err
		}
		return nil, fmt.Errorf("failed to start batch_crawl_stream stream")
	}
	ch := make(chan CrawlEvent)
	go func() {
		defer close(ch)
		defer C.cberg_crawl_engine_handle_batch_crawl_stream_free(handle)
		for {
			chunkPtr := C.cberg_crawl_engine_handle_batch_crawl_stream_next(handle)
			if chunkPtr == nil {
				return
			}
			jsonPtr := C.cberg_crawl_event_to_json(chunkPtr)
			if jsonPtr == nil {
				C.cberg_crawl_event_free(chunkPtr)
				return
			}
			chunk, unmarshalErr := UnmarshalCrawlEvent([]byte(C.GoString(jsonPtr)))
			C.cberg_free_string(jsonPtr)
			C.cberg_crawl_event_free(chunkPtr)
			if unmarshalErr != nil {
				return
			}
			ch <- chunk
		}
	}()
	return ch, nil
}

// FromEnv create a policy from environment variables.
//
// On native platforms, reads `CRAWLBERG_ALLOW_PRIVATE_NETWORK` — if set to "1" or "true"
// (case-insensitive), sets `deny_private = false`. Otherwise, defaults to `deny_private = true`.
//
// On wasm32 targets (browser/Node.js), environment variables are not accessible to the
// compiled module. Defaults to `deny_private = false` because:
// - Outbound requests in a browser go through the fetch API, which enforces its own network policies.
// - Rust-side SSRF checking is unenforceable and redundant in a wasm32 context.
// - For testing and localhost access, the host's network sandbox is the enforcing boundary.
func SsrfPolicyFromEnv() *SsrfPolicy {
	ptr := C.cberg_ssrf_policy_from_env()
	defer C.cberg_ssrf_policy_free(ptr)
	return func() *SsrfPolicy {
		jsonPtr := C.cberg_ssrf_policy_to_json(ptr)
		if jsonPtr == nil {
			return nil
		}
		defer C.cberg_free_string(jsonPtr)
		var result SsrfPolicy
		if err := json.Unmarshal([]byte(C.GoString(jsonPtr)), &result); err != nil {
			return nil
		}
		return &result
	}()
}
