// Code generated by alef — DO NOT EDIT.
// alef:hash:5911b230a12c1cf401b7164b6483c7637a2b9a7b2f0267cd5d9daf0283021e11
package crawlberg

// RequireNativeSetup_1_4_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_4_2 = "1.4.2"
