// Code generated by alef — DO NOT EDIT.
// alef:hash:7c2292300d2245cf538c4f37d89b7aa7ec6e94ea557756f46f05e8eba50bd909
package crawlberg

// RequireNativeSetup_1_10_1 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_10_1 = "1.10.1"
