// Code generated by alef — DO NOT EDIT.
// alef:hash:8226425622cee8cf9ce42509fd65c3f0e667f477ab771a0344004760ec1aaf3c
package crawlberg

// RequireNativeSetup_1_4_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_4_0 = "1.4.0"
