// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6c633e581d125652cde7a556846f46bfeed1def3b4a2330dca1edd4bd7a543aa
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
	},
});
