# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:928639b574d5fca9c5b51f86fe815c5bc0779c92416dbaa12f74160457caaf3a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: warc
defmodule E2e.WarcTest do
  use ExUnit.Case, async: false

  describe "warc_basic_output" do
    test "warc_basic_output" do
      engine_config = "{\"respect_robots_txt\":false,\"warc_output\":\"/tmp/crawlberg_test.warc\"}"
      {:ok, engine} = Crawlberg.create_engine(engine_config)
      url = (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/warc_basic_output"
      {:ok, result} = Crawlberg.crawl(engine, url)
      assert Enum.at(result.pages, 0).status_code == 200
      assert length(result.pages) == 1
    end
  end

  describe "warc_multi_page_crawl" do
    test "warc_multi_page_crawl" do
      engine_config = "{\"max_depth\":1,\"respect_robots_txt\":false,\"warc_output\":\"/tmp/crawlberg_crawl.warc\"}"
      {:ok, engine} = Crawlberg.create_engine(engine_config)

      url =
        System.get_env("MOCK_SERVER_WARC_MULTI_PAGE_CRAWL") ||
          (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/warc_multi_page_crawl"

      {:ok, result} = Crawlberg.crawl(engine, url)
      assert length(result.pages) >= 2
      assert result.stayed_on_domain == true
    end
  end
end
