[build-system]
build-backend = "maturin"
requires = ["maturin>=1,<2"]

[dependency-groups]
dev = ["pyrefly>=1.1.1", "pytest-asyncio>=1.3", "validate-pyproject"]

[tool.uv]
workspace.members = ["packages/python"]
cache-keys = [
  { file = "pyproject.toml" },
  { file = "Cargo.toml" },
  { file = "Cargo.lock" },
  { file = "crates/**/*.rs" },
  { file = "crates/**/Cargo.toml" },
]
