// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:928639b574d5fca9c5b51f86fe815c5bc0779c92416dbaa12f74160457caaf3a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.crawlberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.crawlberg.Crawlberg;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import io.xberg.crawlberg.CrawlConfig;
import java.util.Optional;
import io.xberg.crawlberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;
/** E2e tests for category: cookies. */
public class CookiesTest {
    private static final ObjectMapper MAPPER = new ObjectMapper().registerModule(new Jdk8Module()).setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE);
    @BeforeAll
    static void initEnv() {        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }    }

    @Test
    void testCookiesPerDomain() throws Exception {
        // Isolates cookies per domain during crawl
        var engineConfig = MAPPER.readValue("{\"cookies_enabled\":true,\"max_depth\":1,\"respect_robots_txt\":false}", CrawlConfig.class);
        var engine = Crawlberg.createEngine(engineConfig);
        String url = System.getProperty("mockServer.cookies_per_domain", System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/cookies_per_domain");
        var result = Crawlberg.crawl(engine, url);
assertEquals(1, result.cookies().size());assertTrue(result.cookies().toString().toLowerCase().contains(String.valueOf("domain_cookie").toLowerCase()), "expected to contain: " + "domain_cookie");

    }


    @Test
    void testCookiesPersistence() throws Exception {
        // Maintains cookies across multiple crawl requests
        var engineConfig = MAPPER.readValue("{\"cookies_enabled\":true,\"max_depth\":1,\"respect_robots_txt\":false}", CrawlConfig.class);
        var engine = Crawlberg.createEngine(engineConfig);
        String url = System.getProperty("mockServer.cookies_persistence", System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/cookies_persistence");
        var result = Crawlberg.crawl(engine, url);
assertTrue(result.cookies().toString().toLowerCase().contains(String.valueOf("session").toLowerCase()), "expected to contain: " + "session");

    }


    @Test
    void testCookiesSetCookieResponse() throws Exception {
        // Respects Set-Cookie header from server responses
        var engineConfig = MAPPER.readValue("{\"cookies_enabled\":true,\"max_depth\":1,\"respect_robots_txt\":false}", CrawlConfig.class);
        var engine = Crawlberg.createEngine(engineConfig);
        String url = System.getProperty("mockServer.cookies_set_cookie_response", System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/cookies_set_cookie_response");
        var result = Crawlberg.crawl(engine, url);
assertTrue(result.cookies().toString().toLowerCase().contains(String.valueOf("tracking").toLowerCase()), "expected to contain: " + "tracking");

    }

}
