// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9ffe49781a1bcc14ebea6f50654dc91290b01ff6c8ca2ed510ac5792c67d5bb4
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg.crawlberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.crawlberg.Crawlberg;
import io.xberg.crawlberg.CrawlConfig;
import java.util.Optional;
import io.xberg.crawlberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;

/** E2e tests for category: metadata. */
public class MetadataTest {

    @BeforeAll
    static void initEnv() {
        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }
    }


    @Test
    void testMetadataArticleTimes() throws Exception {
        // Extracts article:published_time, modified_time, author, section, and tags
        var engine = Crawlberg.createEngine(null);
        String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/metadata_article_times";
        var result = Crawlberg.scrape(engine, url);
        assertEquals(200, result.statusCode());
        assertEquals("2024-01-15T10:00:00Z", java.util.Optional.ofNullable(result.metadata().article().publishedTime()).map(java.util.Objects::toString).orElse(""));
        assertEquals("2024-06-20T14:30:00Z", java.util.Optional.ofNullable(result.metadata().article().modifiedTime()).map(java.util.Objects::toString).orElse(""));
        assertEquals("Jane Developer", java.util.Optional.ofNullable(result.metadata().article().author()).map(java.util.Objects::toString).orElse(""));
        assertEquals("Technology", java.util.Optional.ofNullable(result.metadata().article().section()).map(java.util.Objects::toString).orElse(""));
        assertEquals(3, result.metadata().article().tags().size());


    }


    @Test
    void testMetadataFavicons() throws Exception {
        // Extracts favicon link tags including apple-touch-icon
        var engine = Crawlberg.createEngine(null);
        String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/metadata_favicons";
        var result = Crawlberg.scrape(engine, url);
        assertEquals(200, result.statusCode());
        assertEquals(5, result.metadata().favicons().size());
        assertTrue(java.util.Optional.ofNullable(result.metadata().favicons()).orElse(java.util.List.of()).stream().anyMatch(e53736157 -> String.valueOf(e53736157.rel()).contains("apple-touch-icon")), "expected some element of 'favicons[].rel' to contain: apple-touch-icon");


    }


    @Test
    void testMetadataHeadings() throws Exception {
        // Extracts heading hierarchy (h1-h6) from HTML page
        var engine = Crawlberg.createEngine(null);
        String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/metadata_headings";
        var result = Crawlberg.scrape(engine, url);
        assertEquals(200, result.statusCode());
        assertEquals(1, result.metadata().headings().get(0).level());
        assertEquals("Primary Heading", result.metadata().headings().get(0).text());
        assertEquals(8, result.metadata().headings().size());


    }


    @Test
    void testMetadataHreflang() throws Exception {
        // Extracts hreflang alternate link tags
        var engine = Crawlberg.createEngine(null);
        String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/metadata_hreflang";
        var result = Crawlberg.scrape(engine, url);
        assertEquals(200, result.statusCode());
        assertEquals(4, result.metadata().hreflangs().size());
        assertTrue(java.util.Optional.ofNullable(result.metadata().hreflangs()).orElse(java.util.List.of()).stream().anyMatch(e7d2e929c -> String.valueOf(e7d2e929c.lang()).contains("en")), "expected some element of 'hreflang[].lang' to contain: en");


    }


    @Test
    void testMetadataKeywordsAuthor() throws Exception {
        // Extracts keywords, author, viewport, generator, theme-color, robots, lang, dir metadata
        var engine = Crawlberg.createEngine(null);
        String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/metadata_keywords_author";
        var result = Crawlberg.scrape(engine, url);
        assertEquals(200, result.statusCode());
        assertEquals("Comprehensive Metadata Test Page", java.util.Optional.ofNullable(result.metadata().title()).map(java.util.Objects::toString).orElse(""));
        assertTrue(java.util.Optional.ofNullable(result.metadata().canonicalUrl()).filter(value -> switch ((Object) value) {
            case CharSequence text -> !text.isEmpty();
            case java.util.Collection<?> items -> !items.isEmpty();
            case java.util.Map<?, ?> entries -> !entries.isEmpty();
            default -> true;
        }).isPresent(), "expected non-empty value");
        assertTrue(java.util.Optional.ofNullable(result.metadata().keywords()).filter(value -> switch ((Object) value) {
            case CharSequence text -> !text.isEmpty();
            case java.util.Collection<?> items -> !items.isEmpty();
            case java.util.Map<?, ?> entries -> !entries.isEmpty();
            default -> true;
        }).isPresent(), "expected non-empty value");
        assertTrue(java.util.Optional.ofNullable(result.metadata().keywords()).map(java.util.Objects::toString).orElse("").contains("rust"), "expected to contain: " + "rust");
        assertEquals("Jane Developer", java.util.Optional.ofNullable(result.metadata().author()).map(java.util.Objects::toString).orElse(""));
        assertTrue(java.util.Optional.ofNullable(result.metadata().viewport()).filter(value -> switch ((Object) value) {
            case CharSequence text -> !text.isEmpty();
            case java.util.Collection<?> items -> !items.isEmpty();
            case java.util.Map<?, ?> entries -> !entries.isEmpty();
            default -> true;
        }).isPresent(), "expected non-empty value");
        assertEquals("crawlberg/1.0", java.util.Optional.ofNullable(result.metadata().generator()).map(java.util.Objects::toString).orElse(""));
        assertEquals("#ff6600", java.util.Optional.ofNullable(result.metadata().themeColor()).map(java.util.Objects::toString).orElse(""));
        assertEquals("index, follow", java.util.Optional.ofNullable(result.metadata().robots()).map(java.util.Objects::toString).orElse(""));
        assertEquals("en", java.util.Optional.ofNullable(result.metadata().htmlLang()).map(java.util.Objects::toString).orElse(""));
        assertEquals("ltr", java.util.Optional.ofNullable(result.metadata().htmlDir()).map(java.util.Objects::toString).orElse(""));


    }


    @Test
    void testMetadataOgVideoAudio() throws Exception {
        // Extracts og:video, og:audio, and og:locale:alternate metadata
        var engine = Crawlberg.createEngine(null);
        String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/metadata_og_video_audio";
        var result = Crawlberg.scrape(engine, url);
        assertEquals(200, result.statusCode());
        assertEquals("https://example.com/video.mp4", java.util.Optional.ofNullable(result.metadata().ogVideo()).map(java.util.Objects::toString).orElse(""));
        assertEquals("https://example.com/audio.mp3", java.util.Optional.ofNullable(result.metadata().ogAudio()).map(java.util.Objects::toString).orElse(""));
        assertEquals(2, result.metadata().ogLocaleAlternates().size());


    }


    @Test
    void testMetadataResponseHeaders() throws Exception {
        // Extracts response metadata from HTTP headers (etag, server, content-language)
        var engine = Crawlberg.createEngine(null);
        String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/metadata_response_headers";
        var result = Crawlberg.scrape(engine, url);
        assertEquals(200, result.statusCode());
        assertTrue(java.util.Optional.ofNullable(result.responseMeta().etag()).map(java.util.Objects::toString).orElse("").contains("abc123"), "expected to contain: " + "abc123");
        assertTrue(java.util.Optional.ofNullable(result.responseMeta().lastModified()).map(java.util.Objects::toString).orElse("").contains("01 Jan 2025"), "expected to contain: " + "01 Jan 2025");
        assertTrue(java.util.Optional.ofNullable(result.responseMeta().server()).map(java.util.Objects::toString).orElse("").contains("nginx"), "expected to contain: " + "nginx");
        assertEquals("en-US", java.util.Optional.ofNullable(result.responseMeta().contentLanguage()).map(java.util.Objects::toString).orElse(""));


    }


    @Test
    void testMetadataWordCount() throws Exception {
        // Computes word count from visible page text
        var engine = Crawlberg.createEngine(null);
        String url = System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL")) + "/fixtures/metadata_word_count";
        var result = Crawlberg.scrape(engine, url);
        assertEquals(200, result.statusCode());
        assertTrue(java.util.Optional.ofNullable(result.metadata().wordCount()).map(Number::longValue).orElse(0L) > 99, "expected > 99");
        assertTrue(java.util.Optional.ofNullable(result.metadata().wordCount()).map(Number::longValue).orElse(0L) < 301, "expected < 301");


    }

}
