// DO NOT EDIT - auto-generated by alef
// alef:hash:129cfcb5da900751230bec20a427aec9f64808e493adac70dddd6d4e1f8750ff
package io.xberg.crawlberg;

/**
 * A bad gateway error occurred (HTTP 502).
 */
public class BadGatewayException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BadGatewayException with the given message. */
  public BadGatewayException(final String message) {
    super(message);
  }

  /** Creates a new BadGatewayException with the given message and cause. */
  public BadGatewayException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
