// DO NOT EDIT - auto-generated by alef
// alef:hash:3666d6f48a5b367f70d410cc4c34290877eb40d3e8c0cb851dd34ae3722d73d3
package io.xberg.crawlberg;

/**
 * The browser failed to launch, connect, or navigate.
 */
public class BrowserErrorException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BrowserErrorException with the given message. */
  public BrowserErrorException(final String message) {
    super(message);
  }

  /** Creates a new BrowserErrorException with the given message and cause. */
  public BrowserErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
