// DO NOT EDIT - auto-generated by alef
// alef:hash:7c011ee5688979448c85a639a24835fac91faabe56dd33eb0e8239833a035980
package io.xberg.crawlberg;

/**
 * The browser failed to launch, connect, or navigate.
 */
public class BrowserErrorException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BrowserErrorException with the given message. */
  public BrowserErrorException(final String message) { super(message); }

  /** Creates a new BrowserErrorException with the given message and cause. */
  public BrowserErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
