// DO NOT EDIT - auto-generated by alef
// alef:hash:ed6753aa35e27ad4764a749b35d849473835fb530fcba666ac607635b1333c06
package io.xberg.crawlberg;

/**
 * The browser page load or rendering timed out.
 */
public class BrowserTimeoutException extends CrawlErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new BrowserTimeoutException with the given message. */
    public BrowserTimeoutException(final String message) {
        super(message);
    }

    /** Creates a new BrowserTimeoutException with the given message and cause. */
    public BrowserTimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
