// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:19a16a2b022a864dcc52b4d1f0a90aa954536bf3f0f4037e9e13bc62cd491bc0
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.crawlberg;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;

/**
 * Serialises {@code byte[]} as a JSON array of integers.
 *
 * <p>Jackson's default serialiser encodes {@code byte[]} as a base64 string,
 * but Rust's {@code serde} for {@code Vec<u8>} expects {@code [72, 101, 108,
 * ...]}. Annotate any {@code byte[]} field sent to the FFI layer with
 * {@code @JsonSerialize(using = ByteArraySerializer.class)}.
 */
@SuppressWarnings("PMD")
public class ByteArraySerializer extends JsonSerializer<byte[]> {

  @Override
  public void serialize(final byte[] value, final JsonGenerator gen,
                        final SerializerProvider provider)
      throws java.io.IOException {
    gen.writeStartArray();
    for (byte b : value) {
      gen.writeNumber(b & 0xFF);
    }
    gen.writeEndArray();
  }
}
