// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a57e2e066253d4d0fbc31962bb1e75ea9091dc99f9941cbbb6b6154487839a72
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.crawlberg;

/** Exception thrown when an FFI value conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends CrawlbergRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConversionErrorException. */
  public ConversionErrorException(final String message) { super(1, message); }

  /** Creates a new ConversionErrorException with a cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
