// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7c011ee5688979448c85a639a24835fac91faabe56dd33eb0e8239833a035980
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.crawlberg;

/** Exception thrown when type conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends CrawlbergRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConversionErrorException. */
  public ConversionErrorException(final String message) { super(2, message); }

  /** Creates a new ConversionErrorException with a cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
