// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fdba8e9bcbaf58d762046708d0f0ca78d79be2db6461951e8c0c1c443a968c43
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.crawlberg;

/** Exception thrown by CrawlbergRs. */
public class CrawlbergRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new CrawlbergRsException. */
  public CrawlbergRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new CrawlbergRsException with a cause. */
  public CrawlbergRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
