// DO NOT EDIT - auto-generated by alef
// alef:hash:cc5fc94c108bb9f977a57f5e3f8b8af61509305ba43cb747a643f02ace5dc941
package io.xberg.crawlberg;

/**
 * Errors that can occur during crawling, scraping, or mapping operations.
 */
public class CrawlErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new CrawlErrorException with the given message. */
  public CrawlErrorException(final String message) { super(message); }

  /** Creates a new CrawlErrorException with the given message and cause. */
  public CrawlErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
