// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9239f0c4a976848daf64796cbf08d6835862f17985c5f163c603390b305b904e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.crawlberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * An event emitted during a streaming crawl operation.
 *
 * Not available on {@code wasm32} targets — streaming requires native
 * concurrency primitives (tokio channels, {@code JoinSet}) that are not
 * supported on wasm32.
 *
 * Delivered to bindings through each target's native streaming idiom.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes({
  @JsonSubTypes.Type(value = CrawlEvent.Page.class, name = "page")
  , @JsonSubTypes.Type(value = CrawlEvent.Error.class, name = "error"),
      @JsonSubTypes.Type(value = CrawlEvent.Complete.class, name = "complete")
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
public sealed interface CrawlEvent {

  /**
   * A single page has been crawled.
   */
  record Page(@JsonProperty("result") CrawlPageResult result)
      implements CrawlEvent {}

  /**
   * An error occurred while crawling a URL.
   */
  record Error(@JsonProperty("url") String url,
               @JsonProperty("error") String error) implements CrawlEvent {}

  /**
   * The crawl has completed.
   */
  record Complete(@JsonProperty("pages_crawled") long pagesCrawled)
      implements CrawlEvent {}
}
