// DO NOT EDIT - auto-generated by alef
// alef:hash:d613fe50b9fedf669983a61b7dac378119f4e2065693327c84f75cfa245e7524
package io.xberg.crawlberg;

/**
 * Data was lost or truncated during transfer.
 */
public class DataLossException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DataLossException with the given message. */
  public DataLossException(final String message) {
    super(message);
  }

  /** Creates a new DataLossException with the given message and cause. */
  public DataLossException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
