// DO NOT EDIT - auto-generated by alef
// alef:hash:398ffc62e592451b302c72cd09eec8713d2c0e5f2a33308379b643e9afce3ad2
package io.xberg.crawlberg;

/**
 * URL denied by SSRF policy: private IP, metadata IP, etc.
 */
public class DeniedByPolicyException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DeniedByPolicyException with the given message. */
  public DeniedByPolicyException(final String message) {
    super(message);
  }

  /** Creates a new DeniedByPolicyException with the given message and cause. */
  public DeniedByPolicyException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
