// DO NOT EDIT - auto-generated by alef
// alef:hash:ed6753aa35e27ad4764a749b35d849473835fb530fcba666ac607635b1333c06
package io.xberg.crawlberg;

/**
 * URL denied by SSRF policy: private IP, metadata IP, etc.
 */
public class DeniedByPolicyException extends SsrfErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new DeniedByPolicyException with the given message. */
    public DeniedByPolicyException(final String message) {
        super(message);
    }

    /** Creates a new DeniedByPolicyException with the given message and cause. */
    public DeniedByPolicyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
