// DO NOT EDIT - auto-generated by alef
// alef:hash:c1b55b15464f8e9ab65f018add2f9aaa481da0495272c555abfe5dfac42196c5
package io.xberg.crawlberg;

/**
 * URL denied by SSRF policy: private IP, metadata IP, etc.
 */
public class DeniedByPolicyException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DeniedByPolicyException with the given message. */
  public DeniedByPolicyException(final String message) {
    super(message);
  }

  /** Creates a new DeniedByPolicyException with the given message and cause. */
  public DeniedByPolicyException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
