// DO NOT EDIT - auto-generated by alef
// alef:hash:372034c3b8af098cb4d76bddf65fde9251873ec46d4fb34002bf1142b67a106d
package io.xberg.crawlberg;

/**
 * URL scheme not in allowlist (e.g., `ftp://` when only `http`/`https` allowed).
 */
public class DisallowedSchemeException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DisallowedSchemeException with the given message. */
  public DisallowedSchemeException(final String message) {
    super(message);
  }

  /** Creates a new DisallowedSchemeException with the given message and cause. */
  public DisallowedSchemeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
