// DO NOT EDIT - auto-generated by alef
// alef:hash:45dd8af390f23c38aefeddb1f198557357dff97d5a7c3b8a88640cc548716979
package io.xberg.crawlberg;

/**
 * URL scheme not in allowlist (e.g., `ftp://` when only `http`/`https`
 * allowed).
 */
public class DisallowedSchemeException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DisallowedSchemeException with the given message. */
  public DisallowedSchemeException(final String message) { super(message); }

  /**
   * Creates a new DisallowedSchemeException with the given message and cause.
   */
  public DisallowedSchemeException(final String message,
                                   final Throwable cause) {
    super(message, cause);
  }
}
