// DO NOT EDIT - auto-generated by alef
// alef:hash:0a47c6602ddbf0857bef848d1ff0fb7f52878eb4a95d2e6e3421c6addb047ffc
package io.xberg.crawlberg;

/**
 * A DNS resolution error occurred.
 */
public class DnsException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DnsException with the given message. */
  public DnsException(final String message) { super(message); }

  /** Creates a new DnsException with the given message and cause. */
  public DnsException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
