// DO NOT EDIT - auto-generated by alef
// alef:hash:969e8ca908a9f8e0dee81ed5b32109eb37586dcc5cf16d908c7c5fac4eefd332
package io.xberg.crawlberg;

/**
 * A DNS resolution error occurred.
 */
public class DnsException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DnsException with the given message. */
  public DnsException(final String message) { super(message); }

  /** Creates a new DnsException with the given message and cause. */
  public DnsException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
