// DO NOT EDIT - auto-generated by alef
// alef:hash:3796df7d281ce46c6268202053527bc8f53d8c685d439a0215f6ba353ee6f8a4
package io.xberg.crawlberg;

/**
 * DNS resolution failed for hostname.
 */
public class DnsResolutionFailedException extends SsrfErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new DnsResolutionFailedException with the given message. */
    public DnsResolutionFailedException(final String message) {
        super(message);
    }

    /** Creates a new DnsResolutionFailedException with the given message and cause. */
    public DnsResolutionFailedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
