// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4d777d02f0a2a1bf03c7101f0df055ebc5319fa2db419d1cdc13cb5a9cd9a39b
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.crawlberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Opt-in encoding applied to a downloaded document's bytes for callers who need the
 * content available in a serializable field rather than reading it from disk.
 *
 * {@code None} (the {@code CrawlConfig.document_content_encoding} default) produces neither — unlike
 * screenshots, base64-encoding a document by default would duplicate an already
 * up-to-{@code document_max_size} buffer (50 MB default) in memory per document.
 */
@SuppressWarnings("PMD")
public enum DocumentContentEncoding {
    /**
     * Populate {@code DownloadedDocument.content_base64} with a base64-encoded copy.
     */
    Base64("base64");


    /** The string value. */
    private final String value;

    DocumentContentEncoding(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static DocumentContentEncoding fromValue(final String value) {
        for (DocumentContentEncoding e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown DocumentContentEncoding value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
