// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:033f5eca7fbc34bfd4671a4317e70b36ebfd9f5f5cf417b942c113c920a71e34
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.crawlberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The type of a feed (RSS, Atom, or JSON Feed).
 */
@SuppressWarnings("PMD")
public enum FeedType {
  /**
   * RSS feed.
   */
  Rss("rss"),
  /**
   * Atom feed.
   */
  Atom("atom"),
  /**
   * JSON Feed.
   */
  JsonFeed("json_feed");

  /** The string value. */
  private final String value;

  FeedType(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static FeedType fromValue(final String value) {
    for (FeedType e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown FeedType value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
