// DO NOT EDIT - auto-generated by alef
// alef:hash:715e5b74c5795fa01980f673dc5d81dda20db9fadd06e7591349391317059268
package io.xberg.crawlberg;

/**
 * The resource is permanently gone (HTTP 410).
 */
public class GoneException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new GoneException with the given message. */
  public GoneException(final String message) {
    super(message);
  }

  /** Creates a new GoneException with the given message and cause. */
  public GoneException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
