// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8606aadccbefed76c287ca4fde6bc5deda5a7aef8b195ad89f091a92e3c86ec3
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.crawlberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Hostname/IP allowlist matcher for SSRF policy.
 *
 * Serializes as an internally-tagged object so each variant is distinguishable on the
 * wire and round-trips losslessly:
 *
 * {@code }{@code json}
 * {"type": "exact",  "value": "api.example.com"}
 * {"type": "suffix", "value": ".example.com"}
 * {"type": "cidr",   "value": "10.0.0.0/8"}
 *
 *
 * A bare JSON string is still accepted on deserialization and resolves to Exact,
 * preserving configs written against the previous untagged representation.
 *
 * Exact: HostMatcher.Exact
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes({
    @JsonSubTypes.Type(value = HostMatcher.Exact.class, name = "exact"),
    @JsonSubTypes.Type(value = HostMatcher.Suffix.class, name = "suffix"),
    @JsonSubTypes.Type(value = HostMatcher.Cidr.class, name = "cidr")
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
public sealed interface HostMatcher {

    /**
     * Exact hostname match (case-insensitive).
     */
    record Exact(@JsonProperty("value") String value) implements HostMatcher { }

    /**
     * Suffix match: ".xberg.io" matches "api.xberg.io" and "xberg.io".
     */
    record Suffix(@JsonProperty("value") String value) implements HostMatcher { }

    /**
     * CIDR match: "10.0.0.0/8" matches IP addresses in that range.
     */
    record Cidr(@JsonProperty("value") String value) implements HostMatcher { }
}
