// DO NOT EDIT - auto-generated by alef
// alef:hash:c6ff3ffda71e7952b10e569073a855c18f8ef146419931f0e0b2c28b5dd6d0a9
package io.xberg.crawlberg;

/**
 * Allowlist entry is not a parseable CIDR block.
 */
public class InvalidCidrException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidCidrException with the given message. */
  public InvalidCidrException(final String message) {
    super(message);
  }

  /** Creates a new InvalidCidrException with the given message and cause. */
  public InvalidCidrException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
