// DO NOT EDIT - auto-generated by alef
// alef:hash:6e26ca1a2eca53ec6b17f45139622492251fe6c3413142dd0ee4e5fe5e86fd23
package io.xberg.crawlberg;

/**
 * The provided configuration is invalid.
 */
public class InvalidConfigException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidConfigException with the given message. */
  public InvalidConfigException(final String message) {
    super(message);
  }

  /** Creates a new InvalidConfigException with the given message and cause. */
  public InvalidConfigException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
