// DO NOT EDIT - auto-generated by alef
// alef:hash:7d06cc8af838a9badb54dd0c4d8022d46e58cebc83bbb846037fbe46125971b0
package io.xberg.crawlberg;

/**
 * The provided configuration is invalid.
 */
public class InvalidConfigException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidConfigException with the given message. */
  public InvalidConfigException(final String message) { super(message); }

  /** Creates a new InvalidConfigException with the given message and cause. */
  public InvalidConfigException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
