// DO NOT EDIT - auto-generated by alef
// alef:hash:b25f293a2658b5e49df9ae7ecbdcfd96c13ada26ecf2a046c108673ffc47752a
package io.xberg.crawlberg;

/**
 * The provided configuration is invalid.
 */
public class InvalidConfigException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidConfigException with the given message. */
  public InvalidConfigException(final String message) { super(message); }

  /** Creates a new InvalidConfigException with the given message and cause. */
  public InvalidConfigException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
