// DO NOT EDIT - auto-generated by alef
// alef:hash:b25f293a2658b5e49df9ae7ecbdcfd96c13ada26ecf2a046c108673ffc47752a
package io.xberg.crawlberg;

/**
 * Allowlist entry is not a parseable CIDR block.
 */
public class InvalidCidrException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidCidrException with the given message. */
  public InvalidCidrException(final String message) { super(message); }

  /** Creates a new InvalidCidrException with the given message and cause. */
  public InvalidCidrException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
