// DO NOT EDIT - auto-generated by alef
// alef:hash:594c3ea00ade8844fe2e68f827df0ed24a8ca3b3fff2c299c616395fc539b849
package io.xberg.crawlberg;

/**
 * The requested page was not found (HTTP 404).
 */
public class NotFoundException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NotFoundException with the given message. */
  public NotFoundException(final String message) { super(message); }

  /** Creates a new NotFoundException with the given message and cause. */
  public NotFoundException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
