// DO NOT EDIT - auto-generated by alef
// alef:hash:58e14a6aee478b37b380db71bc96dc17c2769aa9ac6cda2f462a917f6bde5c17
package io.xberg.crawlberg;

/**
 * The requested page was not found (HTTP 404).
 */
public class NotFoundException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NotFoundException with the given message. */
  public NotFoundException(final String message) {
    super(message);
  }

  /** Creates a new NotFoundException with the given message and cause. */
  public NotFoundException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
