// DO NOT EDIT - auto-generated by alef
// alef:hash:16ea86305c4558bd2c83814817603b55b2297f1c8dcb55e3f00dac8400a58cb2
package io.xberg.crawlberg;

/**
 * Host not on allowlist when an allowlist is configured.
 */
public class NotOnAllowlistException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NotOnAllowlistException with the given message. */
  public NotOnAllowlistException(final String message) { super(message); }

  /** Creates a new NotOnAllowlistException with the given message and cause. */
  public NotOnAllowlistException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
