// DO NOT EDIT - auto-generated by alef
// alef:hash:eeee829b2f2a5125c3c3701ccb5a3dec2f37b2ef0fcb6034f35b1ac1ddb4295b
package io.xberg.crawlberg;

/**
 * Host not on allowlist when an allowlist is configured.
 */
public class NotOnAllowlistException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NotOnAllowlistException with the given message. */
  public NotOnAllowlistException(final String message) {
    super(message);
  }

  /** Creates a new NotOnAllowlistException with the given message and cause. */
  public NotOnAllowlistException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
