// DO NOT EDIT - auto-generated by alef
// alef:hash:fe445c974733c703099671c7022b34ef9df4b85f8fee3260e7ec4150907af3b0
package io.xberg.crawlberg;

/**
 * An unclassified error occurred.
 */
public class OtherException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) { super(message); }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
