// DO NOT EDIT - auto-generated by alef
// alef:hash:9239f0c4a976848daf64796cbf08d6835862f17985c5f163c603390b305b904e
package io.xberg.crawlberg;

/**
 * An unclassified error occurred.
 */
public class OtherException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) { super(message); }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
