// DO NOT EDIT - auto-generated by alef
// alef:hash:928639b574d5fca9c5b51f86fe815c5bc0779c92416dbaa12f74160457caaf3a
package io.xberg.crawlberg;

/**
 * An unclassified error occurred.
 */
public class OtherException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) { super(message); }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
