// DO NOT EDIT - auto-generated by alef
// alef:hash:bef55d0fe3bec2cfa1f7674a824b620a4f93eb1ab5475627f20db419d245a3e5
package io.xberg.crawlberg;

/**
 * The request was rate-limited (HTTP 429).
 */
public class RateLimitedException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RateLimitedException with the given message. */
  public RateLimitedException(final String message) { super(message); }

  /** Creates a new RateLimitedException with the given message and cause. */
  public RateLimitedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
