// DO NOT EDIT - auto-generated by alef
// alef:hash:b3d616a6d38aba44714daa8a8910895db01ce0c0556bbd24fc8f003ba395253a
package io.xberg.crawlberg;

/**
 * The request was rate-limited (HTTP 429).
 */
public class RateLimitedException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RateLimitedException with the given message. */
  public RateLimitedException(final String message) { super(message); }

  /** Creates a new RateLimitedException with the given message and cause. */
  public RateLimitedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
