// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:033f5eca7fbc34bfd4671a4317e70b36ebfd9f5f5cf417b942c113c920a71e34
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.crawlberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Direction for a scroll action.
 */
@SuppressWarnings("PMD")
public enum ScrollDirection {
  /**
   * Scroll upward.
   */
  Up("up"),
  /**
   * Scroll downward.
   */
  Down("down");

  /** The string value. */
  private final String value;

  ScrollDirection(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static ScrollDirection fromValue(final String value) {
    for (ScrollDirection e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown ScrollDirection value: " +
                                       value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
