// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:99a9403abedfcae04d3703781a3f59ae4f4cca231d054b1526efac68aa0a487b
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.crawlberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Direction for a scroll action.
 */
@SuppressWarnings("PMD")
public enum ScrollDirection {
    /**
     * Scroll upward.
     */
    Up("up"),
    /**
     * Scroll downward.
     */
    Down("down");


    /** The string value. */
    private final String value;

    ScrollDirection(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ScrollDirection fromValue(final String value) {
        for (ScrollDirection e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown ScrollDirection value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
