// DO NOT EDIT - auto-generated by alef
// alef:hash:0a47c6602ddbf0857bef848d1ff0fb7f52878eb4a95d2e6e3421c6addb047ffc
package io.xberg.crawlberg;

/**
 * A server error occurred (HTTP 5xx).
 */
public class ServerErrorException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ServerErrorException with the given message. */
  public ServerErrorException(final String message) { super(message); }

  /** Creates a new ServerErrorException with the given message and cause. */
  public ServerErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
