// DO NOT EDIT - auto-generated by alef
// alef:hash:75130b11765cbed0a1ea2b5bcffe59620c4045cee1c7cece391c5e3fa47b10e0
package io.xberg.crawlberg;

/**
 * An SSL/TLS error occurred.
 */
public class SslException extends CrawlErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new SslException with the given message. */
    public SslException(final String message) {
        super(message);
    }

    /** Creates a new SslException with the given message and cause. */
    public SslException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
