// DO NOT EDIT - auto-generated by alef
// alef:hash:0ce4d753fdb4854e44358639dcbaebee3449a4afa142dbc4f0a72aa72c214648
package io.xberg.crawlberg;

/**
 * An SSL/TLS error occurred.
 */
public class SslException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SslException with the given message. */
  public SslException(final String message) { super(message); }

  /** Creates a new SslException with the given message and cause. */
  public SslException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
