// DO NOT EDIT - auto-generated by alef
// alef:hash:55a366098facb9cb0635056fee27c362dabf933434f3e82634be8fcd4e19f9a9
package io.xberg.crawlberg;

/**
 * An SSL/TLS error occurred.
 */
public class SslException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SslException with the given message. */
  public SslException(final String message) {
    super(message);
  }

  /** Creates a new SslException with the given message and cause. */
  public SslException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
