// DO NOT EDIT - auto-generated by alef
// alef:hash:0a47c6602ddbf0857bef848d1ff0fb7f52878eb4a95d2e6e3421c6addb047ffc
package io.xberg.crawlberg;

/**
 * A URL was rejected by SSRF policy (private IP, metadata, disallowed scheme,
 * etc).
 */
public class SsrfPolicyViolationException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SsrfPolicyViolationException with the given message. */
  public SsrfPolicyViolationException(final String message) { super(message); }

  /**
   * Creates a new SsrfPolicyViolationException with the given message and
   * cause.
   */
  public SsrfPolicyViolationException(final String message,
                                      final Throwable cause) {
    super(message, cause);
  }
}
