// DO NOT EDIT - auto-generated by alef
// alef:hash:9734598091b20b568807c27946360e78323036ccf66861dc98a52d1bce70f361
package io.xberg.crawlberg;

/**
 * SSRF validation error.
 */
public class SsrfErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new SsrfErrorException with the given message. */
  public SsrfErrorException(final String message) { super(message); }

  /** Creates a new SsrfErrorException with the given message and cause. */
  public SsrfErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
