// DO NOT EDIT - auto-generated by alef
// alef:hash:1016b05fa062cb2ed3f873777e53123e30b584c0e9cb912d64a5db701af8bccd
package io.xberg.crawlberg;

/**
 * A URL was rejected by SSRF policy (private IP, metadata, disallowed scheme, etc).
 */
public class SsrfPolicyViolationException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SsrfPolicyViolationException with the given message. */
  public SsrfPolicyViolationException(final String message) {
    super(message);
  }

  /** Creates a new SsrfPolicyViolationException with the given message and cause. */
  public SsrfPolicyViolationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
