// DO NOT EDIT - auto-generated by alef
// alef:hash:3a1917e5db668dfe5f72cf0122d3b3eec3fb0855563c85c74cfa0f0d11fc4ae5
package io.xberg.crawlberg;

/**
 * A URL was rejected by SSRF policy (private IP, metadata, disallowed scheme,
 * etc).
 */
public class SsrfPolicyViolationException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SsrfPolicyViolationException with the given message. */
  public SsrfPolicyViolationException(final String message) { super(message); }

  /**
   * Creates a new SsrfPolicyViolationException with the given message and
   * cause.
   */
  public SsrfPolicyViolationException(final String message,
                                      final Throwable cause) {
    super(message, cause);
  }
}
