// DO NOT EDIT - auto-generated by alef
// alef:hash:57c8318d531ed2b7c2fecf3adb6382a4168daf9489368319960022e7a25272f6
package io.xberg.crawlberg;

/**
 * SSRF validation error.
 */
public class SsrfErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new SsrfErrorException with the given message. */
  public SsrfErrorException(final String message) {
    super(message);
  }

  /** Creates a new SsrfErrorException with the given message and cause. */
  public SsrfErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
