// DO NOT EDIT - auto-generated by alef
// alef:hash:13066d16bcf2cb5499552a64a3b4dadbd1ac92ea8504f7b2499ac1b578ad4480
package io.xberg.crawlberg;

/**
 * The request timed out.
 */
public class TimeoutException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TimeoutException with the given message. */
  public TimeoutException(final String message) {
    super(message);
  }

  /** Creates a new TimeoutException with the given message and cause. */
  public TimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
