// DO NOT EDIT - auto-generated by alef
// alef:hash:9239f0c4a976848daf64796cbf08d6835862f17985c5f163c603390b305b904e
package io.xberg.crawlberg;

/**
 * Too many HTTP redirects encountered during validation.
 */
public class TooManyRedirectsException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TooManyRedirectsException with the given message. */
  public TooManyRedirectsException(final String message) { super(message); }

  /**
   * Creates a new TooManyRedirectsException with the given message and cause.
   */
  public TooManyRedirectsException(final String message,
                                   final Throwable cause) {
    super(message, cause);
  }
}
