// DO NOT EDIT - auto-generated by alef
package io.xberg.crawlberg;

/**
 * Too many HTTP redirects encountered during validation.
 */
public class TooManyRedirectsException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TooManyRedirectsException with the given message. */
  public TooManyRedirectsException(final String message) {
    super(message);
  }

  /** Creates a new TooManyRedirectsException with the given message and cause. */
  public TooManyRedirectsException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
