// DO NOT EDIT - auto-generated by alef
// alef:hash:9ff7a9b8c0bd359476d1c76a8c03769d326d18c4072e444ed4daf29f49ec2875
package io.xberg.crawlberg;

/**
 * Too many HTTP redirects encountered during validation.
 */
public class TooManyRedirectsException extends SsrfErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TooManyRedirectsException with the given message. */
  public TooManyRedirectsException(final String message) { super(message); }

  /**
   * Creates a new TooManyRedirectsException with the given message and cause.
   */
  public TooManyRedirectsException(final String message,
                                   final Throwable cause) {
    super(message, cause);
  }
}
