// DO NOT EDIT - auto-generated by alef
// alef:hash:1930dd72c49ae9e2d441a37151f5d872ded40864ee278c2b71abc7c061991b24
package io.xberg.crawlberg;

/**
 * The request was unauthorized (HTTP 401).
 */
public class UnauthorizedException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new UnauthorizedException with the given message. */
  public UnauthorizedException(final String message) {
    super(message);
  }

  /** Creates a new UnauthorizedException with the given message and cause. */
  public UnauthorizedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
