// DO NOT EDIT - auto-generated by alef
// alef:hash:c597cef220369dd54ee548b52970cbf3a5df9c9c616a255ddfb551b6438a8bbc
package io.xberg.crawlberg;

/**
 * The request was unauthorized (HTTP 401).
 */
public class UnauthorizedException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new UnauthorizedException with the given message. */
  public UnauthorizedException(final String message) {
    super(message);
  }

  /** Creates a new UnauthorizedException with the given message and cause. */
  public UnauthorizedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
