// DO NOT EDIT - auto-generated by alef
// alef:hash:033f5eca7fbc34bfd4671a4317e70b36ebfd9f5f5cf417b942c113c920a71e34
package io.xberg.crawlberg;

/**
 * The requested capability is not supported by the active backend or build.
 */
public class UnsupportedException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new UnsupportedException with the given message. */
  public UnsupportedException(final String message) { super(message); }

  /** Creates a new UnsupportedException with the given message and cause. */
  public UnsupportedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
