// DO NOT EDIT - auto-generated by alef
// alef:hash:45dd8af390f23c38aefeddb1f198557357dff97d5a7c3b8a88640cc548716979
package io.xberg.crawlberg;

/**
 * The requested capability is not supported by the active backend or build.
 */
public class UnsupportedException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new UnsupportedException with the given message. */
  public UnsupportedException(final String message) { super(message); }

  /** Creates a new UnsupportedException with the given message and cause. */
  public UnsupportedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
