// DO NOT EDIT - auto-generated by alef
// alef:hash:1ea143ac7420ef5f2c7706944368a99e0f7655efce268bf208ccdb4392cce449
package io.xberg.crawlberg;

/**
 * The requested capability is not supported by the active backend or build.
 */
public class UnsupportedException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new UnsupportedException with the given message. */
  public UnsupportedException(final String message) { super(message); }

  /** Creates a new UnsupportedException with the given message and cause. */
  public UnsupportedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
