// DO NOT EDIT - auto-generated by alef
// alef:hash:109af5f321d63c1f5f62bc4956de6678f318b8e58c602d1b4c36817517b98bbe
package io.xberg.crawlberg;

/**
 * The request was blocked by a WAF or bot protection (HTTP 403 with WAF indicators).
 *
 * `vendor` is the lowercase identifier of the detected WAF (e.g. "cloudflare",
 * "datadome"). When the engine cannot identify the vendor, it uses "unknown".
 * `message` is the freeform description for logs and human readers.
 *
 * The stable error tag remains `forbidden: waf/blocked: MESSAGE` so existing
 * log-grep patterns and cross-language bindings continue to work; vendor is
 * surfaced separately for structured consumers.
 */
public class WafBlockedException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new WafBlockedException with the given message. */
  public WafBlockedException(final String message) {
    super(message);
  }

  /** Creates a new WafBlockedException with the given message and cause. */
  public WafBlockedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
