// DO NOT EDIT - auto-generated by alef
// alef:hash:0ae8279929116deaefb54c54ac95177c5aca52b127e16fa5df6caafb5b50ff85
package io.xberg.crawlberg;

/**
 * The request was blocked by a WAF or bot protection (HTTP 403 with WAF indicators).
 *
 * `vendor` is the lowercase identifier of the detected WAF (e.g. "cloudflare",
 * "datadome"). When the engine cannot identify the vendor, it uses "unknown".
 * `message` is the freeform description for logs and human readers.
 *
 * The stable error tag remains `forbidden: waf/blocked: MESSAGE` so existing
 * log-grep patterns and cross-language bindings continue to work; vendor is
 * surfaced separately for structured consumers.
 */
public class WafBlockedException extends CrawlErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new WafBlockedException with the given message. */
  public WafBlockedException(final String message) {
    super(message);
  }

  /** Creates a new WafBlockedException with the given message and cause. */
  public WafBlockedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
