<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ed6753aa35e27ad4764a749b35d849473835fb530fcba666ac607635b1333c06
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

declare(strict_types=1);

namespace Crawlberg\E2e;

use Crawlberg\Crawlberg;
use Crawlberg\CrawlConfig;
use PHPUnit\Framework\TestCase;

/** E2e tests for category: proxy. */
final class ProxyTest extends TestCase
{
    /** Proxy with username and password credentials authenticates successfully */
    public function test_proxy_authenticated(): void
    {
        $engine_config = CrawlConfig::from_json(json_encode([
            'proxy' => ['password' => 'proxypass', 'url' => 'http://127.0.0.1:8889', 'username' => 'proxyuser'],
            'respectRobotsTxt' => false,
        ]));
        $engine = Crawlberg::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/proxy_authenticated';
        $result = Crawlberg::crawl($engine, $url);

        $this->assertEquals(0, count($result->getPages()));
    }

    /** Configure proxy URL and successfully crawl through it */
    public function test_proxy_basic_success(): void
    {
        $engine_config = CrawlConfig::from_json(json_encode([
            'proxy' => ['url' => 'http://127.0.0.1:8888'],
            'respectRobotsTxt' => false,
        ]));
        $engine = Crawlberg::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/proxy_basic_success';
        $result = Crawlberg::crawl($engine, $url);

        $this->assertEquals(0, count($result->getPages()));
    }
}
