<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:852deb9ed970b5103934444e503fcdd8e91572c2ee116e8662f72886802ece57
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Crawlberg\E2e;

use PHPUnit\Framework\TestCase;
use Crawlberg\Crawlberg;
use Crawlberg\CrawlConfig;

/** E2e tests for category: proxy. */
final class ProxyTest extends TestCase
{
    /** Proxy with username and password credentials authenticates successfully */
    public function test_proxy_authenticated(): void
    {
        $engine_config = CrawlConfig::from_json(json_encode(["proxy" => ["password" => "proxypass", "url" => "http://127.0.0.1:8889", "username" => "proxyuser"], "respectRobotsTxt" => false]));
        $engine = Crawlberg::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/proxy_authenticated';
        $result = Crawlberg::crawl($engine, $url);

        $this->assertEquals(0, count($result->getPages()));


    }


    /** Configure proxy URL and successfully crawl through it */
    public function test_proxy_basic_success(): void
    {
        $engine_config = CrawlConfig::from_json(json_encode(["proxy" => ["url" => "http://127.0.0.1:8888"], "respectRobotsTxt" => false]));
        $engine = Crawlberg::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/proxy_basic_success';
        $result = Crawlberg::crawl($engine, $url);

        $this->assertEquals(0, count($result->getPages()));


    }

}
