<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5c2d8c2667131ed0ad3b2e60f641030e76c8f32959008f5bc6f4c0715e3d9008
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Crawlberg\E2e;

use PHPUnit\Framework\TestCase;
use Crawlberg\Crawlberg;
use Crawlberg\CrawlConfig;

/** E2e tests for category: validation. */
final class ValidationTest extends TestCase
{
    /** Browser endpoint must be a valid ws:// or wss:// URL, not http:// */
    public function test_validation_browser_endpoint_invalid(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["browser" => ["endpoint" => "http://not-websocket:3000", "mode" => "always"]]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_browser_endpoint_invalid';
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/endpoint/', $e->getMessage()) === 1 || preg_match('/endpoint/', get_class($e)) === 1, 'expected exception message or class name to match endpoint');
        }

    }


    /** auth object with empty username in basic auth is rejected */
    public function test_validation_invalid_auth_config(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["auth" => ["password" => "secret", "type" => "basic"]]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_invalid_auth_config';
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/auth/', $e->getMessage()) === 1 || preg_match('/auth/', get_class($e)) === 1, 'expected exception message or class name to match auth');
        }

    }


    /** Invalid regex in exclude_paths is rejected */
    public function test_validation_invalid_exclude_regex(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["excludePaths" => ["(unclosed"]]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_invalid_exclude_regex';
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/exclude_path/', $e->getMessage()) === 1 || preg_match('/exclude_path/', get_class($e)) === 1, 'expected exception message or class name to match exclude_path');
        }

    }


    /** Invalid regex in include_paths is rejected */
    public function test_validation_invalid_include_regex(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["includePaths" => ["[invalid"]]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_invalid_include_regex';
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/include_path/', $e->getMessage()) === 1 || preg_match('/include_path/', get_class($e)) === 1, 'expected exception message or class name to match include_path');
        }

    }


    /** proxy with invalid URL like 'not-a-url' is rejected */
    public function test_validation_invalid_proxy_url(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["proxy" => ["url" => "not-a-url"]]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_invalid_proxy_url';
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/proxy/', $e->getMessage()) === 1 || preg_match('/proxy/', get_class($e)) === 1, 'expected exception message or class name to match proxy');
        }

    }


    /** Retry code outside 100-599 is rejected */
    public function test_validation_invalid_retry_code(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["retryCodes" => [999]]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_invalid_retry_code';
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/retry code/', $e->getMessage()) === 1 || preg_match('/retry code/', get_class($e)) === 1, 'expected exception message or class name to match retry code');
        }

    }


    /** max_concurrent=0 is rejected as invalid config (minimum is 1) */
    public function test_validation_max_concurrent_zero(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["maxConcurrent" => 0]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_max_concurrent_zero';
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/max_concurrent/', $e->getMessage()) === 1 || preg_match('/max_concurrent/', get_class($e)) === 1, 'expected exception message or class name to match max_concurrent');
        }

    }


    /** max_depth=200 exceeds limit of 100 */
    public function test_validation_max_depth_too_high(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["maxDepth" => 200]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_max_depth_too_high';
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/max_depth/', $e->getMessage()) === 1 || preg_match('/max_depth/', get_class($e)) === 1, 'expected exception message or class name to match max_depth');
        }

    }


    /** max_pages=0 is rejected as invalid config */
    public function test_validation_max_pages_zero(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["maxPages" => 0]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_max_pages_zero';
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/max_pages/', $e->getMessage()) === 1 || preg_match('/max_pages/', get_class($e)) === 1, 'expected exception message or class name to match max_pages');
        }

    }


    /** max_redirects > 100 is rejected as invalid config */
    public function test_validation_max_redirects_too_high(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["maxRedirects" => 200]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_max_redirects_too_high';
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/max_redirects/', $e->getMessage()) === 1 || preg_match('/max_redirects/', get_class($e)) === 1, 'expected exception message or class name to match max_redirects');
        }

    }


    /** max_body_size set to -1 is rejected as invalid config */
    public function test_validation_negative_body_size(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["maxBodySize" => 0]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_negative_body_size';
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/body_size/', $e->getMessage()) === 1 || preg_match('/body_size/', get_class($e)) === 1, 'expected exception message or class name to match body_size');
        }

    }


    /** SSRF allowlist permits a loopback mock server while private-network protection remains enabled */
    public function test_validation_ssrf_allowlisted_loopback(): void
    {
        $engine_config = CrawlConfig::from_json(json_encode(["respectRobotsTxt" => false, "ssrf" => ["allowlist" => [["type" => "cidr", "value" => "127.0.0.0/8"]], "denyPrivate" => true, "maxRedirects" => 5], "ssrfDenyPrivateExplicit" => true]));
        $engine = Crawlberg::createEngine($engine_config);
        $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_ssrf_allowlisted_loopback';
        $result = Crawlberg::scrape($engine, $url);

        $this->assertEquals(200, $result->statusCode);
        $this->assertEquals("Allowlisted", ($result->getMetadata()->title ?? null));


    }


    /** SSRF policy rejects an IPv4 loopback address embedded in an IPv6 literal */
    public function test_validation_ssrf_ipv4_mapped_ipv6_denied(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["ssrf" => ["denyPrivate" => true], "ssrfDenyPrivateExplicit" => true]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = "http://[::ffff:127.0.0.1]/";
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/ssrf_policy_violation/', $e->getMessage()) === 1 || preg_match('/ssrf_policy_violation/', get_class($e)) === 1, 'expected exception message or class name to match ssrf_policy_violation');
        }

    }


    /** scrape() rejects loopback addresses by default SSRF policy */
    public function test_validation_ssrf_loopback_denied(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["ssrfDenyPrivateExplicit" => true]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = "http://127.0.0.1:9/";
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/ssrf_policy_violation/', $e->getMessage()) === 1 || preg_match('/ssrf_policy_violation/', get_class($e)) === 1, 'expected exception message or class name to match ssrf_policy_violation');
        }

    }


    /** SSRF policy rejects an IPv4 loopback address embedded in the well-known NAT64 prefix */
    public function test_validation_ssrf_nat64_loopback_denied(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["ssrf" => ["denyPrivate" => true], "ssrfDenyPrivateExplicit" => true]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = "http://[64:ff9b::7f00:1]/";
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/ssrf_policy_violation/', $e->getMessage()) === 1 || preg_match('/ssrf_policy_violation/', get_class($e)) === 1, 'expected exception message or class name to match ssrf_policy_violation');
        }

    }


    /** Zero request timeout is rejected as invalid config */
    public function test_validation_timeout_zero(): void
    {
        try {
            $engine_config = CrawlConfig::from_json(json_encode(["requestTimeout" => 0]));
            $engine = Crawlberg::createEngine($engine_config);
            $url = getenv('MOCK_SERVER_URL') . '/fixtures/validation_timeout_zero';
            Crawlberg::scrape($engine, $url);
            $this->fail('Expected an exception to be thrown');
        } catch (\Exception $e) {
            $this->assertTrue(preg_match('/request_timeout/', $e->getMessage()) === 1 || preg_match('/request_timeout/', get_class($e)) === 1, 'expected exception message or class name to match request_timeout');
        }

    }

}
