// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:969e8ca908a9f8e0dee81ed5b32109eb37586dcc5cf16d908c7c5fac4eefd332
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
		setupFiles: ["./setup.ts"],
	},
});
