// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a6b6e5ccad62a2556f32d9dbab9ed253ee9aba56b16e9154972678879e80d0c1
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
		setupFiles: ["./setup.ts"],
	},
});
