// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:65d00c380dce0294c64cc0da299dbac854d39c7fedfd7f128992917432061eaa
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
		setupFiles: ["./setup.ts"],
	},
});
