// Generated by alef. Do not edit by hand.
// alef:hash:3796df7d281ce46c6268202053527bc8f53d8c685d439a0215f6ba353ee6f8a4
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.crawlberg.android

/** Article metadata extracted from `article:*` Open Graph tags. */
data class ArticleMetadata(
    /** The article publication time. */
    val publishedTime: String? = null,
    /** The article modification time. */
    val modifiedTime: String? = null,
    /** The article author. */
    val author: String? = null,
    /** The article section. */
    val section: String? = null,
    /** The article tags. */
    val tags: List<String> = emptyList(),
)
