// Generated by alef. Do not edit by hand.
// alef:hash:18f65d1dbe89eb573bc26a4f0ef12eaf5cdc757fda3ab9f7c15acdcd95b3f589
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.crawlberg.android

/** Authentication configuration. */
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, property = "type", visible = false)
@com.fasterxml.jackson.annotation.JsonSubTypes(
    com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = AuthConfig.Basic::class, name = "basic"),
    com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = AuthConfig.Bearer::class, name = "bearer"),
    com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = AuthConfig.Header::class, name = "header")
)
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
sealed class AuthConfig {
    /** HTTP Basic authentication. */
    data class Basic(val username: String, val password: String) : AuthConfig()
    /** Bearer token authentication. */
    data class Bearer(val token: String) : AuthConfig()
    /** Custom authentication header. */
    data class Header(val name: String, val value: String) : AuthConfig()
}
