// Generated by alef. Do not edit by hand.
// alef:hash:ba2cb51ad116c249bfe98aa351e7d9333c39a66e51e9c855b875a92b885687cd
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.crawlberg.android

/** Result from a single URL in a batch scrape operation. */
data class BatchScrapeResult(
    /** The URL that was scraped. */
    val url: String = "",
    /** The scrape result, if successful. */
    val result: ScrapeResult? = null,
    /** The error message, if the scrape failed. */
    val error: String? = null,
)
