// Generated by alef. Do not edit by hand.
// alef:hash:9239f0c4a976848daf64796cbf08d6835862f17985c5f163c603390b305b904e
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.crawlberg.android

/** Browser backend used for JavaScript rendering. */
enum class BrowserBackend {
    /** Existing Chromium/CDP backend powered by chromiumoxide. */
    @com.fasterxml.jackson.annotation.JsonProperty("chromiumoxide") CHROMIUMOXIDE,
    /** Crawlberg-owned native browser backend derived from Obscura. */
    @com.fasterxml.jackson.annotation.JsonProperty("native") NATIVE;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
    when (this) {
        CHROMIUMOXIDE -> "chromiumoxide"
        NATIVE -> "native"
    }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): BrowserBackend =
        when (value) {
            "chromiumoxide" -> CHROMIUMOXIDE
            "native" -> NATIVE
            else -> throw IllegalArgumentException("Unknown BrowserBackend value: $value")
        }
    }
}
