// Generated by alef. Do not edit by hand.
// alef:hash:45dd8af390f23c38aefeddb1f198557357dff97d5a7c3b8a88640cc548716979
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.crawlberg.android

/**
 * Browser-specific extras populated when the native browser backend was used.
 *
 * Available on `ScrapeResult.browser` when `BrowserBackend.Native` handled the request.
 */
data class BrowserExtras(
    /** Return value of `BrowserConfig.eval_script`, if provided. */
    val evalResult: Any? = null,
    /**
     * Network events captured during page navigation (only populated when
     * `BrowserConfig.capture_network_events` is true).
     */
    val networkEvents: List<ResponseMeta> = emptyList(),
    /**
     * All non-expired cookies present in the browser's cookie jar after
     * navigation completes (includes both prior cookies and server Set-Cookie).
     */
    val cookies: List<CookieInfo> = emptyList(),
)
