// Generated by alef. Do not edit by hand.
// alef:hash:5877ff7fa5d71693c4a00a3df926a0367df9eeb72a20238a8810361f85902813
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.crawlberg.android

/** Browser backend used for JavaScript rendering. */
enum class BrowserBackend {
    /** Existing Chromium/CDP backend powered by chromiumoxide. */
    @com.fasterxml.jackson.annotation.JsonProperty("chromiumoxide") CHROMIUMOXIDE,
    /** Crawlberg-owned native browser backend derived from Obscura. */
    @com.fasterxml.jackson.annotation.JsonProperty("native") NATIVE;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            CHROMIUMOXIDE -> "chromiumoxide"
            NATIVE -> "native"
        }

    override fun toString(): String = toWire()

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): BrowserBackend =
            when (value) {
                "chromiumoxide" -> CHROMIUMOXIDE
                "native" -> NATIVE
                else -> throw IllegalArgumentException("Unknown BrowserBackend value: $value")
            }
    }
}
