// Generated by alef. Do not edit by hand.
// alef:hash:aaf757d71f91269ef96dadbc9f50931be13f01c7e61e5bdfaf4a7458c0959891
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.crawlberg.android

/** Result of citation conversion. */
data class CitationResult(
    /** Markdown with links replaced by numbered citations. */
    val content: String = "",
    /** Numbered reference list: (index, url, text). */
    val references: List<CitationReference> = emptyList(),
)
