// Generated by alef. Do not edit by hand.
// alef:hash:383d495e960d1581f6322a944c6a06ba66916bc679618eb84acc9bab4ac968ca

package io.xberg.crawlberg.android

class CrawlbergBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
