// Generated by alef. Do not edit by hand.
// alef:hash:bef55d0fe3bec2cfa1f7674a824b620a4f93eb1ab5475627f20db419d245a3e5

package io.xberg.crawlberg.android

class CrawlbergBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
