// Generated by alef. Do not edit by hand.
// alef:hash:510a6e0666fe4ad0ab3eeb8d884a6da4220ee326048be606ecdd5ef51a9d89e9
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.crawlberg.android

/**
 * Request to begin a single-URL streaming crawl.
 *
 * Wraps a single seed URL for delivery through the streaming-adapter binding
 * surface. Required as a struct because alef's streaming adapter requires a
 * named request type — primitives are not supported.
 */
data class CrawlStreamRequest(
    /** The seed URL to crawl. */
    val url: String = "",
)
