// Generated by alef. Do not edit by hand.
// alef:hash:45dd8af390f23c38aefeddb1f198557357dff97d5a7c3b8a88640cc548716979
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.crawlberg.android

/** Proxy configuration for HTTP requests. */
data class ProxyConfig(
    /** Proxy URL (e.g. "http://proxy:8080", "socks5://proxy:1080"). */
    val url: String = "",
    /** Optional username for proxy authentication. */
    val username: String? = null,
    /** Optional password for proxy authentication. */
    val password: String? = null,
)
