// Generated by alef. Do not edit by hand.
// alef:hash:16ea86305c4558bd2c83814817603b55b2297f1c8dcb55e3f00dac8400a58cb2
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.crawlberg.android

/** A URL entry from a sitemap. */
data class SitemapUrl(
    /** The URL. */
    val url: String = "",
    /** The last modification date, if present. */
    val lastmod: String? = null,
    /** The change frequency, if present. */
    val changefreq: String? = null,
    /** The priority, if present. */
    val priority: String? = null,
)
