// Generated by alef. Do not edit by hand.
// alef:hash:0bad31cd2a645ac05bbcdcde5415acdd5d8f9669d1f59b7bf71a33558fbf2694
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.crawlberg.android

/** SSRF validation error. */
sealed class SsrfError(message: String) : Exception(message) {
    data class DeniedByPolicy(val reason: String) : SsrfError("denied by SSRF policy: {reason}")
    object NotOnAllowlist : SsrfError("host not on allowlist")
    data class DnsResolutionFailed(val field0: String) : SsrfError("dns resolution failed: $field0")
    data class InvalidUrl(val field0: String) : SsrfError("invalid URL: $field0")
    data class DisallowedScheme(val field0: String) : SsrfError("disallowed scheme: $field0")
    object TooManyRedirects : SsrfError("too many redirects")
}
