// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:161298fec273f5811eab14fc4b5f191bc022703db6b8fe3b5bffd1dd1edb55d6
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Crawlberg
import RustBridge

/// E2e tests for category: links.
final class LinksTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testLinksAnchorFragment() async throws {
        // Identifies fragment-only links as anchor type
        let engineObj = try createEngine(config: nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_LINKS_ANCHOR_FRAGMENT"] ?? (AlefE2EMockServer.baseURL + "/fixtures/links_anchor_fragment")
        let result = try await Crawlberg.scrape(engine: engineObj, url: url)
        XCTAssertTrue(result.links().contains(where: { $0.linkType().toString().contains("anchor") }), "expected to contain: \("anchor")")
    }

    func testLinksBaseTag() async throws {
        // Resolves relative URLs using base tag href
        let engineObj = try createEngine(config: nil)
        let url = AlefE2EMockServer.baseURL + "/fixtures/links_base_tag"
        let result = try await Crawlberg.scrape(engine: engineObj, url: url)
        XCTAssertGreaterThan(result.links().count, 2)
        XCTAssertTrue(result.links().contains(where: { $0.url().toString().contains("example.com") }), "expected to contain: \("example.com")")
    }

    func testLinksDocumentTypes() async throws {
        // Detects PDF, DOCX, XLSX links as document type
        let engineObj = try createEngine(config: nil)
        let url = ProcessInfo.processInfo.environment["MOCK_SERVER_LINKS_DOCUMENT_TYPES"] ?? (AlefE2EMockServer.baseURL + "/fixtures/links_document_types")
        let result = try await Crawlberg.scrape(engine: engineObj, url: url)
        XCTAssertTrue(result.links().contains(where: { $0.linkType().toString().contains("document") }), "expected to contain: \("document")")
    }

    func testLinksEmptyHref() async throws {
        // Handles empty href attributes without errors
        let engineObj = try createEngine(config: nil)
        let url = AlefE2EMockServer.baseURL + "/fixtures/links_empty_href"
        let result = try await Crawlberg.scrape(engine: engineObj, url: url)
        XCTAssertGreaterThan(result.links().count, 0)
        XCTAssertTrue(result.links().contains(where: { $0.url().toString().contains("/valid") }), "expected to contain: \("/valid")")
    }

    func testLinksInternalExternalClassification() async throws {
        // Correctly classifies internal vs external links by domain
        let engineObj = try createEngine(config: nil)
        let url = AlefE2EMockServer.baseURL + "/fixtures/links_internal_external_classification"
        let result = try await Crawlberg.scrape(engine: engineObj, url: url)
        XCTAssertGreaterThan(result.links().count, 4)
        XCTAssertTrue(result.links().contains(where: { !$0.url().toString().isEmpty }), "expected non-empty value")
    }

    func testLinksMailtoJavascriptSkip() async throws {
        // Skips mailto:, javascript:, and tel: scheme links
        let engineObj = try createEngine(config: nil)
        let url = AlefE2EMockServer.baseURL + "/fixtures/links_mailto_javascript_skip"
        let result = try await Crawlberg.scrape(engine: engineObj, url: url)
        XCTAssertGreaterThan(result.links().count, 0)
        XCTAssertFalse(result.links().contains(where: { $0.url().toString().contains("mailto:") }), "expected NOT to contain: \("mailto:")")
    }

    func testLinksProtocolRelative() async throws {
        // Handles protocol-relative URLs (//example.com) correctly
        let engineObj = try createEngine(config: nil)
        let url = AlefE2EMockServer.baseURL + "/fixtures/links_protocol_relative"
        let result = try await Crawlberg.scrape(engine: engineObj, url: url)
        XCTAssertGreaterThan(result.links().count, 1)
        XCTAssertTrue(result.links().contains(where: { $0.url().toString().contains("http://cdn.example.com/resource") }), "expected to contain: \("http://cdn.example.com/resource")")
        XCTAssertTrue(result.links().contains(where: { $0.url().toString().contains("http://images.example.com/photo.jpg") }), "expected to contain: \("http://images.example.com/photo.jpg")")
    }

    func testLinksRelAttributes() async throws {
        // Preserves rel=nofollow and rel=canonical attributes
        let engineObj = try createEngine(config: nil)
        let url = AlefE2EMockServer.baseURL + "/fixtures/links_rel_attributes"
        let result = try await Crawlberg.scrape(engine: engineObj, url: url)
        XCTAssertGreaterThan(result.links().count, 0)
    }

    func testLinksRelativeParent() async throws {
        // Resolves ../ and ./ relative parent path links correctly
        let engineObj = try createEngine(config: nil)
        let url = AlefE2EMockServer.baseURL + "/fixtures/links_relative_parent"
        let result = try await Crawlberg.scrape(engine: engineObj, url: url)
        XCTAssertGreaterThan(result.links().count, 3)
    }

}
