// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fe445c974733c703099671c7022b34ef9df4b85f8fee3260e7ec4150907af3b0
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// A bad gateway error occurred (HTTP 502).
/// </summary>
public class BadGatewayException : CrawlErrorException {
  public BadGatewayException(string message) : base(message) {}

  public BadGatewayException(string message, Exception innerException)
      : base(message, innerException) {}
}
