// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:928639b574d5fca9c5b51f86fe815c5bc0779c92416dbaa12f74160457caaf3a
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The browser failed to launch, connect, or navigate.
/// </summary>
public class BrowserErrorException : CrawlErrorException {
  public BrowserErrorException(string message) : base(message) {}

  public BrowserErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
