// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1ea143ac7420ef5f2c7706944368a99e0f7655efce268bf208ccdb4392cce449
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The browser failed to launch, connect, or navigate.
/// </summary>
public class BrowserErrorException : CrawlErrorException {
  public BrowserErrorException(string message) : base(message) {}

  public BrowserErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
