// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9dbb8065f6eb49dbf470bbe8bebea0028c3e16836f3201a4e0a8c30fe5c286b0
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The browser page load or rendering timed out.
/// </summary>
public class BrowserTimeoutException : CrawlErrorException {
  public BrowserTimeoutException(string message) : base(message) {}

  public BrowserTimeoutException(string message, Exception innerException)
      : base(message, innerException) {}
}
