// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:14c16bc487e02ca5653b830fc9f08d8812609efe50f0c257d3f0984c5c454860
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The browser failed to launch, connect, or navigate.
/// </summary>
public class BrowserErrorException : CrawlErrorException
{
    public BrowserErrorException(string message) : base(message) { }

    public BrowserErrorException(string message, Exception innerException) : base(message, innerException) { }
}
