// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0d1febf1fb71f67edc0fc4aa0c688f555975a936433b2e7f576e23f9efaa0707
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Crawlberg;

/// <summary>
/// Browser fallback configuration.
/// </summary>
public sealed record BrowserConfig
{
    /// <summary>
    /// When to use the headless browser fallback.
    /// </summary>
    [JsonPropertyName("mode")]
    public BrowserMode Mode { get; init; } = BrowserMode.Auto;

    /// <summary>
    /// Browser backend used to render JavaScript-heavy pages.
    /// </summary>
    [JsonPropertyName("backend")]
    public BrowserBackend Backend { get; init; } = BrowserBackend.Chromiumoxide;

    /// <summary>
    /// CDP WebSocket endpoint for connecting to an external browser instance.
    /// </summary>
    [JsonPropertyName("endpoint")]
    public string? Endpoint { get; init; } = null;

    /// <summary>
    /// Timeout for browser page load and rendering (in milliseconds when serialized).
    /// </summary>
    [JsonPropertyName("timeout")]
    public ulong? Timeout { get; init; } = null;

    /// <summary>
    /// Overall deadline for a single browser fetch, covering browser launch (or
    /// page acquisition from a shared pool), page setup, navigation, rendering,
    /// and screenshot capture. Must exceed `timeout` to leave room for launch
    /// and setup overhead; a fetch that has not returned within this deadline
    /// fails with a timeout error (in milliseconds when serialized).
    ///
    /// Shutdown/teardown is governed separately by `shutdown_timeout` and is
    /// not counted against this deadline: an already-computed result is
    /// delivered to the caller without waiting for the browser process to
    /// exit.
    /// </summary>
    [JsonPropertyName("overall_timeout")]
    public ulong? OverallTimeout { get; init; } = null;

    /// <summary>
    /// How long to wait for the browser process to close and exit cleanly
    /// during teardown before the process is forcibly killed (in milliseconds
    /// when serialized).
    /// </summary>
    [JsonPropertyName("shutdown_timeout")]
    public ulong? ShutdownTimeout { get; init; } = null;

    /// <summary>
    /// Wait strategy after browser navigation.
    /// </summary>
    [JsonPropertyName("wait")]
    public BrowserWait Wait { get; init; } = BrowserWait.NetworkIdle;

    /// <summary>
    /// CSS selector to wait for when `wait` is `Selector`.
    /// </summary>
    [JsonPropertyName("wait_selector")]
    public string? WaitSelector { get; init; } = null;

    /// <summary>
    /// Extra time to wait after the wait condition is met.
    /// </summary>
    [JsonPropertyName("extra_wait")]
    public ulong? ExtraWait { get; init; } = null;

    /// <summary>
    /// Proxy for browser fetches. Overrides `CrawlConfig.proxy` when set.
    /// Native backend supports http/https only (no SOCKS5).
    /// </summary>
    [JsonPropertyName("proxy")]
    public ProxyConfig? Proxy { get; init; } = null;

    /// <summary>
    /// URL patterns to block before the network request fires. Supports `*`
    /// wildcards. Useful for skipping ads/analytics/large images. Honored by
    /// `BrowserBackend.Native`; chromiumoxide ignores this field today.
    /// </summary>
    [JsonPropertyName("block_url_patterns")]
    public List<string> BlockUrlPatterns { get; init; } = [];

    /// <summary>
    /// JavaScript snippet evaluated after navigation completes.
    ///
    /// Scraping captures the native backend result in `ScrapeResult.browser.eval_result`.
    /// Interactions run this script before page actions on both browser backends but do
    /// not include the script result in `InteractionResult`.
    /// </summary>
    [JsonPropertyName("eval_script")]
    public string? EvalScript { get; init; } = null;

    /// <summary>
    /// User-agent used when fetching robots.txt. Defaults to `BrowserConfig.user_agent`
    /// (or crawlberg's default) if unset. Native only.
    /// </summary>
    [JsonPropertyName("robots_user_agent")]
    public string? RobotsUserAgent { get; init; } = null;

    /// <summary>
    /// Capture the full network event stream into the result. Default false
    /// (only the document event is captured). Native only.
    /// </summary>
    [JsonPropertyName("capture_network_events")]
    public bool CaptureNetworkEvents { get; init; } = false;

    /// <summary>
    /// Enable session affinity: reuse chromiumoxide Pages for same-domain
    /// requests so cookies + fingerprint + solved challenges persist.
    /// Default: true. When false, each request gets a fresh Page.
    /// </summary>
    [JsonPropertyName("session_affinity")]
    public bool SessionAffinity { get; init; } = true;

    /// <summary>
    /// Chrome or Chromium executable to launch. When set, crawlberg launches only this
    /// binary, and a path that is missing or not executable is an error that names the
    /// path; crawlberg never falls back to a different Chrome. When unset, crawlberg uses
    /// the `CHROME` environment variable, then searches the machine for an installed Chrome,
    /// Chromium or Edge. Chromiumoxide backend only: ignored, with a warning, when `endpoint`
    /// is set, with the native backend, and by scrapes and crawls that use a shared browser pool.
    /// </summary>
    [JsonPropertyName("chrome_path")]
    public string? ChromePath { get; init; } = null;

    /// <summary>
    /// Extra Chrome command-line flags, each written as `--flag` or `--flag=value`, for example
    /// `--user-agent=...`. A flag here replaces a crawlberg default flag of the same name
    /// (`--lang=fr` replaces crawlberg's `--lang=en_US`). Rejected: an entry that does not
    /// start with `--`, a flag name with an uppercase letter (Chrome flag names are lowercase),
    /// a flag named twice, and `--headless`, `--remote-debugging-port` and `--user-data-dir`,
    /// which crawlberg sets itself to run Chrome. Set this only from trusted configuration,
    /// like `proxy`: flags such as `--proxy-server` and `--host-resolver-rules` send Chrome's
    /// traffic around the `ssrf` policy. Chromiumoxide backend only: ignored, with a warning,
    /// when `endpoint` is set, with the native backend, and by scrapes and crawls that use a
    /// shared browser pool.
    /// </summary>
    [JsonPropertyName("chrome_args")]
    public List<string> ChromeArgs { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="BrowserConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="CrawlbergException">When the JSON cannot be deserialised.</exception>
    public static BrowserConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<BrowserConfig>(json, JsonOptions)
                ?? throw new CrawlbergException($"Failed to parse BrowserConfig from JSON: deserializer returned null");
        }
        catch (CrawlbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new CrawlbergException($"Failed to parse BrowserConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    public static BrowserConfig Default()
    {
        var nativeResult = NativeMethods.BrowserConfigDefault();
        var jsonPtr = NativeMethods.BrowserConfigToJson(nativeResult);
        var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.BrowserConfigFree(nativeResult);
        return JsonSerializer.Deserialize<BrowserConfig>(json ?? "null", JsonOptions)!;
    }
}
