// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:033f5eca7fbc34bfd4671a4317e70b36ebfd9f5f5cf417b942c113c920a71e34
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// A connection error occurred.
/// </summary>
public class ConnectionException : CrawlErrorException {
  public ConnectionException(string message) : base(message) {}

  public ConnectionException(string message, Exception innerException)
      : base(message, innerException) {}
}
