// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9ff7a9b8c0bd359476d1c76a8c03769d326d18c4072e444ed4daf29f49ec2875
#nullable enable

using System;

namespace Crawlberg;

public class CrawlbergException : Exception {
  public int Code { get; }

  public CrawlbergException(int code, string message) : base(message) {
    Code = code;
  }

  public CrawlbergException(string message) : base(message) { Code = 0; }

  public CrawlbergException(string message, Exception innerException)
      : base(message, innerException) {
    Code = 0;
  }
}
