// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Crawlberg;

public static class CrawlbergConverter {
  private static readonly JsonSerializerOptions JsonOptions =
      new() { Converters = { new JsonStringEnumConverter(
                  JsonNamingPolicy.SnakeCaseLower) },
              DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

  private static readonly JsonSerializerOptions JsonSerializationOptions =
      new() { Converters = { new JsonStringEnumConverter(
                  JsonNamingPolicy.SnakeCaseLower) },
              DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull };

  /// <summary>
  /// Crawl multiple seed URLs concurrently, each following links to configured
  /// depth.
  /// </summary>
  /// <param name="engine"></param>
  /// <param name="urls"></param>
  public static async Task<BatchCrawlResults>
  BatchCrawlAsync(CrawlEngineHandle engine, List<string> urls) {
    ArgumentNullException.ThrowIfNull(engine);
    var urlsJson = JsonSerializer.Serialize(urls, JsonSerializationOptions);
    var urlsHandle =
        global::System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(
            urlsJson);
    try {
      return await Task.Run(() => {
        var nativeResult = NativeMethods.BatchCrawl(engine.Handle, urlsHandle);
        if (NativeMethods.LastErrorCode() != 0) {
          throw GetLastError();
        }
        var jsonPtr = NativeMethods.BatchCrawlResultsToJson(nativeResult);
        var json =
            global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.BatchCrawlResultsFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<BatchCrawlResults>(
            json ?? "null", JsonOptions)!;
        return returnValue;
      });
    } finally {
      if (urlsHandle != global::System.IntPtr.Zero)
        global::System.Runtime.InteropServices.Marshal.FreeCoTaskMem(
            urlsHandle);
    }
  }

  /// <summary>
  /// Scrape multiple URLs concurrently.
  /// </summary>
  /// <param name="engine"></param>
  /// <param name="urls"></param>
  public static async Task<BatchScrapeResults>
  BatchScrapeAsync(CrawlEngineHandle engine, List<string> urls) {
    ArgumentNullException.ThrowIfNull(engine);
    var urlsJson = JsonSerializer.Serialize(urls, JsonSerializationOptions);
    var urlsHandle =
        global::System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(
            urlsJson);
    try {
      return await Task.Run(() => {
        var nativeResult = NativeMethods.BatchScrape(engine.Handle, urlsHandle);
        if (NativeMethods.LastErrorCode() != 0) {
          throw GetLastError();
        }
        var jsonPtr = NativeMethods.BatchScrapeResultsToJson(nativeResult);
        var json =
            global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.BatchScrapeResultsFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<BatchScrapeResults>(
            json ?? "null", JsonOptions)!;
        return returnValue;
      });
    } finally {
      if (urlsHandle != global::System.IntPtr.Zero)
        global::System.Runtime.InteropServices.Marshal.FreeCoTaskMem(
            urlsHandle);
    }
  }

  /// <summary>
  /// Crawl a website starting from `url`, following links up to the configured
  /// depth.
  /// </summary>
  /// <param name="engine"></param>
  /// <param name="url"></param>
  public static async Task<CrawlResult> CrawlAsync(CrawlEngineHandle engine,
                                                   string url) {
    ArgumentNullException.ThrowIfNull(engine);
    ArgumentNullException.ThrowIfNull(url);
    return await Task.Run(() => {
      var nativeResult = NativeMethods.Crawl(engine.Handle, url);
      if (NativeMethods.LastErrorCode() != 0) {
        throw GetLastError();
      }
      var jsonPtr = NativeMethods.CrawlResultToJson(nativeResult);
      var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
          jsonPtr);
      NativeMethods.FreeString(jsonPtr);
      NativeMethods.CrawlResultFree(nativeResult);
      var returnValue =
          JsonSerializer.Deserialize<CrawlResult>(json ?? "null", JsonOptions)!;
      return returnValue;
    });
  }

  /// <summary>
  /// Create a new crawl engine with the given configuration.
  ///
  /// If `config` is `None`, uses `CrawlConfig.default()`.
  /// Returns an error if the configuration is invalid.
  /// </summary>
  /// <param name="config">Optional.</param>
  public static CrawlEngineHandle CreateEngine(CrawlConfig? config) {
    ulong configHandle;
    if (config == null) {
      configHandle = 0;
    } else {
      var configJson =
          JsonSerializer.Serialize(config, JsonSerializationOptions);
      configHandle = NativeMethods.CrawlConfigFromJson(configJson);
      if (configHandle == 0) {
        throw CrawlbergException.FromLastError("CrawlConfigFromJson failed");
      }
    }
    try {
      var nativeResult = NativeMethods.CreateEngine(configHandle);
      if (NativeMethods.LastErrorCode() != 0) {
        throw GetLastError();
      }
      var returnValue = new CrawlEngineHandle(nativeResult);
      return returnValue;
    } finally {
      if (configHandle != 0)
        NativeMethods.CrawlConfigFree(configHandle);
    }
  }

  /// <summary>
  /// Convert markdown links to numbered citations.
  ///
  /// `[Example](https://example.com)` becomes `Example[1]`
  /// with `[1]: https://example.com` in the reference list.
  /// Images `![alt](url)` are preserved unchanged.
  /// </summary>
  /// <param name="markdown"></param>
  public static CitationResult GenerateCitations(string markdown) {
    ArgumentNullException.ThrowIfNull(markdown);
    var nativeResult = NativeMethods.GenerateCitations(markdown);
    if (NativeMethods.LastErrorCode() != 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.CitationResultToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.CitationResultFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<CitationResult>(json ?? "null",
                                                                 JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Execute browser actions on a single page.
  /// </summary>
  /// <param name="engine"></param>
  /// <param name="url"></param>
  /// <param name="actions"></param>
  public static async Task<InteractionResult>
  InteractAsync(CrawlEngineHandle engine, string url,
                List<PageAction> actions) {
    ArgumentNullException.ThrowIfNull(engine);
    ArgumentNullException.ThrowIfNull(url);
    var actionsJson =
        JsonSerializer.Serialize(actions, JsonSerializationOptions);
    var actionsHandle =
        global::System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(
            actionsJson);
    try {
      return await Task.Run(() => {
        var nativeResult =
            NativeMethods.Interact(engine.Handle, url, actionsHandle);
        if (NativeMethods.LastErrorCode() != 0) {
          throw GetLastError();
        }
        var jsonPtr = NativeMethods.InteractionResultToJson(nativeResult);
        var json =
            global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.InteractionResultFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<InteractionResult>(
            json ?? "null", JsonOptions)!;
        return returnValue;
      });
    } finally {
      if (actionsHandle != global::System.IntPtr.Zero)
        global::System.Runtime.InteropServices.Marshal.FreeCoTaskMem(
            actionsHandle);
    }
  }

  /// <summary>
  /// Discover all pages on a website by following links and sitemaps.
  /// </summary>
  /// <param name="engine"></param>
  /// <param name="url"></param>
  public static async Task<MapResult> MapUrlsAsync(CrawlEngineHandle engine,
                                                   string url) {
    ArgumentNullException.ThrowIfNull(engine);
    ArgumentNullException.ThrowIfNull(url);
    return await Task.Run(() => {
      var nativeResult = NativeMethods.MapUrls(engine.Handle, url);
      if (NativeMethods.LastErrorCode() != 0) {
        throw GetLastError();
      }
      var jsonPtr = NativeMethods.MapResultToJson(nativeResult);
      var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
          jsonPtr);
      NativeMethods.FreeString(jsonPtr);
      NativeMethods.MapResultFree(nativeResult);
      var returnValue =
          JsonSerializer.Deserialize<MapResult>(json ?? "null", JsonOptions)!;
      return returnValue;
    });
  }

  /// <summary>
  /// Scrape a single URL, returning extracted page data.
  /// </summary>
  /// <param name="engine"></param>
  /// <param name="url"></param>
  public static async Task<ScrapeResult> ScrapeAsync(CrawlEngineHandle engine,
                                                     string url) {
    ArgumentNullException.ThrowIfNull(engine);
    ArgumentNullException.ThrowIfNull(url);
    return await Task.Run(() => {
      var nativeResult = NativeMethods.Scrape(engine.Handle, url);
      if (NativeMethods.LastErrorCode() != 0) {
        throw GetLastError();
      }
      var jsonPtr = NativeMethods.ScrapeResultToJson(nativeResult);
      var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
          jsonPtr);
      NativeMethods.FreeString(jsonPtr);
      NativeMethods.ScrapeResultFree(nativeResult);
      var returnValue = JsonSerializer.Deserialize<ScrapeResult>(json ?? "null",
                                                                 JsonOptions)!;
      return returnValue;
    });
  }

  /// <summary>
  /// Validate the configuration, returning an error if any values are invalid.
  /// </summary>
  public static void CrawlConfigValidate(ulong handle) {
    NativeMethods.CrawlConfigValidate(handle);
  }

  /// <summary>
  /// Returns the count of unique normalized URLs encountered during crawling.
  ///
  /// Computed from `pages` (not the deprecated `normalized_urls` field) so it
  /// is correct across every binding that reconstructs `CrawlResult` from
  /// `pages` alone. In streaming mode `pages` is empty, so this returns 0 on
  /// the opaque-handle (C/Go/C#/Zig/Dart) path where it previously counted
  /// streamed pages — a known, accepted cost of making the other ten binding
  /// families correct.
  /// </summary>
  public static ulong CrawlResultUniqueNormalizedUrls(ulong handle) {
    var nativeResult = NativeMethods.CrawlResultUniqueNormalizedUrls(handle);
    var returnValue = nativeResult;
    return returnValue;
  }

  /// <summary>
  /// Create a policy from environment variables.
  ///
  /// On native platforms, reads `CRAWLBERG_ALLOW_PRIVATE_NETWORK` — if set to
  /// "1" or "true" (case-insensitive), sets `deny_private = false`. Otherwise,
  /// defaults to `deny_private = true`.
  ///
  /// On wasm32 targets (browser/Node.js), environment variables are not
  /// accessible to the compiled module. Defaults to `deny_private = false`
  /// because:
  /// - Outbound requests in a browser go through the fetch API, which enforces
  /// its own network policies.
  /// - Rust-side SSRF checking is unenforceable and redundant in a wasm32
  /// context.
  /// - For testing and localhost access, the host's network sandbox is the
  /// enforcing boundary.
  ///
  /// **Node.js caveat:** `deny_private` (whatever its value) has no effect on
  /// hostname-based requests under `wasm32`. There is no DNS resolution on this
  /// target, so `validate_url` only ever checks a literal IP host; a domain
  /// name falls straight through to `Ok(())`. In a browser this is covered by
  /// same-origin/CORS. Node's `fetch` enforces no CORS, so a Node service
  /// embedding this wasm module can be driven to internal hosts by domain name
  /// even though `deny_private = true`. Do not rely on this policy to stop that
  /// in Node — enforce egress restrictions (network policy, firewall, proxy
  /// allowlist) outside the process.
  /// </summary>
  public static SsrfPolicy SsrfPolicyFromEnv() {
    var nativeResult = NativeMethods.SsrfPolicyFromEnv();
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.SsrfPolicyToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.SsrfPolicyFree(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<SsrfPolicy>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Stream a single-URL crawl, yielding [`CrawlEvent`]s as pages are
  /// processed.
  ///
  /// Returns an async stream that emits one event per crawled page, plus a
  /// terminal `Complete` event. On per-URL failure during the crawl, emits an
  /// `Error` event followed by `Complete`. The stream item type is wrapped in
  /// a `Result` to surface transport-level errors; today every emit is `Ok`.
  ///
  /// Language bindings expose this as the native streaming shape for each
  /// target. WASM does not expose native streaming wrappers.
  /// </summary>
  /// <param name="engine">Opaque handle to CrawlEngineHandle</param>
  /// <param name="req"></param>
  public static async IAsyncEnumerable<CrawlEvent>
  CrawlStreamAsync(CrawlEngineHandle engine, CrawlStreamRequest req) {
    await foreach (var item in engine.CrawlStreamAsync(req)) {
      yield return item;
    }
  }
  /// <summary>
  /// Stream a multi-URL crawl, yielding [`CrawlEvent`]s across all seeds.
  ///
  /// Returns an async stream that emits one event per crawled page across all
  /// seeds, plus terminal `Complete` and `Error` events as appropriate. The
  /// stream item type is wrapped in a `Result` to surface transport-level
  /// errors; today every emit is `Ok`.
  ///
  /// Language bindings expose this as the native streaming shape for each
  /// target. WASM does not expose native streaming wrappers.
  /// </summary>
  /// <param name="engine">Opaque handle to CrawlEngineHandle</param>
  /// <param name="req"></param>
  public static async IAsyncEnumerable<CrawlEvent>
  BatchCrawlStreamAsync(CrawlEngineHandle engine, BatchCrawlStreamRequest req) {
    await foreach (var item in engine.BatchCrawlStreamAsync(req)) {
      yield return item;
    }
  }
  public static async IAsyncEnumerable<CrawlEvent>
  CrawlStream(ulong engine, CrawlStreamRequest req) {
    var reqJson = JsonSerializer.Serialize(req, JsonSerializationOptions);
    var reqHandle = NativeMethods.CrawlStreamRequestFromJson(reqJson);
    var iterHandle =
        NativeMethods.CrawlEngineHandleCrawlStreamStart(engine, reqHandle);
    if (iterHandle == 0)
      throw GetLastError();
    try {
      while (true) {
        var itemHandle =
            NativeMethods.CrawlEngineHandleCrawlStreamNext(iterHandle);
        if (itemHandle == 0)
          break;
        try {
          var jsonPtr = NativeMethods.CrawlEventToJson(itemHandle);
          var json =
              global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                  jsonPtr);
          NativeMethods.FreeString(jsonPtr);
          if (!string.IsNullOrEmpty(json)) {
            var item =
                JsonSerializer.Deserialize<CrawlEvent>(json, JsonOptions)!;
            yield return item;
          }
        } finally {
          NativeMethods.CrawlEventFree(itemHandle);
        }
      }
    } finally {
      NativeMethods.CrawlEngineHandleCrawlStreamFree(iterHandle);
      NativeMethods.CrawlStreamRequestFree(reqHandle);
    }
  }
  public static async IAsyncEnumerable<CrawlEvent>
  BatchCrawlStream(ulong engine, BatchCrawlStreamRequest req) {
    var reqJson = JsonSerializer.Serialize(req, JsonSerializationOptions);
    var reqHandle = NativeMethods.BatchCrawlStreamRequestFromJson(reqJson);
    var iterHandle =
        NativeMethods.CrawlEngineHandleBatchCrawlStreamStart(engine, reqHandle);
    if (iterHandle == 0)
      throw GetLastError();
    try {
      while (true) {
        var itemHandle =
            NativeMethods.CrawlEngineHandleBatchCrawlStreamNext(iterHandle);
        if (itemHandle == 0)
          break;
        try {
          var jsonPtr = NativeMethods.CrawlEventToJson(itemHandle);
          var json =
              global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                  jsonPtr);
          NativeMethods.FreeString(jsonPtr);
          if (!string.IsNullOrEmpty(json)) {
            var item =
                JsonSerializer.Deserialize<CrawlEvent>(json, JsonOptions)!;
            yield return item;
          }
        } finally {
          NativeMethods.CrawlEventFree(itemHandle);
        }
      }
    } finally {
      NativeMethods.CrawlEngineHandleBatchCrawlStreamFree(iterHandle);
      NativeMethods.BatchCrawlStreamRequestFree(reqHandle);
    }
  }
  private static Exception GetLastError() {
    return CrawlbergException.FromLastError("Unknown error");
  }
}
