// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b0f739ca5c218fedacc5fcc337a79637e4cc185a52a9c061b5672353066ce07f
#nullable enable

using System;

namespace Crawlberg;

public class CrawlbergException : Exception {
  public int Code { get; }

  public CrawlbergException(int code, string message) : base(message) {
    Code = code;
  }

  public CrawlbergException(string message) : base(message) { Code = 0; }

  public CrawlbergException(string message, Exception innerException)
      : base(message, innerException) {
    Code = 0;
  }
}
