// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:202e8ed24ef6d677db84b2fbeadb661261bcfd124c9d4eb83345c7cf066a4566
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// Errors that can occur during crawling, scraping, or mapping operations.
/// </summary>
public class CrawlErrorException : CrawlbergException
{
    public CrawlErrorException(string message) : base(message) { }

    public CrawlErrorException(string message, Exception innerException) : base(message, innerException) { }
}
