// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1d700aa62f11b5359b4fe5de8d58ae48fe8d61fb39ecde8438b4f017655c3bf5
#nullable enable

using System;

namespace Crawlberg;

public class CrawlbergException : Exception
{
    public int Code { get; }

    public CrawlbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public CrawlbergException(string message) : base(message)
    {
        Code = 0;
    }

    public CrawlbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
