// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b576a02e42860a4a42ba6af3f97930868dca6c18258f9f7d92e44dbb15f94cb9
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Crawlberg;
/// <summary>
/// Traversal order for a crawl.
///
/// Selects both the queue discipline and the selection strategy, because global order is a
/// property of the frontier: the engine hands its bounded selection window to the strategy, so
/// a strategy alone can only reorder URLs that have already been dequeued.
/// </summary>
[JsonConverter(typeof(CrawlStrategyKindJsonConverter))]
public enum CrawlStrategyKind
{
    /// <summary>
    /// Breadth-first: a FIFO frontier visits every URL at one depth before the next.
    /// </summary>
    [JsonPropertyName("bfs")]
    Bfs,
    /// <summary>
    /// Depth-first: a LIFO frontier descends into a page's children before its siblings.
    /// </summary>
    [JsonPropertyName("dfs")]
    Dfs,
    /// <summary>
    /// Highest-priority-first within the selection window, scored by `CrawlStrategy.score_url`.
    /// </summary>
    [JsonPropertyName("best_first")]
    BestFirst,
    /// <summary>
    /// Like `BestFirst`, but stops once newly crawled pages stop contributing new terms.
    /// </summary>
    [JsonPropertyName("adaptive")]
    Adaptive,
}


/// <summary>
/// Custom JSON converter for <see cref="CrawlStrategyKind"/> that respects explicit variant names.
/// </summary>
internal sealed class CrawlStrategyKindJsonConverter : JsonConverter<CrawlStrategyKind>
{
    public override CrawlStrategyKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "bfs" => CrawlStrategyKind.Bfs,
            "dfs" => CrawlStrategyKind.Dfs,
            "best_first" => CrawlStrategyKind.BestFirst,
            "adaptive" => CrawlStrategyKind.Adaptive,
            _ => throw new JsonException($"Unknown CrawlStrategyKind value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, CrawlStrategyKind value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            CrawlStrategyKind.Bfs => "bfs",
            CrawlStrategyKind.Dfs => "dfs",
            CrawlStrategyKind.BestFirst => "best_first",
            CrawlStrategyKind.Adaptive => "adaptive",
            _ => throw new JsonException($"Unknown CrawlStrategyKind value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
