// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3a1917e5db668dfe5f72cf0122d3b3eec3fb0855563c85c74cfa0f0d11fc4ae5
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// Data was lost or truncated during transfer.
/// </summary>
public class DataLossException : CrawlErrorException {
  public DataLossException(string message) : base(message) {}

  public DataLossException(string message, Exception innerException)
      : base(message, innerException) {}
}
