// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9239f0c4a976848daf64796cbf08d6835862f17985c5f163c603390b305b904e
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// URL denied by SSRF policy: private IP, metadata IP, etc.
/// </summary>
public class DeniedByPolicyException : SsrfErrorException {
  public DeniedByPolicyException(string message) : base(message) {}

  public DeniedByPolicyException(string message, Exception innerException)
      : base(message, innerException) {}
}
