// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:383d495e960d1581f6322a944c6a06ba66916bc679618eb84acc9bab4ac968ca
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// URL denied by SSRF policy: private IP, metadata IP, etc.
/// </summary>
public class DeniedByPolicyException : SsrfErrorException {
  public DeniedByPolicyException(string message) : base(message) {}

  public DeniedByPolicyException(string message, Exception innerException)
      : base(message, innerException) {}
}
