// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3796df7d281ce46c6268202053527bc8f53d8c685d439a0215f6ba353ee6f8a4
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// URL scheme not in allowlist (e.g., `ftp://` when only `http`/`https` allowed).
/// </summary>
public class DisallowedSchemeException : SsrfErrorException
{
    public DisallowedSchemeException(string message) : base(message) { }

    public DisallowedSchemeException(string message, Exception innerException) : base(message, innerException) { }
}
