// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0bad31cd2a645ac05bbcdcde5415acdd5d8f9669d1f59b7bf71a33558fbf2694
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// URL scheme not in allowlist (e.g., `ftp://` when only `http`/`https` allowed).
/// </summary>
public class DisallowedSchemeException : SsrfErrorException
{
    public DisallowedSchemeException(string message) : base(message) { }

    public DisallowedSchemeException(string message, Exception innerException) : base(message, innerException) { }
}
