// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ae067408edb725c54b3afe11bb9c1800a4e05fd59d46925c4e43ef954b31d873
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// A DNS resolution error occurred.
/// </summary>
public class DnsException : CrawlErrorException
{
    public DnsException(string message) : base(message) { }

    public DnsException(string message, Exception innerException) : base(message, innerException) { }
}
