// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:594c3ea00ade8844fe2e68f827df0ed24a8ca3b3fff2c299c616395fc539b849
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// DNS resolution failed for hostname.
/// </summary>
public class DnsResolutionFailedException : SsrfErrorException {
  public DnsResolutionFailedException(string message) : base(message) {}

  public DnsResolutionFailedException(string message, Exception innerException)
      : base(message, innerException) {}
}
