// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d5e3bea96c4ac3fa331838550b170f8c0f2ed1d0cecb7d674a3da24b3176d05a
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Crawlberg;
/// <summary>
/// Opt-in encoding applied to a downloaded document's bytes for callers who need the
/// content available in a serializable field rather than reading it from disk.
///
/// `None` (the `CrawlConfig.document_content_encoding` default) produces neither — unlike
/// screenshots, base64-encoding a document by default would duplicate an already
/// up-to-`document_max_size` buffer (50 MB default) in memory per document.
/// </summary>
[JsonConverter(typeof(DocumentContentEncodingJsonConverter))]
public enum DocumentContentEncoding
{
    /// <summary>
    /// Populate `DownloadedDocument.content_base64` with a base64-encoded copy.
    /// </summary>
    [JsonPropertyName("base64")]
    Base64,
}


/// <summary>
/// Custom JSON converter for <see cref="DocumentContentEncoding"/> that respects explicit variant names.
/// </summary>
internal sealed class DocumentContentEncodingJsonConverter : JsonConverter<DocumentContentEncoding>
{
    public override DocumentContentEncoding Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "base64" => DocumentContentEncoding.Base64,
            _ => throw new JsonException($"Unknown DocumentContentEncoding value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, DocumentContentEncoding value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            DocumentContentEncoding.Base64 => "base64",
            _ => throw new JsonException($"Unknown DocumentContentEncoding value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
