// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8b8b27fbd841e5e6a60b6a57c653fce6635a0ab68338d19b206af2d050e103f7
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The request was forbidden (HTTP 403).
/// </summary>
public class ForbiddenException : CrawlErrorException {
  public ForbiddenException(string message) : base(message) {}

  public ForbiddenException(string message, Exception innerException)
      : base(message, innerException) {}
}
