// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cdbae0086c67643786b266fd1c768660afa6de82c185f674be4261952fa22d6e
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The request was forbidden (HTTP 403).
/// </summary>
public class ForbiddenException : CrawlErrorException
{
    public ForbiddenException(string message) : base(message) { }

    public ForbiddenException(string message, Exception innerException) : base(message, innerException) { }
}
