// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:969e8ca908a9f8e0dee81ed5b32109eb37586dcc5cf16d908c7c5fac4eefd332
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Crawlberg;

/// <summary>
/// A heading element extracted from the page.
/// </summary>
public sealed record HeadingInfo {
  /// <summary>
  /// The heading level (1-6).
  /// </summary>
  [JsonPropertyName("level")]
  public byte Level { get; init; } = 0;

  /// <summary>
  /// The heading text content.
  /// </summary>
  [JsonPropertyName("text")]
  public string Text {
    get; init;
  } = "";

  /// <summary>
  /// Parse a <see cref="HeadingInfo"/> from a JSON string.
  /// </summary>
  /// <exception cref="CrawlbergException">When the JSON cannot be
  /// deserialised.</exception>
  public static HeadingInfo FromJson(string json) {
    try {
      return JsonSerializer.Deserialize<HeadingInfo>(json, JsonOptions) ??
             throw new CrawlbergException(
                 $"Failed to parse HeadingInfo from JSON: deserializer returned null");
    } catch (CrawlbergException) {
      throw;
    } catch (Exception e) {
      throw new CrawlbergException(
          $"Failed to parse HeadingInfo from JSON: {e.Message}", e);
    }
  }

  private static readonly JsonSerializerOptions JsonOptions = new() {
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower),
                   new ByteArrayJsonConverter() },
  };

  /// <summary>Options for serializing config/input objects to FFI. Strips nulls
  /// (nullable C# fields default to null and would override required Rust
  /// fields with non-deserialisable nulls) but preserves explicit false/0 so
  /// caller intent is kept.</summary>
  private static readonly JsonSerializerOptions JsonSerializationOptions =
      new() {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(
                           JsonNamingPolicy.SnakeCaseLower),
                       new ByteArrayJsonConverter() },
      };
}
