// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7c011ee5688979448c85a639a24835fac91faabe56dd33eb0e8239833a035980
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// Invalid URL format.
/// </summary>
public class InvalidUrlException : SsrfErrorException {
  public InvalidUrlException(string message) : base(message) {}

  public InvalidUrlException(string message, Exception innerException)
      : base(message, innerException) {}
}
