// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ed6753aa35e27ad4764a749b35d849473835fb530fcba666ac607635b1333c06
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// Invalid URL format.
/// </summary>
public class InvalidUrlException : SsrfErrorException
{
    public InvalidUrlException(string message) : base(message) { }

    public InvalidUrlException(string message, Exception innerException) : base(message, innerException) { }
}
