// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b2fae67943d039bd091a4326b188cba2789ad15200bbba85ef0f093953a53646
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The provided configuration is invalid.
/// </summary>
public class InvalidConfigException : CrawlErrorException
{
    public InvalidConfigException(string message) : base(message) { }

    public InvalidConfigException(string message, Exception innerException) : base(message, innerException) { }
}
