// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a9f8bca9f6f574b0494fad24bcf9f8fdde78d109ef31d94ccc8f80854020dea4
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The provided configuration is invalid.
/// </summary>
public class InvalidConfigException : CrawlErrorException
{
    public InvalidConfigException(string message) : base(message) { }

    public InvalidConfigException(string message, Exception innerException) : base(message, innerException) { }
}
