// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ed6753aa35e27ad4764a749b35d849473835fb530fcba666ac607635b1333c06
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The provided configuration is invalid.
/// </summary>
public class InvalidConfigException : CrawlErrorException
{
    public InvalidConfigException(string message) : base(message) { }

    public InvalidConfigException(string message, Exception innerException) : base(message, innerException) { }
}
