// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:899a9b0b3964b8cc10628ac686b74140e934aa910533d6b9333c2acf97f2773b
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// Invalid URL format.
/// </summary>
public class InvalidUrlException : SsrfErrorException {
  public InvalidUrlException(string message) : base(message) {}

  public InvalidUrlException(string message, Exception innerException)
      : base(message, innerException) {}
}
