// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6df749047d02a830f8fbd4d001e412764ab811ace96a1b1c378dec71e733a354
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The requested page was not found (HTTP 404).
/// </summary>
public class NotFoundException : CrawlErrorException {
  public NotFoundException(string message) : base(message) {}

  public NotFoundException(string message, Exception innerException)
      : base(message, innerException) {}
}
