// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:969e8ca908a9f8e0dee81ed5b32109eb37586dcc5cf16d908c7c5fac4eefd332
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The requested page was not found (HTTP 404).
/// </summary>
public class NotFoundException : CrawlErrorException {
  public NotFoundException(string message) : base(message) {}

  public NotFoundException(string message, Exception innerException)
      : base(message, innerException) {}
}
