// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:45dd8af390f23c38aefeddb1f198557357dff97d5a7c3b8a88640cc548716979
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// Host not on allowlist when an allowlist is configured.
/// </summary>
public class NotOnAllowlistException : SsrfErrorException {
  public NotOnAllowlistException(string message) : base(message) {}

  public NotOnAllowlistException(string message, Exception innerException)
      : base(message, innerException) {}
}
