// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:aa1b0dac6ad5a08ba59165e745791f33f857a9c6a5d67b2f2e5534e15cf52958
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// Host not on allowlist when an allowlist is configured.
/// </summary>
public class NotOnAllowlistException : SsrfErrorException
{
    public NotOnAllowlistException(string message) : base(message) { }

    public NotOnAllowlistException(string message, Exception innerException) : base(message, innerException) { }
}
