// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0a47c6602ddbf0857bef848d1ff0fb7f52878eb4a95d2e6e3421c6addb047ffc
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// Host not on allowlist when an allowlist is configured.
/// </summary>
public class NotOnAllowlistException : SsrfErrorException {
  public NotOnAllowlistException(string message) : base(message) {}

  public NotOnAllowlistException(string message, Exception innerException)
      : base(message, innerException) {}
}
