// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9734598091b20b568807c27946360e78323036ccf66861dc98a52d1bce70f361
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// An unclassified error occurred.
/// </summary>
public class OtherException : CrawlErrorException {
  public OtherException(string message) : base(message) {}

  public OtherException(string message, Exception innerException)
      : base(message, innerException) {}
}
