// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cc5fc94c108bb9f977a57f5e3f8b8af61509305ba43cb747a643f02ace5dc941
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// An unclassified error occurred.
/// </summary>
public class OtherException : CrawlErrorException {
  public OtherException(string message) : base(message) {}

  public OtherException(string message, Exception innerException)
      : base(message, innerException) {}
}
