// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0bad31cd2a645ac05bbcdcde5415acdd5d8f9669d1f59b7bf71a33558fbf2694
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The request was rate-limited (HTTP 429).
/// </summary>
public class RateLimitedException : CrawlErrorException
{
    public RateLimitedException(string message) : base(message) { }

    public RateLimitedException(string message, Exception innerException) : base(message, innerException) { }
}
