// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:928639b574d5fca9c5b51f86fe815c5bc0779c92416dbaa12f74160457caaf3a
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The request was rate-limited (HTTP 429).
/// </summary>
public class RateLimitedException : CrawlErrorException {
  public RateLimitedException(string message) : base(message) {}

  public RateLimitedException(string message, Exception innerException)
      : base(message, innerException) {}
}
