// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:220f5f6df041dfa9e6ccdaa492fe328856d39e9f10894e431cd915a696d6bc34
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The request was rate-limited (HTTP 429).
/// </summary>
public class RateLimitedException : CrawlErrorException
{
    public RateLimitedException(string message) : base(message) { }

    public RateLimitedException(string message, Exception innerException) : base(message, innerException) { }
}
