// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3a1917e5db668dfe5f72cf0122d3b3eec3fb0855563c85c74cfa0f0d11fc4ae5
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Crawlberg;
/// <summary>
/// Direction for a scroll action.
/// </summary>
[JsonConverter(typeof(ScrollDirectionJsonConverter))]
public enum ScrollDirection {
  /// <summary>
  /// Scroll upward.
  /// </summary>
  [JsonPropertyName("up")] Up,
  /// <summary>
  /// Scroll downward.
  /// </summary>
  [JsonPropertyName("down")] Down,
}

/// <summary>
/// Custom JSON converter for <see cref="ScrollDirection"/> that respects
/// explicit variant names.
/// </summary>
internal sealed class ScrollDirectionJsonConverter
    : JsonConverter<ScrollDirection> {
  public override ScrollDirection Read(ref Utf8JsonReader reader,
                                       Type typeToConvert,
                                       JsonSerializerOptions options) {
    var value = reader.GetString();
    return value switch {
      "up" => ScrollDirection.Up, "down" => ScrollDirection.Down,
      _ => throw new JsonException($"Unknown ScrollDirection value: {value}")
    };
  }

  public override void Write(Utf8JsonWriter writer, ScrollDirection value,
                             JsonSerializerOptions options) {
    var str = value switch {
      ScrollDirection.Up => "up", ScrollDirection.Down => "down",
      _ => throw new JsonException($"Unknown ScrollDirection value: {value}")
    };
    writer.WriteStringValue(str);
  }
}
