// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:28804898e5c30c619c6fe36c02750b178c829ea1c320345e879de29db150e812
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// A server error occurred (HTTP 5xx).
/// </summary>
public class ServerErrorException : CrawlErrorException
{
    public ServerErrorException(string message) : base(message) { }

    public ServerErrorException(string message, Exception innerException) : base(message, innerException) { }
}
