// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2d1771464a54ef9e955689dddc390c987a350c27d30211d13a8affb6432cb068
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// An SSL/TLS error occurred.
/// </summary>
public class SslException : CrawlErrorException
{
    public SslException(string message) : base(message) { }

    public SslException(string message, Exception innerException) : base(message, innerException) { }
}
