// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2a2452ab1adc6aeed23acc4b2fff220f7632b6c32eca6de793599f89a7963f5a
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// An SSL/TLS error occurred.
/// </summary>
public class SslException : CrawlErrorException {
  public SslException(string message) : base(message) {}

  public SslException(string message, Exception innerException)
      : base(message, innerException) {}
}
