// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b25f293a2658b5e49df9ae7ecbdcfd96c13ada26ecf2a046c108673ffc47752a
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// A URL was rejected by SSRF policy (private IP, metadata, disallowed scheme,
/// etc).
/// </summary>
public class SsrfPolicyViolationException : CrawlErrorException {
  public SsrfPolicyViolationException(string message) : base(message) {}

  public SsrfPolicyViolationException(string message, Exception innerException)
      : base(message, innerException) {}
}
