// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e033f002c82742956f74aec95922d214ad649750746e01669e1d4be5662dde1b
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// A URL was rejected by SSRF policy (private IP, metadata, disallowed scheme,
/// etc).
/// </summary>
public class SsrfPolicyViolationException : CrawlErrorException {
  public SsrfPolicyViolationException(string message) : base(message) {}

  public SsrfPolicyViolationException(string message, Exception innerException)
      : base(message, innerException) {}
}
