// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:033f5eca7fbc34bfd4671a4317e70b36ebfd9f5f5cf417b942c113c920a71e34
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// SSRF validation error.
/// </summary>
public class SsrfErrorException : CrawlbergException {
  public SsrfErrorException(string message) : base(message) {}

  public SsrfErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
