// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e0600612767fdd3d51e9128afdb0ffcd1fb490e9942f3839a5120ab7a4e3b658
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// A URL was rejected by SSRF policy (private IP, metadata, disallowed scheme, etc).
/// </summary>
public class SsrfPolicyViolationException : CrawlErrorException
{
    public SsrfPolicyViolationException(string message) : base(message) { }

    public SsrfPolicyViolationException(string message, Exception innerException) : base(message, innerException) { }
}
