// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:477098a9fbc712ce8a01a56095b711cd4a8076520ef7f0c1461288ca5fe66ead
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The request timed out.
/// </summary>
public class TimeoutException : CrawlErrorException {
  public TimeoutException(string message) : base(message) {}

  public TimeoutException(string message, Exception innerException)
      : base(message, innerException) {}
}
