// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:16ea86305c4558bd2c83814817603b55b2297f1c8dcb55e3f00dac8400a58cb2
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The request timed out.
/// </summary>
public class TimeoutException : CrawlErrorException {
  public TimeoutException(string message) : base(message) {}

  public TimeoutException(string message, Exception innerException)
      : base(message, innerException) {}
}
