// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0ce4d753fdb4854e44358639dcbaebee3449a4afa142dbc4f0a72aa72c214648
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// Too many HTTP redirects encountered during validation.
/// </summary>
public class TooManyRedirectsException : SsrfErrorException {
  public TooManyRedirectsException(string message) : base(message) {}

  public TooManyRedirectsException(string message, Exception innerException)
      : base(message, innerException) {}
}
