// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e0600612767fdd3d51e9128afdb0ffcd1fb490e9942f3839a5120ab7a4e3b658
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// Too many HTTP redirects encountered during validation.
/// </summary>
public class TooManyRedirectsException : SsrfErrorException
{
    public TooManyRedirectsException(string message) : base(message) { }

    public TooManyRedirectsException(string message, Exception innerException) : base(message, innerException) { }
}
