// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3796df7d281ce46c6268202053527bc8f53d8c685d439a0215f6ba353ee6f8a4
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The requested capability is not supported by the active backend or build.
/// </summary>
public class UnsupportedException : CrawlErrorException
{
    public UnsupportedException(string message) : base(message) { }

    public UnsupportedException(string message, Exception innerException) : base(message, innerException) { }
}
