// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:594c3ea00ade8844fe2e68f827df0ed24a8ca3b3fff2c299c616395fc539b849
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The requested capability is not supported by the active backend or build.
/// </summary>
public class UnsupportedException : CrawlErrorException {
  public UnsupportedException(string message) : base(message) {}

  public UnsupportedException(string message, Exception innerException)
      : base(message, innerException) {}
}
