// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d838def23655685fa0251d979d53fb8e4eeb183ac5f64f11ebc9773093521cd2
#nullable enable

using System;

namespace Crawlberg;

/// <summary>
/// The requested capability is not supported by the active backend or build.
/// </summary>
public class UnsupportedException : CrawlErrorException
{
    public UnsupportedException(string message) : base(message) { }

    public UnsupportedException(string message, Exception innerException) : base(message, innerException) { }
}
