# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:890cf4411caea729c1f4232d4847d8745215608d88826d2170e7abed65ac74cb
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Crawlberg.AuthConfig do
  @moduledoc "Authentication configuration."

  @typedoc "Authentication configuration."
  @type t :: term()

  @typedoc "HTTP Basic authentication."
  @type basic :: %{type: :basic, username: String.t(), password: String.t()}
  @typedoc "Bearer token authentication."
  @type bearer :: %{type: :bearer, token: String.t()}
  @typedoc "Custom authentication header."
  @type header :: %{type: :header, name: String.t(), value: String.t()}

  def basic(username, password), do: {:basic, %{username: username, password: password}}
  def bearer(token), do: {:bearer, %{token: token}}
  def header(name, value), do: {:header, %{name: name, value: value}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:basic), do: "basic"
  def wire_value(:bearer), do: "bearer"
  def wire_value(:header), do: "header"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
