# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e0600612767fdd3d51e9128afdb0ffcd1fb490e9942f3839a5120ab7a4e3b658
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.BrowserExtras do
  @moduledoc """
  Browser-specific extras populated when the native browser backend was used.

  Available on `ScrapeResult.browser` when `BrowserBackend::Native` handled the request.
  """

  @typedoc "Browser-specific extras populated when the native browser backend was used."
  @type t :: %__MODULE__{
  eval_result: String.t() | nil,
  network_events: [Crawlberg.ResponseMeta.t()],
  cookies: [Crawlberg.CookieInfo.t()]
  }

  defstruct eval_result: nil,
  network_events: [],
  cookies: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
