# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f961bdffd684028364e993c81e04f2a8bbd23d7a9b92c5d5999f843d8f95bca
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Crawlberg.BrowserExtras do
  @moduledoc """
  Browser-specific extras populated when the native browser backend was used.

  Available on `ScrapeResult.browser` when `BrowserBackend::Native` handled the request.
  """

  @typedoc "Browser-specific extras populated when the native browser backend was used."
  @type t :: %__MODULE__{
          eval_result: String.t() | nil,
          network_events: [Crawlberg.ResponseMeta.t()],
          cookies: [Crawlberg.CookieInfo.t()]
        }

  defstruct eval_result: nil,
            network_events: [],
            cookies: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
