# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ca771d8bd7e590d63e16df7e27c98aaad46ab1ac4977f95a064925f34a014a6d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Crawlberg.BrowserConfig do
  @moduledoc "Browser fallback configuration."

  @typedoc "Browser fallback configuration."
  @type t :: %__MODULE__{
          mode: Crawlberg.BrowserMode.t(),
          backend: Crawlberg.BrowserBackend.t(),
          endpoint: String.t() | nil,
          timeout: non_neg_integer(),
          wait: Crawlberg.BrowserWait.t(),
          wait_selector: String.t() | nil,
          extra_wait: non_neg_integer() | nil,
          proxy: Crawlberg.ProxyConfig.t() | nil,
          block_url_patterns: [String.t()],
          eval_script: String.t() | nil,
          robots_user_agent: String.t() | nil,
          capture_network_events: boolean(),
          session_affinity: boolean()
        }

  defstruct mode: :auto,
            backend: :chromiumoxide,
            endpoint: nil,
            timeout: 30_000,
            wait: :network_idle,
            wait_selector: nil,
            extra_wait: nil,
            proxy: nil,
            block_url_patterns: [],
            eval_script: nil,
            robots_user_agent: nil,
            capture_network_events: false,
            session_affinity: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
