# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3796df7d281ce46c6268202053527bc8f53d8c685d439a0215f6ba353ee6f8a4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.CookieInfo do
  @moduledoc "Information about an HTTP cookie received from a response."

  @typedoc "Information about an HTTP cookie received from a response."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  value: String.t() | nil,
  domain: String.t() | nil,
  path: String.t() | nil
  }

  defstruct name: nil,
  value: nil,
  domain: nil,
  path: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
