# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:894efc463f05524721400ad91978e7482ccfe79a5f1b8d633c5992d68c18cec8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Crawlberg.CookieInfo do
  @moduledoc "Information about an HTTP cookie received from a response."

  @typedoc "Information about an HTTP cookie received from a response."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          value: String.t() | nil,
          domain: String.t() | nil,
          path: String.t() | nil
        }

  defstruct name: nil,
            value: nil,
            domain: nil,
            path: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
