# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:033f5eca7fbc34bfd4671a4317e70b36ebfd9f5f5cf417b942c113c920a71e34
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.CrawlEngineHandle do
  @moduledoc """
  Opaque handle to a configured crawl engine.

  Constructed via [`create_engine`] with an optional [`CrawlConfig`].
  Default implementations for all pluggable components are used internally.
  """

  alias Crawlberg.Native
  defstruct [:ref]

  @typedoc "Opaque handle to a configured crawl engine."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Stream a single-URL crawl, yielding [`CrawlEvent`]s as pages are processed."
  def crawl_stream(obj, req) do
    case Native.crawlenginehandle_crawl_stream_start(obj.ref, req) do
      {:ok, handle} ->
      stream =
      Stream.unfold(handle, fn h ->
        case Native.crawlenginehandle_crawl_stream_next(h) do
          {:ok, nil} ->
          nil

          {:ok, chunk_json} when is_binary(chunk_json) ->
          {Jason.decode!(chunk_json, keys: :atoms), h}

          {:ok, chunk} ->
          {chunk, h}

          {:error, _} ->
          nil
        end
      end)

      {:ok, stream}

      {:error, reason} ->
      {:error, reason}
    end
  end

  @doc "Stream a multi-URL crawl, yielding [`CrawlEvent`]s across all seeds."
  def batch_crawl_stream(obj, req) do
    case Native.crawlenginehandle_batch_crawl_stream_start(obj.ref, req) do
      {:ok, handle} ->
      stream =
      Stream.unfold(handle, fn h ->
        case Native.crawlenginehandle_batch_crawl_stream_next(h) do
          {:ok, nil} ->
          nil

          {:ok, chunk_json} when is_binary(chunk_json) ->
          {Jason.decode!(chunk_json, keys: :atoms), h}

          {:ok, chunk} ->
          {chunk, h}

          {:error, _} ->
          nil
        end
      end)

      {:ok, stream}

      {:error, reason} ->
      {:error, reason}
    end
  end
end
