# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2f8a8523cfc67b4ef9ccc7e198cc2ecda9f5188697349be7b0fed6be94da3f36
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Crawlberg.DocumentContentEncoding do
  @moduledoc """
  Opt-in encoding applied to a downloaded document's bytes for callers who need the
  content available in a serializable field rather than reading it from disk.

  `None` (the `CrawlConfig.document_content_encoding` default) produces neither — unlike
  screenshots, base64-encoding a document by default would duplicate an already
  up-to-`document_max_size` buffer (50 MB default) in memory per document.
  """

  @typedoc "Opt-in encoding applied to a downloaded document's bytes for callers who need the content available in a serializable field rather than reading it from disk."
  @type t :: :base64

  @base64 :base64

  @doc "Populate `DownloadedDocument.content_base64` with a base64-encoded copy."
  @spec base64() :: t()
  def base64, do: @base64

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:base64), do: "base64"
end
