# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e0600612767fdd3d51e9128afdb0ffcd1fb490e9942f3839a5120ab7a4e3b658
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.DownloadedAsset do
  @moduledoc "A downloaded asset from a page."

  @typedoc "A downloaded asset from a page."
  @type t :: %__MODULE__{
  url: String.t() | nil,
  content_hash: String.t() | nil,
  mime_type: String.t() | nil,
  size: non_neg_integer(),
  asset_category: String.t() | nil,
  html_tag: String.t() | nil
  }

  defstruct url: nil,
  content_hash: nil,
  mime_type: nil,
  size: 0,
  asset_category: :image,
  html_tag: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
