# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cc5fc94c108bb9f977a57f5e3f8b8af61509305ba43cb747a643f02ace5dc941
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.FaviconInfo do
  @moduledoc "Information about a favicon or icon link."

  @typedoc "Information about a favicon or icon link."
  @type t :: %__MODULE__{
  url: String.t() | nil,
  rel: String.t() | nil,
  sizes: String.t() | nil,
  mime_type: String.t() | nil
  }

  defstruct url: nil,
  rel: nil,
  sizes: nil,
  mime_type: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
