# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:033f5eca7fbc34bfd4671a4317e70b36ebfd9f5f5cf417b942c113c920a71e34
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.FeedType do
  @moduledoc "The type of a feed (RSS, Atom, or JSON Feed)."

  @typedoc "The type of a feed (RSS, Atom, or JSON Feed)."
  @type t :: :rss | :atom | :json_feed

  @rss :rss
  @atom :atom
  @json_feed :json_feed

  @doc "RSS feed."
  @spec rss() :: t()
  def rss, do: @rss
  @doc "Atom feed."
  @spec atom() :: t()
  def atom, do: @atom
  @doc "JSON Feed."
  @spec json_feed() :: t()
  def json_feed, do: @json_feed
end
