# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fe445c974733c703099671c7022b34ef9df4b85f8fee3260e7ec4150907af3b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.FeedType do
  @moduledoc "The type of a feed (RSS, Atom, or JSON Feed)."

  @typedoc "The type of a feed (RSS, Atom, or JSON Feed)."
  @type t :: :rss | :atom | :json_feed

  @rss :rss
  @atom :atom
  @json_feed :json_feed

  @doc "RSS feed."
  @spec rss() :: t()
  def rss, do: @rss
  @doc "Atom feed."
  @spec atom() :: t()
  def atom, do: @atom
  @doc "JSON Feed."
  @spec json_feed() :: t()
  def json_feed, do: @json_feed
end
