# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8453fdd07d2c7bc1834764e9d5fd3b62193b5d7efaf8cb500435f8e44fe589d4
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Crawlberg.FeedInfo do
  @moduledoc "Information about a feed link found on a page."

  @typedoc "Information about a feed link found on a page."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          title: String.t() | nil,
          feed_type: Crawlberg.FeedType.t()
        }

  defstruct url: nil,
            title: nil,
            feed_type: :rss

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
