# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:75130b11765cbed0a1ea2b5bcffe59620c4045cee1c7cece391c5e3fa47b10e0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.HeadingInfo do
  @moduledoc "A heading element extracted from the page."

  @typedoc "A heading element extracted from the page."
  @type t :: %__MODULE__{
  level: non_neg_integer(),
  text: String.t() | nil
  }

  defstruct level: 0,
  text: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
