# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31a90f762f54d9bb13b0f2e22048eb8e7ff59fe9227f284a75c2f1783113f062
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Crawlberg.HeadingInfo do
  @moduledoc "A heading element extracted from the page."

  @typedoc "A heading element extracted from the page."
  @type t :: %__MODULE__{
          level: non_neg_integer(),
          text: String.t() | nil
        }

  defstruct level: 0,
            text: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
