# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fe445c974733c703099671c7022b34ef9df4b85f8fee3260e7ec4150907af3b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.HreflangEntry do
  @moduledoc "An hreflang alternate link entry."

  @typedoc "An hreflang alternate link entry."
  @type t :: %__MODULE__{
          lang: String.t() | nil,
          url: String.t() | nil
        }

  defstruct lang: nil,
            url: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
