# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:969e8ca908a9f8e0dee81ed5b32109eb37586dcc5cf16d908c7c5fac4eefd332
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.ImageInfo do
  @moduledoc "Information about an image found on a page."

  @typedoc "Information about an image found on a page."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          alt: String.t() | nil,
          width: non_neg_integer() | nil,
          height: non_neg_integer() | nil,
          source: String.t() | nil
        }

  defstruct url: nil,
            alt: nil,
            width: nil,
            height: nil,
            source: :img

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
