# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ea143ac7420ef5f2c7706944368a99e0f7655efce268bf208ccdb4392cce449
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.ImageSource do
  @moduledoc "The source of an image reference."

  @typedoc "The source of an image reference."
  @type t :: :img | :picture_source | :"og:image" | :"twitter:image"

  @img :img
  @picture_source :picture_source
  @og_image :"og:image"
  @twitter_image :"twitter:image"

  @doc "An `<img>` tag."
  @spec img() :: t()
  def img, do: @img
  @doc "A `<source>` tag inside `<picture>`."
  @spec picture_source() :: t()
  def picture_source, do: @picture_source
  @doc "An `og:image` meta tag."
  @spec og_image() :: t()
  def og_image, do: @og_image
  @doc "A `twitter:image` meta tag."
  @spec twitter_image() :: t()
  def twitter_image, do: @twitter_image
end
