# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eece6d4e1d5810b45cc1c04fd609ffb5b18622d9b069c6dfa76d0bbffbc9f96c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.LinkInfo do
  @moduledoc "Information about a link found on a page."

  @typedoc "Information about a link found on a page."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          text: String.t() | nil,
          link_type: String.t() | nil,
          rel: String.t() | nil,
          nofollow: boolean()
        }

  defstruct url: nil,
            text: nil,
            link_type: :internal,
            rel: nil,
            nofollow: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
