# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:17f9f8de28107eff953439f136be0939f7d878b9c0bfeba5966d724bf5eb3056
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.ProxyConfig do
  @moduledoc "Proxy configuration for HTTP requests."

  @typedoc "Proxy configuration for HTTP requests."
  @type t :: %__MODULE__{
  url: String.t() | nil,
  username: String.t() | nil,
  password: String.t() | nil
  }

  defstruct url: nil,
  username: nil,
  password: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
