# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3796df7d281ce46c6268202053527bc8f53d8c685d439a0215f6ba353ee6f8a4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.ScrollDirection do
  @moduledoc "Direction for a scroll action."

  @typedoc "Direction for a scroll action."
  @type t :: :up | :down

  @up :up
  @down :down

  @doc "Scroll upward."
  @spec up() :: t()
  def up, do: @up
  @doc "Scroll downward."
  @spec down() :: t()
  def down, do: @down
end
