# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bef55d0fe3bec2cfa1f7674a824b620a4f93eb1ab5475627f20db419d245a3e5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.ScrollDirection do
  @moduledoc "Direction for a scroll action."

  @typedoc "Direction for a scroll action."
  @type t :: :up | :down

  @up :up
  @down :down

  @doc "Scroll upward."
  @spec up() :: t()
  def up, do: @up
  @doc "Scroll downward."
  @spec down() :: t()
  def down, do: @down
end
