# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:17f9f8de28107eff953439f136be0939f7d878b9c0bfeba5966d724bf5eb3056
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.ScrollDirection do
  @moduledoc "Direction for a scroll action."

  @typedoc "Direction for a scroll action."
  @type t :: :up | :down

  @up :up
  @down :down

  @doc "Scroll upward."
  @spec up() :: t()
  def up, do: @up
  @doc "Scroll downward."
  @spec down() :: t()
  def down, do: @down
end
