# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:495dedc1a12a77710a880dd65741be866b67ab4db2f2026df3e8591ba7fc9a69
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.SitemapUrl do
  @moduledoc "A URL entry from a sitemap."

  @typedoc "A URL entry from a sitemap."
  @type t :: %__MODULE__{
  url: String.t() | nil,
  lastmod: String.t() | nil,
  changefreq: String.t() | nil,
  priority: String.t() | nil
  }

  defstruct url: nil,
  lastmod: nil,
  changefreq: nil,
  priority: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
