# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b25f293a2658b5e49df9ae7ecbdcfd96c13ada26ecf2a046c108673ffc47752a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Crawlberg.SsrfPolicy do
  @moduledoc "SSRF policy configuration."

  @typedoc "SSRF policy configuration."
  @type t :: %__MODULE__{
          deny_private: boolean(),
          allowlist: [Crawlberg.HostMatcher.t()],
          max_redirects: non_neg_integer()
        }

  defstruct deny_private: true,
            allowlist: [],
            max_redirects: 5

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
