// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ce88e168e21e081a8275695f4ab0910207dc74fbdc427228f0f8489fd6f348fa
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.crawlberg.android.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import io.xberg.crawlberg.android.Crawlberg
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import kotlin.time.Duration.Companion.milliseconds
import io.xberg.crawlberg.android.CrawlConfig

/** E2e tests for category: markdown. */
class MarkdownTest {

    companion object {
        init {
            // Suite-level environment defaults from [e2e.env]. JVM OS env is
            // immutable; System.setProperty is the runtime-mutable analog. Each
            // entry uses setdefault semantics: only applied when not already set.
            if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
                System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true")
            }
            try {
                System.loadLibrary("cberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load cberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerModule(
            com.fasterxml.jackson.databind.module.SimpleModule()
                .addSerializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonSerializer<kotlin.time.Duration>() {
                    override fun serialize(value: kotlin.time.Duration, gen: com.fasterxml.jackson.core.JsonGenerator, serializers: com.fasterxml.jackson.databind.SerializerProvider) {
                        gen.writeNumber(value.inWholeMilliseconds)
                    }
                })
                .addDeserializer(kotlin.time.Duration::class.java, object : com.fasterxml.jackson.databind.JsonDeserializer<kotlin.time.Duration>() {
                    override fun deserialize(p: com.fasterxml.jackson.core.JsonParser, ctxt: com.fasterxml.jackson.databind.DeserializationContext): kotlin.time.Duration {
                        return p.longValue.milliseconds
                    }
                })
        ).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testCitationsBalancedParens(): Unit = runBlocking {
        // Citations correctly handle links inside parentheses with balanced rendering
        val engine = Crawlberg.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/citations_balanced_parens"
        val result = Crawlberg.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertTrue(result.markdown?.content != null, "expected non-empty value")
        assertTrue(result.markdown?.content.orEmpty().contains("("), "expected to contain: " + "(")
    }

    @Test
    fun testCitationsDuplicateUrls(): Unit = runBlocking {
        // Citations deduplicates multiple links to the same URL
        val engine = Crawlberg.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/citations_duplicate_urls"
        val result = Crawlberg.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertTrue(result.markdown?.content != null, "expected non-empty value")
        assertTrue(result.markdown?.citations != null, "expected true (non-null)")
    }

    @Test
    fun testMarkdownBasicConversion(): Unit = runBlocking {
        // HTML is always converted to markdown alongside raw HTML
        val engine = Crawlberg.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/markdown_basic_conversion"
        val result = Crawlberg.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertEquals("Test", result.metadata.title.orEmpty())
        assertFalse(result.html.isEmpty(), "expected non-empty value")
        assertTrue(result.markdown?.content != null, "expected non-empty value")
        assertTrue(result.markdown?.content.orEmpty().contains("Hello World"), "expected to contain: " + "Hello World")
    }

    @Test
    fun testMarkdownCrawlAllPages(): Unit = runBlocking {
        // All crawled pages have markdown field populated
        val engineConfig = MAPPER.readValue("{\"max_depth\":1,\"ssrf\":{}}", CrawlConfig::class.java)
        val engine = Crawlberg.createEngine(engineConfig)
        val url = System.getProperty("mockServer.markdown_crawl_all_pages", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/markdown_crawl_all_pages")
        val result = Crawlberg.crawl(engine, url)
        assertEquals(2, result.pages.size)
    }

    @Test
    fun testMarkdownFitContent(): Unit = runBlocking {
        // Fit markdown removes navigation and boilerplate content
        val engine = Crawlberg.createEngine(null)
        val url = System.getProperty("mockServer.markdown_fit_content", (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/markdown_fit_content")
        val result = Crawlberg.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertTrue(result.markdown?.content != null, "expected non-empty value")
    }

    @Test
    fun testMarkdownHeadingsAndParagraphs(): Unit = runBlocking {
        // Markdown conversion preserves heading hierarchy and paragraph text
        val engine = Crawlberg.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/markdown_headings_and_paragraphs"
        val result = Crawlberg.scrape(engine, url)
        assertTrue(result.markdown?.content != null, "expected non-empty value")
        assertTrue(result.markdown?.content.orEmpty().contains("Main Title"), "expected to contain: " + "Main Title")
    }

    @Test
    fun testMarkdownLinksConverted(): Unit = runBlocking {
        // HTML links are converted to markdown link syntax
        val engine = Crawlberg.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/markdown_links_converted"
        val result = Crawlberg.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertFalse(result.html.isEmpty(), "expected non-empty value")
        assertTrue(result.markdown?.content != null, "expected non-empty value")
        assertTrue(result.markdown?.content.orEmpty().contains("Example"), "expected to contain: " + "Example")
    }

    @Test
    fun testMarkdownWithCitations(): Unit = runBlocking {
        // Markdown includes citation conversion with numbered references
        val engine = Crawlberg.createEngine(null)
        val url = (System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/markdown_with_citations"
        val result = Crawlberg.scrape(engine, url)
        assertEquals(200, result.statusCode)
        assertTrue(result.markdown?.content != null, "expected non-empty value")
    }

}
