// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a6e291d05e7d12f4aeae622789e44ff3e58c561c4fe764811cc3b36234efc326
// To regenerate: alef generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const crawlberg = @import("crawlberg");

extern "c" fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;
fn allow_private_network() void {
    _ = setenv("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true", 1);
}

// E2e tests for category: auth

test "auth_basic_http" {
    // Sends HTTP Basic authentication header
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_AUTH_BASIC_HTTP")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/auth_basic_http", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.scrape("{\"auth\":{\"password\":\"testpass\",\"type\":\"basic\",\"username\":\"testuser\"},\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqual(true, result.object.get("auth_header_sent").?.bool);
    try testing.expectEqual(@as(i64, 200), result.object.get("status_code").?.integer);
}

test "auth_bearer_token" {
    // Sends Bearer token in Authorization header
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_AUTH_BEARER_TOKEN")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/auth_bearer_token", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.scrape("{\"auth\":{\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.test\",\"type\":\"bearer\"},\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqual(true, result.object.get("auth_header_sent").?.bool);
    try testing.expectEqual(@as(i64, 200), result.object.get("status_code").?.integer);
}

test "auth_custom_header" {
    // Sends authentication via custom header (X-API-Key)
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_AUTH_CUSTOM_HEADER")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/auth_custom_header", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.scrape("{\"auth\":{\"name\":\"X-API-Key\",\"type\":\"header\",\"value\":\"sk-test-key-12345\"},\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqual(true, result.object.get("auth_header_sent").?.bool);
    try testing.expectEqual(@as(i64, 200), result.object.get("status_code").?.integer);
}
