// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:23af3bd5e572ca49769299776df8095a6ddd7bd75d52c9071361bf3c6b3f3e57
// To regenerate: alef generate
// To verify freshness: alef verify

const std = @import("std");

// category "batch" produced no zig tests
// skipped: batch_crawl_basic — excluded for zig e2e generation
// skipped: batch_crawl_partial_failure — excluded for zig e2e generation
// skipped: batch_crawl_with_config — excluded for zig e2e generation
// skipped: batch_scrape_empty_urls_error — excluded for zig e2e generation
// skipped: batch_scrape_with_config — excluded for zig e2e generation
// skipped: scrape_batch_basic — excluded for zig e2e generation
// skipped: scrape_batch_partial_failure — excluded for zig e2e generation
// skipped: scrape_batch_progress — excluded for zig e2e generation

test "batch skipped for zig" {
    return error.SkipZigTest;
}
