// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8e7b9464a9888638286bad92ac08a836dc830f8c3c879abdc8458f161c4854bd
// To regenerate: alef generate
// To verify freshness: alef verify

const std = @import("std");

// category "batch" produced no zig tests
// skipped: batch_crawl_basic — excluded for zig e2e generation
// skipped: batch_crawl_partial_failure — excluded for zig e2e generation
// skipped: batch_crawl_with_config — excluded for zig e2e generation
// skipped: batch_scrape_empty_urls_error — excluded for zig e2e generation
// skipped: batch_scrape_with_config — excluded for zig e2e generation
// skipped: scrape_batch_basic — excluded for zig e2e generation
// skipped: scrape_batch_partial_failure — excluded for zig e2e generation
// skipped: scrape_batch_progress — excluded for zig e2e generation

test "batch skipped for zig" {
    return error.SkipZigTest;
}
