// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1cc157819d135062dc96cea02f79d88b6888be2f00496e32b2bae195b553d936
// To regenerate: alef generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const crawlberg = @import("crawlberg");

extern "c" fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;
fn allow_private_network() void {
    _ = setenv("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true", 1);
}

// E2e tests for category: redirect

test "redirect_301_permanent" {
    // Follows 301 permanent redirect and returns final page content
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_REDIRECT_301_PERMANENT")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/redirect_301_permanent", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.crawl("{\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("final_url").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "/target") != null);
    }
    try testing.expectEqual(@as(i64, 1), result.object.get("redirect_count").?.integer);
}

test "redirect_302_found" {
    // Follows 302 Found redirect correctly
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_REDIRECT_302_FOUND")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/redirect_302_found", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.crawl("{\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("final_url").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "/found-target") != null);
    }
    try testing.expectEqual(@as(i64, 1), result.object.get("redirect_count").?.integer);
}

test "redirect_303_see_other" {
    // Follows 303 See Other redirect (method changes to GET)
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_REDIRECT_303_SEE_OTHER")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/redirect_303_see_other", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.crawl("{\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("final_url").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "/see-other") != null);
    }
    try testing.expectEqual(@as(i64, 1), result.object.get("redirect_count").?.integer);
}

test "redirect_307_temporary" {
    // Follows 307 Temporary Redirect (preserves method)
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_REDIRECT_307_TEMPORARY")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/redirect_307_temporary", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.crawl("{\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("final_url").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "/temp-target") != null);
    }
    try testing.expectEqual(@as(i64, 1), result.object.get("redirect_count").?.integer);
}

test "redirect_308_permanent" {
    // Follows 308 Permanent Redirect (preserves method)
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_REDIRECT_308_PERMANENT")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/redirect_308_permanent", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.crawl("{\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("final_url").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "/perm-target") != null);
    }
    try testing.expectEqual(@as(i64, 1), result.object.get("redirect_count").?.integer);
}

test "redirect_chain" {
    // Follows a chain of redirects (301 -> 302 -> 200)
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_REDIRECT_CHAIN")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/redirect_chain", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.crawl("{\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("final_url").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "/step2") != null);
    }
    try testing.expectEqual(@as(i64, 2), result.object.get("redirect_count").?.integer);
}

test "redirect_cross_domain" {
    // Reports cross-domain redirect target without following to external domain
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_REDIRECT_CROSS_DOMAIN")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/redirect_cross_domain", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.crawl("{\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("final_url").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "/external-redirect") != null);
    }
    try testing.expectEqual(@as(i64, 1), result.object.get("redirect_count").?.integer);
}

test "redirect_loop" {
    // Detects redirect loop (A -> B -> A) and stops following without reaching a final page
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_REDIRECT_LOOP")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/redirect_loop", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.crawl("{\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqual(@as(i64, 1), result.object.get("redirect_count").?.integer);
    try testing.expectEqual(@as(i64, 302), result.object.get("pages").?.array.items[0].object.get("status_code").?.integer);
}

test "redirect_max_exceeded" {
    // Aborts when redirect count exceeds max_redirects limit
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_REDIRECT_MAX_EXCEEDED")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/redirect_max_exceeded", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.crawl("{\"max_redirects\":2,\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqual(@as(i64, 2), result.object.get("redirect_count").?.integer);
    try testing.expectEqual(@as(i64, 301), result.object.get("pages").?.array.items[0].object.get("status_code").?.integer);
}

test "redirect_meta_refresh" {
    // Follows HTML meta-refresh redirect to target page
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_REDIRECT_META_REFRESH")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/redirect_meta_refresh", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.crawl("{\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("final_url").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "/target") != null);
    }
    try testing.expectEqual(@as(i64, 1), result.object.get("redirect_count").?.integer);
}

test "redirect_refresh_header" {
    // Handles HTTP Refresh header redirect
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_REDIRECT_REFRESH_HEADER")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/redirect_refresh_header", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.crawl("{\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("final_url").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "/refreshed") != null);
    }
    try testing.expectEqual(@as(i64, 1), result.object.get("redirect_count").?.integer);
}

test "redirect_to_404" {
    // Redirect target returns 404 Not Found
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const url = if (std.c.getenv("MOCK_SERVER_REDIRECT_TO_404")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/redirect_to_404", .{if (std.c.getenv("MOCK_SERVER_URL")) |v| std.mem.span(v) else "http://localhost:8080"});
    defer allocator.free(url);
    const _result_json = try crawlberg.crawl("{\"respect_robots_txt\":false}", url);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("final_url").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "/gone") != null);
    }
    try testing.expectEqual(@as(i64, 1), result.object.get("redirect_count").?.integer);
    {
        const _jv = (result.object.get("error") orelse std.json.Value{ .null = {} });
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "404") != null);
    }
}
