// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d1c3a29a612d696ea19a1347b9a1d0de7b16ff902c3f989bf6f9c345b983969e
// To regenerate: alef generate
// To verify freshness: alef verify

const std = @import("std");

// category "stream" produced no zig tests
// skipped: batch_crawl_stream_events — excluded for zig e2e generation
// skipped: batch_crawl_stream_partial_failure — excluded for zig e2e generation
// skipped: crawl_stream_events — excluded for zig e2e generation
// skipped: stream_depth_crawl — excluded for zig e2e generation
// skipped: stream_error_event_mid_crawl — excluded for zig e2e generation
// skipped: stream_event_ordering — excluded for zig e2e generation
// skipped: stream_large_crawl — excluded for zig e2e generation
// skipped: stream_with_error_event — excluded for zig e2e generation

test "stream skipped for zig" {
    return error.SkipZigTest;
}
