// Generated by alef — intentionally empty.
// alef:hash:928639b574d5fca9c5b51f86fe815c5bc0779c92416dbaa12f74160457caaf3a
// Streaming-adapter owner handles are declared canonically (once) in the
// Rust extern blocks, so swift-bridge synthesizes their class triple and
// `$_free` destructor directly; no hand-rolled class hierarchy is needed.

import Foundation
import RustBridgeC
