# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2bbb68fab1d7b0c2d0827ba0e137701a7dc1abdb794be8879680465bc96521aa
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: auth."""

import os
import pytest  # noqa: F401
from crawlberg import scrape, create_engine, CrawlConfig


@pytest.mark.asyncio
async def test_auth_basic_http() -> None:
    """Sends HTTP Basic authentication header."""
    engine_config = CrawlConfig(
        auth={"password": "testpass", "type": "basic", "username": "testuser"},
        respect_robots_txt=False,
    )
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/auth_basic_http"

    result = await scrape(engine, url)
    assert result.auth_header_sent is True  # noqa: S101
    assert result.status_code == 200  # noqa: S101


@pytest.mark.asyncio
async def test_auth_bearer_token() -> None:
    """Sends Bearer token in Authorization header."""
    engine_config = CrawlConfig(
        auth={"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.test", "type": "bearer"},
        respect_robots_txt=False,
    )
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/auth_bearer_token"

    result = await scrape(engine, url)
    assert result.auth_header_sent is True  # noqa: S101
    assert result.status_code == 200  # noqa: S101


@pytest.mark.asyncio
async def test_auth_custom_header() -> None:
    """Sends authentication via custom header (X-API-Key)."""
    engine_config = CrawlConfig(
        auth={"name": "X-API-Key", "type": "header", "value": "sk-test-key-12345"},
        respect_robots_txt=False,
    )
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/auth_custom_header"

    result = await scrape(engine, url)
    assert result.auth_header_sent is True  # noqa: S101
    assert result.status_code == 200  # noqa: S101
