# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:70074915c85be474db84aae9140de8360a13f9b43022ab9b9dd3433702c6f73e
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: links."""

import os
import pytest  # noqa: F401
from crawlberg import scrape, create_engine


@pytest.mark.asyncio
async def test_links_anchor_fragment() -> None:
    """Identifies fragment-only links as anchor type."""
    engine = create_engine(None)
    url = (
        os.environ.get("MOCK_SERVER_LINKS_ANCHOR_FRAGMENT")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/links_anchor_fragment"
    )

    result = await scrape(engine, url)
    assert any("anchor" in str(_e.link_type) for _e in (result.links or []))  # noqa: S101


@pytest.mark.asyncio
async def test_links_base_tag() -> None:
    """Resolves relative URLs using base tag href."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/links_base_tag"

    result = await scrape(engine, url)
    assert len(result.links) > 2  # noqa: S101
    assert any("example.com" in str(_e.url) for _e in (result.links or []))  # noqa: S101


@pytest.mark.asyncio
async def test_links_document_types() -> None:
    """Detects PDF, DOCX, XLSX links as document type."""
    engine = create_engine(None)
    url = (
        os.environ.get("MOCK_SERVER_LINKS_DOCUMENT_TYPES")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/links_document_types"
    )

    result = await scrape(engine, url)
    assert any("document" in str(_e.link_type) for _e in (result.links or []))  # noqa: S101


@pytest.mark.asyncio
async def test_links_empty_href() -> None:
    """Handles empty href attributes without errors."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/links_empty_href"

    result = await scrape(engine, url)
    assert len(result.links) > 0  # noqa: S101
    assert any("/valid" in str(_e.url) for _e in (result.links or []))  # noqa: S101


@pytest.mark.asyncio
async def test_links_internal_external_classification() -> None:
    """Correctly classifies internal vs external links by domain."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/links_internal_external_classification"

    result = await scrape(engine, url)
    assert len(result.links) > 4  # noqa: S101
    assert any(str(_e.url) != "" for _e in (result.links or []))  # noqa: S101


@pytest.mark.asyncio
async def test_links_mailto_javascript_skip() -> None:
    """Skips mailto:, javascript:, and tel: scheme links."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/links_mailto_javascript_skip"

    result = await scrape(engine, url)
    assert len(result.links) > 0  # noqa: S101
    assert not any("mailto:" in str(_e.url) for _e in (result.links or []))  # noqa: S101


@pytest.mark.asyncio
async def test_links_protocol_relative() -> None:
    """Handles protocol-relative URLs (//example.com) correctly."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/links_protocol_relative"

    result = await scrape(engine, url)
    assert len(result.links) > 1  # noqa: S101
    assert any("//" in str(_e.url) for _e in (result.links or []))  # noqa: S101


@pytest.mark.asyncio
async def test_links_rel_attributes() -> None:
    """Preserves rel=nofollow and rel=canonical attributes."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/links_rel_attributes"

    result = await scrape(engine, url)
    assert len(result.links) > 0  # noqa: S101


@pytest.mark.asyncio
async def test_links_relative_parent() -> None:
    """Resolves ../ and ./ relative parent path links correctly."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/links_relative_parent"

    result = await scrape(engine, url)
    assert len(result.links) > 3  # noqa: S101
