# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8dc321aecd28dfeceb4eed6a34fe1fcf57dfd291b2d441b8a855ed2fab37e8f7
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: filter."""

import os
import pytest  # noqa: F401
from crawlberg import crawl, create_engine, CrawlConfig


@pytest.mark.asyncio
async def test_filter_bm25_crawl_integration() -> None:
    """BM25 filter works during multi-page crawl, keeping relevant pages."""
    engine_config = CrawlConfig(
        bm25_query="rust programming",
        bm25_threshold=0.1,
        content_filter="bm25",
        max_concurrent=1,
        max_depth=1,
    )
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_FILTER_BM25_CRAWL_INTEGRATION")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/filter_bm25_crawl_integration"
    )

    result = await crawl(engine, url)
    assert "rust".lower() in str(result.pages[0].html).lower()  # noqa: S101


@pytest.mark.asyncio
async def test_filter_bm25_empty_query() -> None:
    """BM25 filter with empty query passes all pages through."""
    engine_config = CrawlConfig(bm25_query="", bm25_threshold=0.1, content_filter="bm25", max_depth=1)
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_FILTER_BM25_EMPTY_QUERY")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/filter_bm25_empty_query"
    )

    result = await crawl(engine, url)
    assert len(result.pages) == 2  # noqa: S101


@pytest.mark.asyncio
async def test_filter_bm25_high_threshold() -> None:
    """BM25 filter with very high threshold filters out all pages."""
    engine_config = CrawlConfig(bm25_query="quantum physics", bm25_threshold=100.0, content_filter="bm25", max_depth=1)
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_FILTER_BM25_HIGH_THRESHOLD")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/filter_bm25_high_threshold"
    )

    result = await crawl(engine, url)
    assert len(result.pages) == 0  # noqa: S101


@pytest.mark.asyncio
async def test_filter_bm25_relevant_pages() -> None:
    """BM25 filter keeps only pages relevant to the query."""
    engine_config = CrawlConfig(
        bm25_query="rust programming language",
        bm25_threshold=0.1,
        content_filter="bm25",
        max_depth=1,
    )
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_FILTER_BM25_RELEVANT_PAGES")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/filter_bm25_relevant_pages"
    )

    result = await crawl(engine, url)
    assert "rust".lower() in str(result.pages[0].html).lower()  # noqa: S101


@pytest.mark.asyncio
async def test_filter_bm25_threshold_zero() -> None:
    """BM25 filter with zero threshold passes all pages."""
    engine_config = CrawlConfig(bm25_query="unrelated query", bm25_threshold=0.0, content_filter="bm25", max_depth=1)
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_FILTER_BM25_THRESHOLD_ZERO")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/filter_bm25_threshold_zero"
    )

    result = await crawl(engine, url)
    assert len(result.pages) == 2  # noqa: S101


@pytest.mark.asyncio
async def test_filter_noop_crawl_all_kept() -> None:
    """NoopFilter keeps all pages during a multi-page crawl."""
    engine_config = CrawlConfig(max_concurrent=1, max_depth=1)
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_FILTER_NOOP_CRAWL_ALL_KEPT")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/filter_noop_crawl_all_kept"
    )

    result = await crawl(engine, url)
    assert len(result.pages) == 3  # noqa: S101


@pytest.mark.asyncio
async def test_filter_noop_passes_all() -> None:
    """No content filter passes all crawled pages through."""
    engine_config = CrawlConfig(max_depth=1)
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_FILTER_NOOP_PASSES_ALL")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/filter_noop_passes_all"
    )

    result = await crawl(engine, url)
    assert len(result.pages) == 3  # noqa: S101
