# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:48f45896833364bb8b875500ad3b429af38be5729b3b25c30377b45bff6996ec
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: auth."""

import os

import pytest
from crawlberg import scrape, create_engine, CrawlConfig


@pytest.mark.asyncio
async def test_auth_basic_http() -> None:
    """Sends HTTP Basic authentication header."""
    engine_config = CrawlConfig(
        auth={"password": "testpass", "type": "basic", "username": "testuser"},
        respect_robots_txt=False,
    )
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/auth_basic_http"

    result = await scrape(engine, url)
    assert result["auth_header_sent"] is True
    assert result["status_code"] == 200


@pytest.mark.asyncio
async def test_auth_bearer_token() -> None:
    """Sends Bearer token in Authorization header."""
    engine_config = CrawlConfig(
        auth={"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.test", "type": "bearer"},
        respect_robots_txt=False,
    )
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/auth_bearer_token"

    result = await scrape(engine, url)
    assert result["auth_header_sent"] is True
    assert result["status_code"] == 200


@pytest.mark.asyncio
async def test_auth_custom_header() -> None:
    """Sends authentication via custom header (X-API-Key)."""
    engine_config = CrawlConfig(
        auth={"name": "X-API-Key", "type": "header", "value": "sk-test-key-12345"},
        respect_robots_txt=False,
    )
    engine = create_engine(engine_config)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/auth_custom_header"

    result = await scrape(engine, url)
    assert result["auth_header_sent"] is True
    assert result["status_code"] == 200
