// Generated by alef. Do not edit by hand.
// alef:hash:8b332e9c659b1d818d22d94ac613d3bc57e0b8b02bc8e2d53d3a00198b452e8c

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "crawlberg-e2e"
