# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:11ee106a38b2ae65fce6fe168519b69ed130d9737c4c779b9488e97ae37040e8
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require_relative "crawlberg/version"
require_relative "crawlberg/native"

# Top-level namespace for the Crawlberg Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "crawlberg/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module Crawlberg
  # Re-export all types and functions from native extension
end

# Keep generated types under Crawlberg. Publishing generated constants
# into Object makes generic names collide with unrelated Ruby libraries.
