# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:72251b3aa02bf769e473206839c833cf616e70a8dd38735f5ff3a3a2849e8c0a
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require_relative "crawlberg/version"
require_relative "crawlberg/native"

# Top-level namespace for the Crawlberg Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "crawlberg/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module Crawlberg
  # Re-export all types and functions from native extension
end

# Keep generated types under Crawlberg. Publishing generated constants
# into Object makes generic names collide with unrelated Ruby libraries.
