# Generated by alef. Do not edit by hand.
# alef:hash:57b737fc78678b0abdb1466f1e2ea13a9deb1727bcea1a9928217d173154606d
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.crawlberg.android.** { *; }
