# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:599dc32931e5358799b0fc145412fd4c9a3e066be9a9e46e423868e98cf8688b
# To regenerate: alef generate
# To verify freshness: alef verify
"""Exception hierarchy (re-exported from the native module)."""

from ._crawlberg import (
    BadGatewayError,
    BrowserError,
    BrowserTimeoutError,
    CrawlConnectionError,
    CrawlError,
    CrawlTimeoutError,
    DataLossError,
    DeniedByPolicyError,
    DisallowedSchemeError,
    DnsError,
    DnsResolutionFailedError,
    ForbiddenError,
    GoneError,
    InvalidCidrError,
    InvalidConfigError,
    InvalidUrlError,
    NotFoundError,
    NotOnAllowlistError,
    OtherError,
    RateLimitedError,
    ServerError,
    SslError,
    SsrfError,
    SsrfPolicyViolationError,
    TooManyRedirectsError,
    UnauthorizedError,
    UnsupportedError,
    WafBlockedError,
)

__all__ = [
    "BadGatewayError",
    "BrowserError",
    "BrowserTimeoutError",
    "CrawlConnectionError",
    "CrawlError",
    "CrawlTimeoutError",
    "DataLossError",
    "DeniedByPolicyError",
    "DisallowedSchemeError",
    "DnsError",
    "DnsResolutionFailedError",
    "ForbiddenError",
    "GoneError",
    "InvalidCidrError",
    "InvalidConfigError",
    "InvalidUrlError",
    "NotFoundError",
    "NotOnAllowlistError",
    "OtherError",
    "RateLimitedError",
    "ServerError",
    "SslError",
    "SsrfError",
    "SsrfPolicyViolationError",
    "TooManyRedirectsError",
    "UnauthorizedError",
    "UnsupportedError",
    "WafBlockedError",
]

# Re-point each exception's __module__ at the public package so tracebacks show the
# public name (e.g. "DownloadError"), not the native module name (GitHub issue #147).
_public_module = __name__.rsplit(".", 1)[0]
for _name in __all__:
    globals()[_name].__module__ = _public_module
del _name, _public_module
