// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3a1917e5db668dfe5f72cf0122d3b3eec3fb0855563c85c74cfa0f0d11fc4ae5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
    globalSetup: "./globalSetup.ts",
    setupFiles: ["./setup.ts"],
  },
});
