// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e2177cbe758f2dc53d9fb699458c2b04cde30115d51d45a072a834d1191bc74a
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
    globalSetup: "./globalSetup.ts",
    setupFiles: ["./setup.ts"],
  },
});
