// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3f64b8cf7d9b29a1e64ed2b0e664706db6c200b88ce91b11ee4d9926cb2154fe
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import * as pkg from "@xberg-io/crawlberg-wasm";

describe("smoke", () => {
  it("imports the published wasm package", () => {
    expect(pkg).toBeDefined();
    expect(typeof pkg).toBe("object");
  });
});
