// Generated by alef. Do not edit by hand.
// alef:hash:cfca04278c36532b6c4e3d14002c14b0ce6ddf1a33f17242b151b9d1daebffc8

// Traits module (empty in Dart as Dart does not have trait systems like Rust).
// This file is kept for API surface consistency across language bindings.
