// Generated by alef. Do not edit by hand.
// alef:hash:ed6753aa35e27ad4764a749b35d849473835fb530fcba666ac607635b1333c06

// Traits module (empty in Dart as Dart does not have trait systems like Rust).
// This file is kept for API surface consistency across language bindings.
