# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e0600612767fdd3d51e9128afdb0ffcd1fb490e9942f3839a5120ab7a4e3b658
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Smoke test: import the published package."""

import importlib


def test_imports_published_package():
    module = importlib.import_module("crawlberg")
    assert module is not None
