# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:00d227931f0d518706af640746782c53c295c3e94f7db5d7180c0f1ee66bc12d
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: markdown."""

import os

import pytest
from crawlberg import scrape, crawl, create_engine, CrawlConfig


@pytest.mark.asyncio
async def test_citations_balanced_parens() -> None:
    """Citations correctly handle links inside parentheses with balanced rendering."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/citations_balanced_parens"

    result = await scrape(engine, url)
    assert result["status_code"] == 200
    assert (result["markdown"].content if result["markdown"] else None) is not None and (
        not hasattr(result["markdown"].content if result["markdown"] else None, "__len__")
        or len(result["markdown"].content if result["markdown"] else None) > 0
    )
    assert "(" in (result["markdown"].content if result["markdown"] else None)


@pytest.mark.asyncio
async def test_citations_duplicate_urls() -> None:
    """Citations deduplicates multiple links to the same URL."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/citations_duplicate_urls"

    result = await scrape(engine, url)
    assert result["status_code"] == 200
    assert (result["markdown"].content if result["markdown"] else None) is not None and (
        not hasattr(result["markdown"].content if result["markdown"] else None, "__len__")
        or len(result["markdown"].content if result["markdown"] else None) > 0
    )
    assert (result["markdown"].citations if result["markdown"] else None) is True


@pytest.mark.asyncio
async def test_markdown_basic_conversion() -> None:
    """HTML is always converted to markdown alongside raw HTML."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/markdown_basic_conversion"

    result = await scrape(engine, url)
    assert result["status_code"] == 200
    assert result["metadata"].title == "Test"
    assert result["html"] is not None and (not hasattr(result["html"], "__len__") or len(result["html"]) > 0)
    assert (result["markdown"].content if result["markdown"] else None) is not None and (
        not hasattr(result["markdown"].content if result["markdown"] else None, "__len__")
        or len(result["markdown"].content if result["markdown"] else None) > 0
    )
    assert "Hello World" in (result["markdown"].content if result["markdown"] else None)


@pytest.mark.asyncio
async def test_markdown_crawl_all_pages() -> None:
    """All crawled pages have markdown field populated."""
    engine_config = CrawlConfig(max_depth=1)
    engine = create_engine(engine_config)
    url = (
        os.environ.get("MOCK_SERVER_MARKDOWN_CRAWL_ALL_PAGES")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/markdown_crawl_all_pages"
    )

    result = await crawl(engine, url)
    assert len(result["pages"]) == 2


@pytest.mark.asyncio
async def test_markdown_fit_content() -> None:
    """Fit markdown removes navigation and boilerplate content."""
    engine = create_engine(None)
    url = (
        os.environ.get("MOCK_SERVER_MARKDOWN_FIT_CONTENT")
        or os.environ["MOCK_SERVER_URL"] + "/fixtures/markdown_fit_content"
    )

    result = await scrape(engine, url)
    assert result["status_code"] == 200
    assert (result["markdown"].content if result["markdown"] else None) is not None and (
        not hasattr(result["markdown"].content if result["markdown"] else None, "__len__")
        or len(result["markdown"].content if result["markdown"] else None) > 0
    )


@pytest.mark.asyncio
async def test_markdown_headings_and_paragraphs() -> None:
    """Markdown conversion preserves heading hierarchy and paragraph text."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/markdown_headings_and_paragraphs"

    result = await scrape(engine, url)
    assert (result["markdown"].content if result["markdown"] else None) is not None and (
        not hasattr(result["markdown"].content if result["markdown"] else None, "__len__")
        or len(result["markdown"].content if result["markdown"] else None) > 0
    )
    assert "Main Title" in (result["markdown"].content if result["markdown"] else None)


@pytest.mark.asyncio
async def test_markdown_links_converted() -> None:
    """HTML links are converted to markdown link syntax."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/markdown_links_converted"

    result = await scrape(engine, url)
    assert result["status_code"] == 200
    assert result["html"] is not None and (not hasattr(result["html"], "__len__") or len(result["html"]) > 0)
    assert (result["markdown"].content if result["markdown"] else None) is not None and (
        not hasattr(result["markdown"].content if result["markdown"] else None, "__len__")
        or len(result["markdown"].content if result["markdown"] else None) > 0
    )
    assert "Example" in (result["markdown"].content if result["markdown"] else None)


@pytest.mark.asyncio
async def test_markdown_with_citations() -> None:
    """Markdown includes citation conversion with numbered references."""
    engine = create_engine(None)
    url = os.environ["MOCK_SERVER_URL"] + "/fixtures/markdown_with_citations"

    result = await scrape(engine, url)
    assert result["status_code"] == 200
    assert (result["markdown"].content if result["markdown"] else None) is not None and (
        not hasattr(result["markdown"].content if result["markdown"] else None, "__len__")
        or len(result["markdown"].content if result["markdown"] else None) > 0
    )
