// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:01f37ebb1e7082896351546caef270e2c38f950408ca3bf3652adf8ff480be10
// To regenerate: alef generate
// To verify freshness: alef verify
import { describe, it } from "vitest";

describe("cookies", () => {
    // wasm has no Tower middleware for HTTP header cookie extraction
    it.skip("cookies_per_domain", () => {});
    // wasm has no Tower middleware for HTTP header cookie extraction
    it.skip("cookies_persistence", () => {});
    // wasm has no Tower middleware for HTTP header cookie extraction
    it.skip("cookies_set_cookie_response", () => {});
});
