// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:acc58dbc58708083b4d68dc48baede31af01ae9c04b8485c34349b238f906b38
// To regenerate: alef e2e generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { scrape, createEngine, WasmCrawlConfig, WasmAuthConfig, WasmBrowserConfig, WasmContentConfig, WasmProxyConfig, WasmSsrfPolicy } from "@xberg-io/crawlberg-wasm";

process.env.CRAWLBERG_ALLOW_PRIVATE_NETWORK ??= "true";


async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let bytes = new Uint8Array(await response.arrayBuffer());

	// The runtime's own fetch (undici on Node, and the browser equivalent) decodes
	// `content-encoding` transparently and leaves the header in place, so by the time the
	// body reaches here it is usually already plain text. Decoding unconditionally on the
	// header alone therefore fails ("incorrect header check") against a server that really
	// did compress. Decode only when the payload still carries the encoding: gzip announces
	// itself with the 0x1f8b magic pair; brotli has no magic, so it is attempted and the
	// already-decoded case falls back to the bytes as received.
	if (contentEncoding === "gzip" && bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) {
		const { gunzipSync } = await import("zlib");
		bytes = new Uint8Array(gunzipSync(bytes));
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		try {
			bytes = new Uint8Array(brotliDecompressSync(bytes));
		} catch {
			// Already decoded by the runtime.
		}
	}

	const text = new TextDecoder().decode(bytes);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is internally tagged, so serde merges the variant payload's own fields as
	// siblings of the tag rather than nesting them: { format_type: 'image', format: 'PNG', ... }.
	// Read `format` off the record directly. Deliberately NO nested (`record.image`) fallback --
	// a binding that regresses to the pre-flatten shape must fail this assertion loudly instead
	// of silently degrading to the variant name below.
	if (formatType === "image" && typeof record.format === "string") {
		return record.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("links", () => {

	it("links_anchor_fragment: Identifies fragment-only links as anchor type", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url = process.env.MOCK_SERVER_LINKS_ANCHOR_FRAGMENT ?? `${process.env.MOCK_SERVER_URL}/fixtures/links_anchor_fragment`;
		const result = await scrape(engine, url);
    expect((result.links ?? []).some((e) => String(e.linkType).includes("anchor"))).toBe(true);

	}, 30000);

	it("links_base_tag: Resolves relative URLs using base tag href", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url = `${process.env.MOCK_SERVER_URL}/fixtures/links_base_tag`;
		const result = await scrape(engine, url);
    expect(Number(result.links.length)).toBeGreaterThan(2);
    expect((result.links ?? []).some((e) => String(e.url).includes("example.com"))).toBe(true);

	}, 30000);

	it("links_document_types: Detects PDF, DOCX, XLSX links as document type", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url = process.env.MOCK_SERVER_LINKS_DOCUMENT_TYPES ?? `${process.env.MOCK_SERVER_URL}/fixtures/links_document_types`;
		const result = await scrape(engine, url);
    expect((result.links ?? []).some((e) => String(e.linkType).includes("document"))).toBe(true);

	}, 30000);

	it("links_empty_href: Handles empty href attributes without errors", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url = `${process.env.MOCK_SERVER_URL}/fixtures/links_empty_href`;
		const result = await scrape(engine, url);
    expect(Number(result.links.length)).toBeGreaterThan(0);
    expect((result.links ?? []).some((e) => String(e.url).includes("/valid"))).toBe(true);

	}, 30000);

	it("links_internal_external_classification: Correctly classifies internal vs external links by domain", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url = `${process.env.MOCK_SERVER_URL}/fixtures/links_internal_external_classification`;
		const result = await scrape(engine, url);
    expect(Number(result.links.length)).toBeGreaterThan(4);
    expect((result.links ?? []).some((e) => String(e.url).length > 0)).toBe(true);

	}, 30000);

	it("links_mailto_javascript_skip: Skips mailto:, javascript:, and tel: scheme links", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url = `${process.env.MOCK_SERVER_URL}/fixtures/links_mailto_javascript_skip`;
		const result = await scrape(engine, url);
    expect(Number(result.links.length)).toBeGreaterThan(0);
    expect((result.links ?? []).some((e) => String(e.url).includes("mailto:"))).toBe(false);

	}, 30000);

	it("links_protocol_relative: Handles protocol-relative URLs (//example.com) correctly", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url = `${process.env.MOCK_SERVER_URL}/fixtures/links_protocol_relative`;
		const result = await scrape(engine, url);
    expect(Number(result.links.length)).toBeGreaterThan(1);
    expect((result.links ?? []).some((e) => String(e.url).includes("http://cdn.example.com/resource"))).toBe(true);
    expect((result.links ?? []).some((e) => String(e.url).includes("http://images.example.com/photo.jpg"))).toBe(true);

	}, 30000);

	it("links_rel_attributes: Preserves rel=nofollow and rel=canonical attributes", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url = `${process.env.MOCK_SERVER_URL}/fixtures/links_rel_attributes`;
		const result = await scrape(engine, url);
    expect(Number(result.links.length)).toBeGreaterThan(0);

	}, 30000);

	it("links_relative_parent: Resolves ../ and ./ relative parent path links correctly", async () => {
		const engineConfig = WasmCrawlConfig.default();
		engineConfig.ssrf.denyPrivate = false;
		const engine = createEngine(engineConfig);
		const url = `${process.env.MOCK_SERVER_URL}/fixtures/links_relative_parent`;
		const result = await scrape(engine, url);
    expect(Number(result.links.length)).toBeGreaterThan(3);

	}, 30000);

});
