// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3914a6a9dcdbb11dcc5a39d86559e076e6aacd88d2fc17f08c43f77d2b8ed751
// To regenerate: alef e2e generate
// To verify freshness: alef verify
import { describe, it } from "vitest";

describe("stream", () => {
    // excluded for wasm e2e generation
    it.skip("batch_crawl_stream_events", () => {});
    // excluded for wasm e2e generation
    it.skip("batch_crawl_stream_partial_failure", () => {});
    // excluded for wasm e2e generation
    it.skip("crawl_stream_events", () => {});
    // excluded for wasm e2e generation
    it.skip("stream_depth_crawl", () => {});
    // excluded for wasm e2e generation
    it.skip("stream_error_event_mid_crawl", () => {});
    // excluded for wasm e2e generation
    it.skip("stream_event_ordering", () => {});
    // excluded for wasm e2e generation
    it.skip("stream_large_crawl", () => {});
    // excluded for wasm e2e generation
    it.skip("stream_with_error_event", () => {});
});
