# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:914f9aa75862ecce6dbfef4a56e0f27aa6f270753d50527ec3480df52473e5ff
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'crawlberg'
require 'json'

RSpec.describe 'stream' do
  it 'batch_crawl_stream_events: Batch crawl stream produces expected Page and Complete events' do
    # skipped: streaming assertion on unsupported field 'stream.event_count_min'
    # skipped: streaming assertion on unsupported field 'stream.has_page_event'
    # skipped: streaming assertion on unsupported field 'stream.has_complete_event'
    # skipped: streaming assertion on unsupported field 'stream_complete'; this stream's chunks carry no terminal finish_reason, so completion is not observable here
    skip 'alef rendered no runnable expectation for fixture `batch_crawl_stream_events`: all 4 declared assertion(s) were skipped (see the markers above)'
  end

  it 'batch_crawl_stream_partial_failure: Batch crawl stream emits both Page and Error events for mixed success/failure URLs' do
    # skipped: streaming assertion on unsupported field 'stream.has_page_event'
    # skipped: streaming assertion on unsupported field 'stream.has_error_event'
    # skipped: streaming assertion on unsupported field 'stream.has_complete_event'
    # skipped: streaming assertion on unsupported field 'stream_complete'; this stream's chunks carry no terminal finish_reason, so completion is not observable here
    skip 'alef rendered no runnable expectation for fixture `batch_crawl_stream_partial_failure`: all 4 declared assertion(s) were skipped (see the markers above)'
  end

  it 'crawl_stream_events: Crawl stream produces page and complete events' do
    # skipped: streaming assertion on unsupported field 'stream.event_count_min'
    # skipped: streaming assertion on unsupported field 'stream.has_page_event'
    # skipped: streaming assertion on unsupported field 'stream.has_complete_event'
    # skipped: streaming assertion on unsupported field 'stream_complete'; this stream's chunks carry no terminal finish_reason, so completion is not observable here
    skip 'alef rendered no runnable expectation for fixture `crawl_stream_events`: all 4 declared assertion(s) were skipped (see the markers above)'
  end

  it 'stream_depth_crawl: Stream produces events for multi-depth crawl with link following' do
    # skipped: streaming assertion on unsupported field 'stream.event_count_min'
    # skipped: streaming assertion on unsupported field 'stream.has_page_event'
    # skipped: streaming assertion on unsupported field 'stream.has_complete_event'
    # skipped: streaming assertion on unsupported field 'stream_complete'; this stream's chunks carry no terminal finish_reason, so completion is not observable here
    skip 'alef rendered no runnable expectation for fixture `stream_depth_crawl`: all 4 declared assertion(s) were skipped (see the markers above)'
  end

  it 'stream_error_event_mid_crawl: Stream emits error event when a page fails mid-crawl, but other pages succeed' do
    # skipped: streaming assertion on unsupported field 'stream.has_page_event'
    # skipped: streaming assertion on unsupported field 'stream.has_error_event'
    # skipped: streaming assertion on unsupported field 'stream.has_complete_event'
    # skipped: streaming assertion on unsupported field 'stream_complete'; this stream's chunks carry no terminal finish_reason, so completion is not observable here
    skip 'alef rendered no runnable expectation for fixture `stream_error_event_mid_crawl`: all 4 declared assertion(s) were skipped (see the markers above)'
  end

  it 'stream_event_ordering: Stream ensures complete event arrives after all page events' do
    # skipped: streaming assertion on unsupported field 'stream.has_complete_event'
    # skipped: streaming assertion on unsupported field 'stream.has_page_event'
    # skipped: streaming assertion on unsupported field 'stream.event_count_min'
    # skipped: streaming assertion on unsupported field 'stream_complete'; this stream's chunks carry no terminal finish_reason, so completion is not observable here
    skip 'alef rendered no runnable expectation for fixture `stream_event_ordering`: all 4 declared assertion(s) were skipped (see the markers above)'
  end

  it 'stream_large_crawl: Stream handles crawl of 5+ pages with multiple events' do
    # skipped: streaming assertion on unsupported field 'stream.event_count_min'
    # skipped: streaming assertion on unsupported field 'stream.has_page_event'
    # skipped: streaming assertion on unsupported field 'stream.has_complete_event'
    # skipped: streaming assertion on unsupported field 'stream_complete'; this stream's chunks carry no terminal finish_reason, so completion is not observable here
    skip 'alef rendered no runnable expectation for fixture `stream_large_crawl`: all 4 declared assertion(s) were skipped (see the markers above)'
  end

  it 'stream_with_error_event: Stream emits page and complete events even when some pages fail' do
    # skipped: streaming assertion on unsupported field 'stream.has_page_event'
    # skipped: streaming assertion on unsupported field 'stream.has_complete_event'
    # skipped: streaming assertion on unsupported field 'stream.event_count_min'
    # skipped: streaming assertion on unsupported field 'stream_complete'; this stream's chunks carry no terminal finish_reason, so completion is not observable here
    skip 'alef rendered no runnable expectation for fixture `stream_with_error_event`: all 4 declared assertion(s) were skipped (see the markers above)'
  end
end
