# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:68ca1c6327cae52c32756ad33cd7c5ec8ea0d0c95c56b741f880c9bfecaf8014
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'crawlberg'
require 'json'

RSpec.describe 'validation' do
  it 'validation_browser_endpoint_invalid: Browser endpoint must be a valid ws:// or wss:// URL, not http://' do
    expect do
      engine_config = { 'browser' => { 'endpoint' => 'http://not-websocket:3000', 'mode' => 'always' } }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_browser_endpoint_invalid"
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /endpoint/ || error.class.name =~ /endpoint/).to be_truthy
    }
  end

  it 'validation_invalid_auth_config: auth object with empty username in basic auth is rejected' do
    expect do
      engine_config = { 'auth' => { 'password' => 'secret', 'type' => 'basic', 'username' => '' } }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_invalid_auth_config"
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /auth/ || error.class.name =~ /auth/).to be_truthy
    }
  end

  it 'validation_invalid_exclude_regex: Invalid regex in exclude_paths is rejected' do
    expect do
      engine_config = { 'exclude_paths' => ['(unclosed'] }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_invalid_exclude_regex"
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /exclude_path/ || error.class.name =~ /exclude_path/).to be_truthy
    }
  end

  it 'validation_invalid_include_regex: Invalid regex in include_paths is rejected' do
    expect do
      engine_config = { 'include_paths' => ['[invalid'] }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_invalid_include_regex"
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /include_path/ || error.class.name =~ /include_path/).to be_truthy
    }
  end

  it "validation_invalid_proxy_url: proxy with invalid URL like 'not-a-url' is rejected" do
    expect do
      engine_config = { 'proxy' => { 'url' => 'not-a-url' } }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_invalid_proxy_url"
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /proxy/ || error.class.name =~ /proxy/).to be_truthy
    }
  end

  it 'validation_invalid_retry_code: Retry code outside 100-599 is rejected' do
    expect do
      engine_config = { 'retry_codes' => [999] }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_invalid_retry_code"
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /retry code/ || error.class.name =~ /retry code/).to be_truthy
    }
  end

  it 'validation_max_concurrent_zero: max_concurrent=0 is rejected as invalid config (minimum is 1)' do
    expect do
      engine_config = { 'max_concurrent' => 0 }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_max_concurrent_zero"
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /max_concurrent/ || error.class.name =~ /max_concurrent/).to be_truthy
    }
  end

  it 'validation_max_depth_too_high: max_depth=200 exceeds limit of 100' do
    expect do
      engine_config = { 'max_depth' => 200 }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_max_depth_too_high"
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /max_depth/ || error.class.name =~ /max_depth/).to be_truthy
    }
  end

  it 'validation_max_pages_zero: max_pages=0 is rejected as invalid config' do
    expect do
      engine_config = { 'max_pages' => 0 }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_max_pages_zero"
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /max_pages/ || error.class.name =~ /max_pages/).to be_truthy
    }
  end

  it 'validation_max_redirects_too_high: max_redirects > 100 is rejected as invalid config' do
    expect do
      engine_config = { 'max_redirects' => 200 }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_max_redirects_too_high"
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /max_redirects/ || error.class.name =~ /max_redirects/).to be_truthy
    }
  end

  it 'validation_negative_body_size: max_body_size set to -1 is rejected as invalid config' do
    expect do
      engine_config = { 'max_body_size' => 0 }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_negative_body_size"
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /body_size/ || error.class.name =~ /body_size/).to be_truthy
    }
  end

  it 'validation_ssrf_allowlisted_loopback: SSRF allowlist permits a loopback mock server while private-network protection remains enabled' do
    engine_config = { 'respect_robots_txt' => false, 'ssrf' => { 'allowlist' => [{ 'type' => 'cidr', 'value' => '127.0.0.0/8' }], 'deny_private' => true, 'max_redirects' => 5 }, 'ssrf_deny_private_explicit' => true }
    engine = Crawlberg.create_engine(engine_config.to_json)
    url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_ssrf_allowlisted_loopback"
    result = Crawlberg.scrape(engine, url)
    expect(result.status_code).to eq(200)
    expect(result.metadata.title.to_s).to eq('Allowlisted')
  end

  it 'validation_ssrf_ipv4_mapped_ipv6_denied: SSRF policy rejects an IPv4 loopback address embedded in an IPv6 literal' do
    expect do
      engine_config = { 'ssrf' => { 'deny_private' => true }, 'ssrf_deny_private_explicit' => true }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = 'http://[::ffff:127.0.0.1]/'
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /ssrf_policy_violation/ || error.class.name =~ /ssrf_policy_violation/).to be_truthy
    }
  end

  it 'validation_ssrf_loopback_denied: scrape() rejects loopback addresses by default SSRF policy' do
    expect do
      engine_config = { 'ssrf_deny_private_explicit' => true }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = 'http://127.0.0.1:9/'
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /ssrf_policy_violation/ || error.class.name =~ /ssrf_policy_violation/).to be_truthy
    }
  end

  it 'validation_ssrf_nat64_loopback_denied: SSRF policy rejects an IPv4 loopback address embedded in the well-known NAT64 prefix' do
    expect do
      engine_config = { 'ssrf' => { 'deny_private' => true }, 'ssrf_deny_private_explicit' => true }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = 'http://[64:ff9b::7f00:1]/'
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /ssrf_policy_violation/ || error.class.name =~ /ssrf_policy_violation/).to be_truthy
    }
  end

  it 'validation_timeout_zero: Zero request timeout is rejected as invalid config' do
    expect do
      engine_config = { 'request_timeout' => 0 }
      engine = Crawlberg.create_engine(engine_config.to_json)
      url = "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/validation_timeout_zero"
      Crawlberg.scrape(engine, url)
    end.to raise_error(RuntimeError) { |error|
      expect(error.message =~ /request_timeout/ || error.class.name =~ /request_timeout/).to be_truthy
    }
  end
end
