// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a37375e57b54ee864f37422d1e798579be192e91396e303ae882ac940e15e553
// To regenerate: alef generate
// To verify freshness: alef verify
// ignore_for_file: unused_local_variable, unused_element

import 'package:test/test.dart';
import 'dart:io';
import 'package:crawlberg/crawlberg.dart';
import 'package:crawlberg/src/crawlberg_bridge_generated/frb_generated.dart'
    show RustLib;
import 'dart:async';
import 'dart:convert';
import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'e2e_helpers.dart';

// E2e tests for category: concurrent

Process? _sutProcess;
String? _spawnedSutUrl;
MockServerHandle? _mockServerHandle;
final Map<String, String> _fixtureUrls = <String, String>{};

String _sutUrl() =>
    _spawnedSutUrl ??
    Platform.environment['MOCK_SERVER_URL'] ??
    Platform.environment['SUT_URL'] ??
    'http://localhost:8008';

String _fixtureUrl(String fixtureId) {
  final perFixture = _fixtureUrls[fixtureId];
  if (perFixture != null) return perFixture;
  final env = Platform.environment['MOCK_SERVERS'];
  if (env != null && env.isNotEmpty) {
    try {
      final decoded = jsonDecode(env);
      if (decoded is Map && decoded[fixtureId] is String) {
        return decoded[fixtureId] as String;
      }
    } catch (_) {}
  }
  return '${_sutUrl()}/fixtures/$fixtureId';
}

void _setEnv(String key, String value) {
  final libc = DynamicLibrary.process();
  final setenv = libc
      .lookupFunction<
        Int32 Function(Pointer<Utf8>, Pointer<Utf8>, Int32),
        int Function(Pointer<Utf8>, Pointer<Utf8>, int)
      >('setenv');
  final keyPtr = key.toNativeUtf8();
  final valuePtr = value.toNativeUtf8();
  try {
    final result = setenv(keyPtr, valuePtr, 1);
    if (result != 0) {
      throw StateError(
        'setenv failed for ${key}=${value} with return code $result',
      );
    }
  } finally {
    calloc.free(keyPtr);
    calloc.free(valuePtr);
  }
}

void main() {
  var _rustLibInitialized = false;

  setUpAll(() async {
    _setEnv('CRAWLBERG_ALLOW_PRIVATE_NETWORK', 'true');
    await RustLib.init();
    _rustLibInitialized = true;
    if (Platform.environment['MOCK_SERVER_URL'] == null &&
        Platform.environment['SUT_URL'] == null) {
      final _harness = Directory.current.uri
          .resolve('app_harness.dart')
          .toFilePath();
      if (File(_harness).existsSync()) {
        _sutProcess = await Process.start('dart', [
          'run',
          _harness,
        ], mode: ProcessStartMode.normal);
        final _ready = Completer<void>();
        _sutProcess!.stdout
            .transform(utf8.decoder)
            .transform(const LineSplitter())
            .listen(
              (_line) {
                final _trimmed = _line.trim();
                if (_trimmed.startsWith('SUT_URL=')) {
                  _spawnedSutUrl = _trimmed.substring('SUT_URL='.length);
                  if (!_ready.isCompleted) _ready.complete();
                }
              },
              onDone: () {
                if (!_ready.isCompleted) _ready.complete();
              },
            );
        await _ready.future.timeout(
          const Duration(seconds: 15),
          onTimeout: () {},
        );
      } else {
        // Standalone mock-server mode: delegate to the shared helper.
        final _handle = await startMockServer();
        _mockServerHandle = _handle;
        _spawnedSutUrl = _handle.url;
        _fixtureUrls.addAll(_handle.fixtureUrls);
      }
    }
  });

  tearDownAll(() async {
    if (_rustLibInitialized) {
      RustLib.dispose();
    }
    final proc = _sutProcess;
    if (proc != null) {
      proc.kill();
      await proc.exitCode;
    }
    await _mockServerHandle?.stop();
  });

  test(
    'Concurrent crawling fetches all pages with max_concurrent workers',
    () async {
      final engineConfig = await createCrawlConfigFromJson(
        json: r'{"max_concurrent":3,"max_depth":1}',
      );
      final engine = await CrawlbergBridge.createEngine(config: engineConfig);
      final url = _fixtureUrl("concurrent_basic");
      final result = await CrawlbergBridge.crawl(engine, url);
      expect(result.pages.length, equals(6));
      expect(result.pages.length, greaterThanOrEqualTo(6));
    },
  );

  test(
    'Concurrent depth=2 crawl correctly fans out and deduplicates across levels',
    () async {
      final engineConfig = await createCrawlConfigFromJson(
        json: r'{"max_concurrent":3,"max_depth":2}',
      );
      final engine = await CrawlbergBridge.createEngine(config: engineConfig);
      final url = _fixtureUrl("concurrent_depth_two_fan_out");
      final result = await CrawlbergBridge.crawl(engine, url);
      expect(result.pages.length, equals(4));
    },
  );

  test(
    'Concurrent crawling does not exceed max_pages limit even with high concurrency',
    () async {
      final engineConfig = await createCrawlConfigFromJson(
        json: r'{"max_concurrent":5,"max_depth":1,"max_pages":3}',
      );
      final engine = await CrawlbergBridge.createEngine(config: engineConfig);
      final url = _fixtureUrl("concurrent_max_pages_exact");
      final result = await CrawlbergBridge.crawl(engine, url);
      expect(result.pages.length, lessThanOrEqualTo(3));
    },
  );

  test('Concurrent crawl handles partial failures gracefully', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"max_concurrent":3,"max_depth":1}',
    );
    final engine = await CrawlbergBridge.createEngine(config: engineConfig);
    final url = _fixtureUrl("concurrent_partial_errors");
    final result = await CrawlbergBridge.crawl(engine, url);
    expect(result.pages.length, greaterThanOrEqualTo(2));
  });

  test('Concurrent crawling respects max_pages limit', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json: r'{"max_concurrent":2,"max_depth":1,"max_pages":3}',
    );
    final engine = await CrawlbergBridge.createEngine(config: engineConfig);
    final url = _fixtureUrl("concurrent_respects_max_pages");
    final result = await CrawlbergBridge.crawl(engine, url);
    expect(result.pages.length, lessThanOrEqualTo(3));
  });
}
