// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1ef18b66e8f0398e0aa0650f98d6b63ca8cd3bb0ac56a6ae950b3ae5137310ca
// To regenerate: alef generate
// To verify freshness: alef verify
// ignore_for_file: unused_local_variable, unused_element

import 'package:test/test.dart';
import 'dart:io';
import 'package:crawlberg/crawlberg.dart';
import 'package:crawlberg/src/crawlberg_bridge_generated/frb_generated.dart'
    show RustLib;
import 'dart:async';
import 'dart:convert';
import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'e2e_helpers.dart';

// E2e tests for category: cookies

Process? _sutProcess;
String? _spawnedSutUrl;
MockServerHandle? _mockServerHandle;
final Map<String, String> _fixtureUrls = <String, String>{};

String _sutUrl() =>
    _spawnedSutUrl ??
    Platform.environment['MOCK_SERVER_URL'] ??
    Platform.environment['SUT_URL'] ??
    'http://localhost:8008';

String _fixtureUrl(String fixtureId) {
  final perFixture = _fixtureUrls[fixtureId];
  if (perFixture != null) return perFixture;
  final env = Platform.environment['MOCK_SERVERS'];
  if (env != null && env.isNotEmpty) {
    try {
      final decoded = jsonDecode(env);
      if (decoded is Map && decoded[fixtureId] is String) {
        return decoded[fixtureId] as String;
      }
    } catch (_) {}
  }
  return '${_sutUrl()}/fixtures/$fixtureId';
}

void _setEnv(String key, String value) {
  final libc = DynamicLibrary.process();
  final setenv = libc
      .lookupFunction<
        Int32 Function(Pointer<Utf8>, Pointer<Utf8>, Int32),
        int Function(Pointer<Utf8>, Pointer<Utf8>, int)
      >('setenv');
  final keyPtr = key.toNativeUtf8();
  final valuePtr = value.toNativeUtf8();
  try {
    final result = setenv(keyPtr, valuePtr, 1);
    if (result != 0) {
      throw StateError(
        'setenv failed for ${key}=${value} with return code $result',
      );
    }
  } finally {
    calloc.free(keyPtr);
    calloc.free(valuePtr);
  }
}

void main() {
  var _rustLibInitialized = false;

  setUpAll(() async {
    _setEnv('CRAWLBERG_ALLOW_PRIVATE_NETWORK', 'true');
    await RustLib.init();
    _rustLibInitialized = true;
    if (Platform.environment['MOCK_SERVER_URL'] == null &&
        Platform.environment['SUT_URL'] == null) {
      final _harness = Directory.current.uri
          .resolve('app_harness.dart')
          .toFilePath();
      if (File(_harness).existsSync()) {
        _sutProcess = await Process.start('dart', [
          'run',
          _harness,
        ], mode: ProcessStartMode.normal);
        final _ready = Completer<void>();
        _sutProcess!.stdout
            .transform(utf8.decoder)
            .transform(const LineSplitter())
            .listen(
              (_line) {
                final _trimmed = _line.trim();
                if (_trimmed.startsWith('SUT_URL=')) {
                  _spawnedSutUrl = _trimmed.substring('SUT_URL='.length);
                  if (!_ready.isCompleted) _ready.complete();
                }
              },
              onDone: () {
                if (!_ready.isCompleted) _ready.complete();
              },
            );
        await _ready.future.timeout(
          const Duration(seconds: 15),
          onTimeout: () {},
        );
      } else {
        // Standalone mock-server mode: delegate to the shared helper.
        final _handle = await startMockServer();
        _mockServerHandle = _handle;
        _spawnedSutUrl = _handle.url;
        _fixtureUrls.addAll(_handle.fixtureUrls);
      }
    }
  });

  tearDownAll(() async {
    if (_rustLibInitialized) {
      RustLib.dispose();
    }
    final proc = _sutProcess;
    if (proc != null) {
      proc.kill();
      await proc.exitCode;
    }
    await _mockServerHandle?.stop();
  });

  test('Isolates cookies per domain during crawl', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json:
          r'{"cookies_enabled":true,"max_depth":1,"respect_robots_txt":false}',
    );
    final engine = await CrawlbergBridge.createEngine(config: engineConfig);
    final url = _fixtureUrl("cookies_per_domain");
    final result = await CrawlbergBridge.crawl(engine, url);
    expect(result.cookies.length, equals(1));
    expect(
      result.cookies.where((item) {
        final texts = <String>[];
        texts.add(item.name.toString());
        texts.add(item.value.toString());
        final v_domain = item.domain;
        if (v_domain != null) texts.add(v_domain.toString());
        final v_path = item.path;
        if (v_path != null) texts.add(v_path.toString());
        return texts.any(
          (t) => t.toLowerCase().contains(
            ('domain_cookie').toString().toLowerCase(),
          ),
        );
      }).isEmpty,
      isFalse,
    );
  });

  test('Maintains cookies across multiple crawl requests', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json:
          r'{"cookies_enabled":true,"max_depth":1,"respect_robots_txt":false}',
    );
    final engine = await CrawlbergBridge.createEngine(config: engineConfig);
    final url = _fixtureUrl("cookies_persistence");
    final result = await CrawlbergBridge.crawl(engine, url);
    expect(
      result.cookies.where((item) {
        final texts = <String>[];
        texts.add(item.name.toString());
        texts.add(item.value.toString());
        final v_domain = item.domain;
        if (v_domain != null) texts.add(v_domain.toString());
        final v_path = item.path;
        if (v_path != null) texts.add(v_path.toString());
        return texts.any(
          (t) => t.toLowerCase().contains(('session').toString().toLowerCase()),
        );
      }).isEmpty,
      isFalse,
    );
  });

  test('Respects Set-Cookie header from server responses', () async {
    final engineConfig = await createCrawlConfigFromJson(
      json:
          r'{"cookies_enabled":true,"max_depth":1,"respect_robots_txt":false}',
    );
    final engine = await CrawlbergBridge.createEngine(config: engineConfig);
    final url = _fixtureUrl("cookies_set_cookie_response");
    final result = await CrawlbergBridge.crawl(engine, url);
    expect(
      result.cookies.where((item) {
        final texts = <String>[];
        texts.add(item.name.toString());
        texts.add(item.value.toString());
        final v_domain = item.domain;
        if (v_domain != null) texts.add(v_domain.toString());
        final v_path = item.path;
        if (v_path != null) texts.add(v_path.toString());
        return texts.any(
          (t) =>
              t.toLowerCase().contains(('tracking').toString().toLowerCase()),
        );
      }).isEmpty,
      isFalse,
    );
  });
}
