// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2d1ae53be83c8324aa82baf160c2f096a3d0814eda8522a9d88da2eec8380642
// To regenerate: alef generate
// To verify freshness: alef verify
// ignore_for_file: unused_local_variable, unused_element

import 'package:test/test.dart';
import 'dart:io';
import 'package:crawlberg/crawlberg.dart';
import 'package:crawlberg/src/crawlberg_bridge_generated/frb_generated.dart'
    show RustLib;
import 'dart:async';
import 'dart:convert';
import 'dart:ffi';
import 'package:ffi/ffi.dart';

// E2e tests for category: error

Process? _sutProcess;
String? _spawnedSutUrl;
final Map<String, String> _fixtureUrls = <String, String>{};

String _sutUrl() =>
    _spawnedSutUrl ??
    Platform.environment['MOCK_SERVER_URL'] ??
    Platform.environment['SUT_URL'] ??
    'http://localhost:8008';

String _fixtureUrl(String fixtureId) {
  final perFixture = _fixtureUrls[fixtureId];
  if (perFixture != null) return perFixture;
  final env = Platform.environment['MOCK_SERVERS'];
  if (env != null && env.isNotEmpty) {
    try {
      final decoded = jsonDecode(env);
      if (decoded is Map && decoded[fixtureId] is String) {
        return decoded[fixtureId] as String;
      }
    } catch (_) {}
  }
  return '${_sutUrl()}/fixtures/$fixtureId';
}

void _setEnv(String key, String value) {
  final libc = DynamicLibrary.process();
  final setenv = libc
      .lookupFunction<
        Int32 Function(Pointer<Utf8>, Pointer<Utf8>, Int32),
        int Function(Pointer<Utf8>, Pointer<Utf8>, int)
      >('setenv');
  final keyPtr = key.toNativeUtf8();
  final valuePtr = value.toNativeUtf8();
  try {
    final result = setenv(keyPtr, valuePtr, 1);
    if (result != 0) {
      throw StateError(
        'setenv failed for ${key}=${value} with return code $result',
      );
    }
  } finally {
    calloc.free(keyPtr);
    calloc.free(valuePtr);
  }
}

void main() {
  var _rustLibInitialized = false;

  setUpAll(() async {
    _setEnv('CRAWLBERG_ALLOW_PRIVATE_NETWORK', 'true');
    await RustLib.init();
    _rustLibInitialized = true;
    if (Platform.environment['MOCK_SERVER_URL'] == null &&
        Platform.environment['SUT_URL'] == null) {
      final _harness = Directory.current.uri
          .resolve('app_harness.dart')
          .toFilePath();
      if (File(_harness).existsSync()) {
        _sutProcess = await Process.start('dart', [
          'run',
          _harness,
        ], mode: ProcessStartMode.normal);
        final _ready = Completer<void>();
        _sutProcess!.stdout
            .transform(utf8.decoder)
            .transform(const LineSplitter())
            .listen(
              (_line) {
                final _trimmed = _line.trim();
                if (_trimmed.startsWith('SUT_URL=')) {
                  _spawnedSutUrl = _trimmed.substring('SUT_URL='.length);
                  if (!_ready.isCompleted) _ready.complete();
                }
              },
              onDone: () {
                if (!_ready.isCompleted) _ready.complete();
              },
            );
        await _ready.future.timeout(
          const Duration(seconds: 15),
          onTimeout: () {},
        );
      } else {
        // Standalone mock-server mode: build if missing, then spawn.
        final _mockBin = Directory.current.uri
            .resolve('../rust/target/release/mock-server')
            .toFilePath();
        final _mockManifest = Directory.current.uri
            .resolve('../rust/Cargo.toml')
            .toFilePath();
        if (!File(_mockBin).existsSync()) {
          final _build = await Process.run('cargo', [
            'build',
            '--release',
            '--manifest-path',
            _mockManifest,
            '--bin',
            'mock-server',
          ]);
          if (_build.exitCode != 0)
            throw StateError('mock-server build failed: ${_build.stderr}');
        }
        final _fixturesDir = Directory.current.uri
            .resolve('../../fixtures')
            .toFilePath();
        _sutProcess = await Process.start(_mockBin, [
          _fixturesDir,
        ], mode: ProcessStartMode.normal);
        final _ready2 = Completer<void>();
        _sutProcess!.stdout
            .transform(utf8.decoder)
            .transform(const LineSplitter())
            .listen(
              (_line) {
                final _trimmed = _line.trim();
                if (_trimmed.startsWith('MOCK_SERVER_URL=')) {
                  _spawnedSutUrl = _trimmed.substring(
                    'MOCK_SERVER_URL='.length,
                  );
                }
                if (_trimmed.startsWith('MOCK_SERVERS=')) {
                  final _payload = _trimmed.substring('MOCK_SERVERS='.length);
                  try {
                    final _decoded = jsonDecode(_payload);
                    if (_decoded is Map) {
                      _decoded.forEach((k, v) {
                        if (k is String && v is String) {
                          _fixtureUrls[k] = v;
                        }
                      });
                    }
                  } catch (_) {}
                  if (!_ready2.isCompleted) _ready2.complete();
                } else if (_spawnedSutUrl != null) {
                  if (!_ready2.isCompleted) _ready2.complete();
                }
              },
              onDone: () {
                if (!_ready2.isCompleted) _ready2.complete();
              },
            );
        await _ready2.future.timeout(
          const Duration(seconds: 60),
          onTimeout: () {},
        );
      }
    }
  });

  tearDownAll(() async {
    if (_rustLibInitialized) {
      RustLib.dispose();
    }
    final proc = _sutProcess;
    if (proc != null) {
      proc.kill();
      await proc.exitCode;
    }
  });

  test('Handles 401 Unauthorized response correctly', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_401_unauthorized");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('unauthorized') ||
              e.runtimeType.toString().contains('unauthorized'),
        ),
      ),
    );
  });

  test('Handles 403 Forbidden response correctly', () async {
    await expectLater(
      () async {
        final engineConfig = await createCrawlConfigFromJson(
          json: r'{"browser":{"mode":"never"}}',
        );
        final engine = await CrawlbergBridge.createEngine(config: engineConfig);
        final url = _fixtureUrl("error_403_forbidden");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('forbidden') ||
              e.runtimeType.toString().contains('forbidden'),
        ),
      ),
    );
  });

  test('Handles 404 response correctly', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_404_page");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('not_found') ||
              e.runtimeType.toString().contains('not_found'),
        ),
      ),
    );
  });

  test('Handles 408 Request Timeout response correctly', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_408_request_timeout");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('timeout') ||
              e.runtimeType.toString().contains('timeout'),
        ),
      ),
    );
  });

  test('Handles 410 Gone response correctly', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_410_gone");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('gone') ||
              e.runtimeType.toString().contains('gone'),
        ),
      ),
    );
  });

  test('Handles 500 server error', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_500_server");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('server_error') ||
              e.runtimeType.toString().contains('server_error'),
        ),
      ),
    );
  });

  test('Handles 502 Bad Gateway response correctly', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_502_bad_gateway");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('bad_gateway') ||
              e.runtimeType.toString().contains('bad_gateway'),
        ),
      ),
    );
  });

  test(
    'Browser launch fails when browser mode is always but browser is unavailable',
    () async {
      await expectLater(
        () async {
          final engineConfig = await createCrawlConfigFromJson(
            json: r'{"browser":{"mode":"always","timeout":1}}',
          );
          final engine = await CrawlbergBridge.createEngine(
            config: engineConfig,
          );
          final url = _fixtureUrl("error_browser_launch_failure");
          return CrawlbergBridge.scrape(engine, url);
        }(),
        throwsA(
          predicate(
            (e) =>
                e.toString().contains('browser') ||
                e.runtimeType.toString().contains('browser'),
          ),
        ),
      );
    },
  );

  test('Browser page load times out', () async {
    await expectLater(
      () async {
        final engineConfig = await createCrawlConfigFromJson(
          json: r'{"browser":{"mode":"always","timeout":1}}',
        );
        final engine = await CrawlbergBridge.createEngine(config: engineConfig);
        final url = _fixtureUrl("error_browser_page_timeout");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('browser_timeout') ||
              e.runtimeType.toString().contains('browser_timeout'),
        ),
      ),
    );
  });

  test('Handles connection refused error gracefully', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_connection_refused");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('connection') ||
              e.runtimeType.toString().contains('connection'),
        ),
      ),
    );
  });

  test('Content-Length mismatch causes data loss error', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_data_loss_truncated");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('data_loss:') ||
              e.runtimeType.toString().contains('data_loss:'),
        ),
      ),
    );
  });

  test('Handles DNS resolution failure gracefully', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_dns_resolution");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('dns') ||
              e.runtimeType.toString().contains('dns'),
        ),
      ),
    );
  });

  test(
    'Scraping a URL that cannot be found returns an error containing the URL path',
    () async {
      await expectLater(
        () async {
          final engine = await CrawlbergBridge.createEngine();
          final url = _fixtureUrl("error_empty_batch_urls");
          return CrawlbergBridge.scrape(engine, url);
        }(),
        throwsA(
          predicate(
            (e) =>
                e.toString().contains('not_found') ||
                e.runtimeType.toString().contains('not_found'),
          ),
        ),
      );
    },
  );

  test('Handles 200 with completely empty body gracefully', () async {
    final engine = await CrawlbergBridge.createEngine();
    final url = _fixtureUrl("error_empty_response");
    final result = await CrawlbergBridge.scrape(engine, url);
    expect((result.html?.toString() ?? ''), isEmpty);
  });

  test(
    'Proxy pointing to unreachable address causes connection error during scrape',
    () async {
      await expectLater(
        () async {
          final engineConfig = await createCrawlConfigFromJson(
            json: r'{"proxy":{"url":"http://127.0.0.1:1"}}',
          );
          final engine = await CrawlbergBridge.createEngine(
            config: engineConfig,
          );
          final url = _fixtureUrl("error_invalid_proxy");
          return CrawlbergBridge.scrape(engine, url);
        }(),
        throwsA(
          predicate(
            (e) =>
                e.toString().contains('connection') ||
                e.runtimeType.toString().contains('connection'),
          ),
        ),
      );
    },
  );

  test('Handles incomplete or truncated HTTP response', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_partial_response");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('data_loss') ||
              e.runtimeType.toString().contains('data_loss'),
        ),
      ),
    );
  });

  test('Handles 429 rate limiting with Retry-After', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_rate_limited");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('rate_limited') ||
              e.runtimeType.toString().contains('rate_limited'),
        ),
      ),
    );
  });

  test('Retries request on 503 Service Unavailable response', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_retry_503");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('server_error') ||
              e.runtimeType.toString().contains('server_error'),
        ),
      ),
    );
  });

  test(
    'Implements exponential backoff when retrying failed requests',
    () async {
      await expectLater(
        () async {
          final engine = await CrawlbergBridge.createEngine();
          final url = _fixtureUrl("error_retry_backoff");
          return CrawlbergBridge.scrape(engine, url);
        }(),
        throwsA(
          predicate(
            (e) =>
                e.toString().contains('rate_limited') ||
                e.runtimeType.toString().contains('rate_limited'),
          ),
        ),
      );
    },
  );

  test('Handles SSL certificate validation error', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = _fixtureUrl("error_ssl_invalid_cert");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('ssl') ||
              e.runtimeType.toString().contains('ssl'),
        ),
      ),
    );
  });

  test(
    'Mock server delays response longer than request_timeout, surfacing a timeout error',
    () async {
      await expectLater(
        () async {
          final engineConfig = await createCrawlConfigFromJson(
            json: r'{"request_timeout":500}',
          );
          final engine = await CrawlbergBridge.createEngine(
            config: engineConfig,
          );
          final url = _fixtureUrl("error_timeout");
          return CrawlbergBridge.scrape(engine, url);
        }(),
        throwsA(
          predicate(
            (e) =>
                e.toString().contains('timeout') ||
                e.runtimeType.toString().contains('timeout'),
          ),
        ),
      );
    },
  );

  test('Unsupported URL scheme (gopher) is rejected', () async {
    await expectLater(
      () async {
        final engine = await CrawlbergBridge.createEngine();
        final url = 'gopher://invalid.example.com/';
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('disallowed scheme: gopher') ||
              e.runtimeType.toString().contains('disallowed scheme: gopher'),
        ),
      ),
    );
  });

  test('Akamai WAF detection returns WafBlocked error', () async {
    await expectLater(() async {
      final engineConfig = await createCrawlConfigFromJson(
        json: r'{"browser":{"mode":"never"}}',
      );
      final engine = await CrawlbergBridge.createEngine(config: engineConfig);
      final url = _fixtureUrl("error_waf_akamai");
      return CrawlbergBridge.scrape(engine, url);
    }(), throwsA(anything));
  });

  test('WAF challenge/block detection returns WafBlocked error', () async {
    await expectLater(
      () async {
        final engineConfig = await createCrawlConfigFromJson(
          json: r'{"browser":{"mode":"never"}}',
        );
        final engine = await CrawlbergBridge.createEngine(config: engineConfig);
        final url = _fixtureUrl("error_waf_blocked");
        return CrawlbergBridge.scrape(engine, url);
      }(),
      throwsA(
        predicate(
          (e) =>
              e.toString().contains('waf') ||
              e.runtimeType.toString().contains('waf'),
        ),
      ),
    );
  });

  test(
    'Detects WAF/bot protection false 403 (Cloudflare challenge page)',
    () async {
      await expectLater(
        () async {
          final engineConfig = await createCrawlConfigFromJson(
            json: r'{"browser":{"mode":"never"}}',
          );
          final engine = await CrawlbergBridge.createEngine(
            config: engineConfig,
          );
          final url = _fixtureUrl("error_waf_false_403");
          return CrawlbergBridge.scrape(engine, url);
        }(),
        throwsA(
          predicate(
            (e) =>
                e.toString().contains('waf') ||
                e.runtimeType.toString().contains('waf'),
          ),
        ),
      );
    },
  );

  test('Imperva/Incapsula WAF detection', () async {
    await expectLater(() async {
      final engineConfig = await createCrawlConfigFromJson(
        json: r'{"browser":{"mode":"never"}}',
      );
      final engine = await CrawlbergBridge.createEngine(config: engineConfig);
      final url = _fixtureUrl("error_waf_imperva");
      return CrawlbergBridge.scrape(engine, url);
    }(), throwsA(anything));
  });
}
