#!/usr/bin/env bash
# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1b085c5d41adfa0f76d3f29c08616c66f2f75f7073cbbc6c84b27fe70b1dca8a
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: redirect
set -euo pipefail

test_redirect_301_permanent() {
  # Follows 301 permanent redirect and returns final page content
  local output
  output=$(crawlberg crawl "${MOCK_SERVER_REDIRECT_301_PERMANENT:-${MOCK_SERVER_URL}/fixtures/redirect_301_permanent}" --config '{"respect_robots_txt":false}' --format json --browser-mode never)

  local val_final_url
  val_final_url=$(echo "$output" | jq -r '.final_url')
  assert_contains "$val_final_url" '/target' 'final_url'
  local val_redirect_count
  val_redirect_count=$(echo "$output" | jq -r '.redirect_count')
  assert_equals "$val_redirect_count" '1' 'redirect_count'
}

test_redirect_302_found() {
  # Follows 302 Found redirect correctly
  local output
  output=$(crawlberg crawl "${MOCK_SERVER_REDIRECT_302_FOUND:-${MOCK_SERVER_URL}/fixtures/redirect_302_found}" --config '{"respect_robots_txt":false}' --format json --browser-mode never)

  local val_final_url
  val_final_url=$(echo "$output" | jq -r '.final_url')
  assert_contains "$val_final_url" '/found-target' 'final_url'
  local val_redirect_count
  val_redirect_count=$(echo "$output" | jq -r '.redirect_count')
  assert_equals "$val_redirect_count" '1' 'redirect_count'
}

test_redirect_303_see_other() {
  # Follows 303 See Other redirect (method changes to GET)
  local output
  output=$(crawlberg crawl "${MOCK_SERVER_REDIRECT_303_SEE_OTHER:-${MOCK_SERVER_URL}/fixtures/redirect_303_see_other}" --config '{"respect_robots_txt":false}' --format json --browser-mode never)

  local val_final_url
  val_final_url=$(echo "$output" | jq -r '.final_url')
  assert_contains "$val_final_url" '/see-other' 'final_url'
  local val_redirect_count
  val_redirect_count=$(echo "$output" | jq -r '.redirect_count')
  assert_equals "$val_redirect_count" '1' 'redirect_count'
}

test_redirect_307_temporary() {
  # Follows 307 Temporary Redirect (preserves method)
  local output
  output=$(crawlberg crawl "${MOCK_SERVER_REDIRECT_307_TEMPORARY:-${MOCK_SERVER_URL}/fixtures/redirect_307_temporary}" --config '{"respect_robots_txt":false}' --format json --browser-mode never)

  local val_final_url
  val_final_url=$(echo "$output" | jq -r '.final_url')
  assert_contains "$val_final_url" '/temp-target' 'final_url'
  local val_redirect_count
  val_redirect_count=$(echo "$output" | jq -r '.redirect_count')
  assert_equals "$val_redirect_count" '1' 'redirect_count'
}

test_redirect_308_permanent() {
  # Follows 308 Permanent Redirect (preserves method)
  local output
  output=$(crawlberg crawl "${MOCK_SERVER_REDIRECT_308_PERMANENT:-${MOCK_SERVER_URL}/fixtures/redirect_308_permanent}" --config '{"respect_robots_txt":false}' --format json --browser-mode never)

  local val_final_url
  val_final_url=$(echo "$output" | jq -r '.final_url')
  assert_contains "$val_final_url" '/perm-target' 'final_url'
  local val_redirect_count
  val_redirect_count=$(echo "$output" | jq -r '.redirect_count')
  assert_equals "$val_redirect_count" '1' 'redirect_count'
}

test_redirect_chain() {
  # Follows a chain of redirects (301 -> 302 -> 200)
  local output
  output=$(crawlberg crawl "${MOCK_SERVER_REDIRECT_CHAIN:-${MOCK_SERVER_URL}/fixtures/redirect_chain}" --config '{"respect_robots_txt":false}' --format json --browser-mode never)

  local val_final_url
  val_final_url=$(echo "$output" | jq -r '.final_url')
  assert_contains "$val_final_url" '/step2' 'final_url'
  local val_redirect_count
  val_redirect_count=$(echo "$output" | jq -r '.redirect_count')
  assert_equals "$val_redirect_count" '2' 'redirect_count'
}

test_redirect_cross_domain() {
  # Reports cross-domain redirect target without following to external domain
  local output
  output=$(crawlberg crawl "${MOCK_SERVER_REDIRECT_CROSS_DOMAIN:-${MOCK_SERVER_URL}/fixtures/redirect_cross_domain}" --config '{"respect_robots_txt":false}' --format json --browser-mode never)

  local val_final_url
  val_final_url=$(echo "$output" | jq -r '.final_url')
  assert_contains "$val_final_url" '/external-redirect' 'final_url'
  local val_redirect_count
  val_redirect_count=$(echo "$output" | jq -r '.redirect_count')
  assert_equals "$val_redirect_count" '1' 'redirect_count'
}

test_redirect_loop() {
  # Detects redirect loop (A -> B -> A) and stops following without reaching a final page
  local output
  output=$(crawlberg crawl "${MOCK_SERVER_REDIRECT_LOOP:-${MOCK_SERVER_URL}/fixtures/redirect_loop}" --config '{"respect_robots_txt":false}' --format json --browser-mode never)

  local val_redirect_count
  val_redirect_count=$(echo "$output" | jq -r '.redirect_count')
  assert_equals "$val_redirect_count" '1' 'redirect_count'
  local val_pages_0__status_code
  val_pages_0__status_code=$(echo "$output" | jq -r '.pages[0].status_code')
  assert_equals "$val_pages_0__status_code" '302' 'pages[0].status_code'
}

test_redirect_max_exceeded() {
  # Aborts when redirect count exceeds max_redirects limit
  local output
  output=$(crawlberg crawl "${MOCK_SERVER_REDIRECT_MAX_EXCEEDED:-${MOCK_SERVER_URL}/fixtures/redirect_max_exceeded}" --config '{"max_redirects":2,"respect_robots_txt":false}' --format json --browser-mode never)

  local val_redirect_count
  val_redirect_count=$(echo "$output" | jq -r '.redirect_count')
  assert_equals "$val_redirect_count" '2' 'redirect_count'
  local val_pages_0__status_code
  val_pages_0__status_code=$(echo "$output" | jq -r '.pages[0].status_code')
  assert_equals "$val_pages_0__status_code" '301' 'pages[0].status_code'
}

test_redirect_meta_refresh() {
  # Follows HTML meta-refresh redirect to target page
  local output
  output=$(crawlberg crawl "${MOCK_SERVER_REDIRECT_META_REFRESH:-${MOCK_SERVER_URL}/fixtures/redirect_meta_refresh}" --config '{"respect_robots_txt":false}' --format json --browser-mode never)

  local val_final_url
  val_final_url=$(echo "$output" | jq -r '.final_url')
  assert_contains "$val_final_url" '/target' 'final_url'
  local val_redirect_count
  val_redirect_count=$(echo "$output" | jq -r '.redirect_count')
  assert_equals "$val_redirect_count" '1' 'redirect_count'
}

test_redirect_refresh_header() {
  # Handles HTTP Refresh header redirect
  local output
  output=$(crawlberg crawl "${MOCK_SERVER_REDIRECT_REFRESH_HEADER:-${MOCK_SERVER_URL}/fixtures/redirect_refresh_header}" --config '{"respect_robots_txt":false}' --format json --browser-mode never)

  local val_final_url
  val_final_url=$(echo "$output" | jq -r '.final_url')
  assert_contains "$val_final_url" '/refreshed' 'final_url'
  local val_redirect_count
  val_redirect_count=$(echo "$output" | jq -r '.redirect_count')
  assert_equals "$val_redirect_count" '1' 'redirect_count'
}

test_redirect_to_404() {
  # Redirect target returns 404 Not Found
  local output
  output=$(crawlberg crawl "${MOCK_SERVER_REDIRECT_TO_404:-${MOCK_SERVER_URL}/fixtures/redirect_to_404}" --config '{"respect_robots_txt":false}' --format json --browser-mode never)

  local val_final_url
  val_final_url=$(echo "$output" | jq -r '.final_url')
  assert_contains "$val_final_url" '/gone' 'final_url'
  local val_redirect_count
  val_redirect_count=$(echo "$output" | jq -r '.redirect_count')
  assert_equals "$val_redirect_count" '1' 'redirect_count'
  local val_error
  val_error=$(echo "$output" | jq -r '.error')
  assert_contains "$val_error" '404' 'error'
}

run_tests_redirect() {
  run_test test_redirect_301_permanent
  run_test test_redirect_302_found
  run_test test_redirect_303_see_other
  run_test test_redirect_307_temporary
  run_test test_redirect_308_permanent
  run_test test_redirect_chain
  run_test test_redirect_cross_domain
  run_test test_redirect_loop
  run_test test_redirect_max_exceeded
  run_test test_redirect_meta_refresh
  run_test test_redirect_refresh_header
  run_test test_redirect_to_404
}
