name: Validate PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    uses: xberg-io/actions/.github/workflows/reusable-validate-pr.yml@3aaf68669e0eeafc98a57e720d0ceef70dce5bbf # v1.11.5
    secrets: inherit
