name: Validate PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    uses: xberg-io/actions/.github/workflows/reusable-validate-pr.yml@fc21dc868b7ec7f2b29a75c16312a818f7feb6f6 # v1.10.2
    secrets: inherit
