// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f98299c38c9c22669bf52059774e0d0898a24ef26e59a9d330428d593c56b5fe
// To regenerate: alef generate
// To verify freshness: alef verify

package e2e_test

import "encoding/json"

// jsonString converts a value to its JSON string representation.
// Array fields use jsonString instead of fmt.Sprint to preserve structure.
//
//nolint:unused
func jsonString(value any) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return ""
	}
	return string(encoded)
}
