// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8075a52f4795919a92c3ffc9ff274166d7c39c08b21747796413bb9b72febe20
// To regenerate: alef e2e generate
// To verify freshness: alef verify

// E2e tests for category: markdown
package e2e_test

import (
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	pkg "github.com/xberg-io/crawlberg/packages/go"
)

func Test_CitationsBalancedParens(t *testing.T) {
	// Citations correctly handle links inside parentheses with balanced rendering
	engine, createErr := pkg.CreateEngine(nil)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/citations_balanced_parens"
	result, err := pkg.Scrape(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.StatusCode != 200 {
		t.Errorf("equals mismatch: got %v", result.StatusCode)
	}
	if len(result.Markdown.Content) == 0 {
		t.Errorf("expected non-empty value")
	}
	if !strings.Contains(string(result.Markdown.Content), `(`) {
		t.Errorf("expected to contain %s, got %v", `(`, result.Markdown.Content)
	}
}

func Test_CitationsDuplicateUrls(t *testing.T) {
	// Citations deduplicates multiple links to the same URL
	engine, createErr := pkg.CreateEngine(nil)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/citations_duplicate_urls"
	result, err := pkg.Scrape(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.StatusCode != 200 {
		t.Errorf("equals mismatch: got %v", result.StatusCode)
	}
	if len(result.Markdown.Content) == 0 {
		t.Errorf("expected non-empty value")
	}
	assert.True(t, result.Markdown.Citations, "expected true")
}

func Test_MarkdownBasicConversion(t *testing.T) {
	// HTML is always converted to markdown alongside raw HTML
	engine, createErr := pkg.CreateEngine(nil)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/markdown_basic_conversion"
	result, err := pkg.Scrape(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var metadataTitle string
	if result.Metadata.Title != nil {
		metadataTitle = string(*result.Metadata.Title)
	}
	if result.StatusCode != 200 {
		t.Errorf("equals mismatch: got %v", result.StatusCode)
	}
	if string(metadataTitle) != `Test` {
		t.Errorf("equals mismatch: got %v", metadataTitle)
	}
	if len(result.HTML) == 0 {
		t.Errorf("expected non-empty value")
	}
	if len(result.Markdown.Content) == 0 {
		t.Errorf("expected non-empty value")
	}
	if !strings.Contains(string(result.Markdown.Content), `Hello World`) {
		t.Errorf("expected to contain %s, got %v", `Hello World`, result.Markdown.Content)
	}
}

func Test_MarkdownCrawlAllPages(t *testing.T) {
	// All crawled pages have markdown field populated
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"max_depth":1}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_MARKDOWN_CRAWL_ALL_PAGES")
	if url == "" {
		url = os.Getenv("MOCK_SERVER_URL") + "/fixtures/markdown_crawl_all_pages"
	}
	result, err := pkg.Crawl(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.Pages) != 2 {
		t.Errorf("equals mismatch: got %v", len(result.Pages))
	}
}

func Test_MarkdownFitContent(t *testing.T) {
	// Fit markdown removes navigation and boilerplate content
	engine, createErr := pkg.CreateEngine(nil)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_MARKDOWN_FIT_CONTENT")
	if url == "" {
		url = os.Getenv("MOCK_SERVER_URL") + "/fixtures/markdown_fit_content"
	}
	result, err := pkg.Scrape(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.StatusCode != 200 {
		t.Errorf("equals mismatch: got %v", result.StatusCode)
	}
	if len(result.Markdown.Content) == 0 {
		t.Errorf("expected non-empty value")
	}
}

func Test_MarkdownFormattingOptions(t *testing.T) {
	// Content settings control paragraph lines, list markers, emphasis, tables, and inline heading images
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"content":{"bullets":"*","compact_tables":true,"extract_metadata":false,"keep_inline_images_in":["h2"],"list_indent_width":4,"strip_newlines":true,"strong_em_symbol":"_"}}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/markdown_formatting_options"
	result, err := pkg.Scrape(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if !strings.Contains(string(result.Markdown.Content), `line one line two`) {
		t.Errorf("expected to contain %s, got %v", `line one line two`, result.Markdown.Content)
	}
	if !strings.Contains(string(result.Markdown.Content), `* a
    * b`) {
		t.Errorf("expected to contain %s, got %v", `* a
    * b`, result.Markdown.Content)
	}
	if !strings.Contains(string(result.Markdown.Content), `_em_ __strong__`) {
		t.Errorf("expected to contain %s, got %v", `_em_ __strong__`, result.Markdown.Content)
	}
	if !strings.Contains(string(result.Markdown.Content), `| Name | Id |
| --- | --- |
| Cobalt | 4217 |`) {
		t.Errorf("expected to contain %s, got %v", `| Name | Id |
| --- | --- |
| Cobalt | 4217 |`, result.Markdown.Content)
	}
	if !strings.Contains(string(result.Markdown.Content), `## Chart ![icon](https://images.example/icon.png)`) {
		t.Errorf("expected to contain %s, got %v", `## Chart ![icon](https://images.example/icon.png)`, result.Markdown.Content)
	}
}

func Test_MarkdownHeadingsAndParagraphs(t *testing.T) {
	// Markdown conversion preserves heading hierarchy and paragraph text
	engine, createErr := pkg.CreateEngine(nil)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/markdown_headings_and_paragraphs"
	result, err := pkg.Scrape(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.Markdown.Content) == 0 {
		t.Errorf("expected non-empty value")
	}
	if !strings.Contains(string(result.Markdown.Content), `Main Title`) {
		t.Errorf("expected to contain %s, got %v", `Main Title`, result.Markdown.Content)
	}
}

func Test_MarkdownLinksConverted(t *testing.T) {
	// HTML links are converted to markdown link syntax
	engine, createErr := pkg.CreateEngine(nil)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/markdown_links_converted"
	result, err := pkg.Scrape(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.StatusCode != 200 {
		t.Errorf("equals mismatch: got %v", result.StatusCode)
	}
	if len(result.HTML) == 0 {
		t.Errorf("expected non-empty value")
	}
	if len(result.Markdown.Content) == 0 {
		t.Errorf("expected non-empty value")
	}
	if !strings.Contains(string(result.Markdown.Content), `Example`) {
		t.Errorf("expected to contain %s, got %v", `Example`, result.Markdown.Content)
	}
}

func Test_MarkdownNoFrontmatter(t *testing.T) {
	// extract_metadata: false omits the YAML frontmatter block from markdown output
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"content":{"extract_metadata":false}}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/markdown_no_frontmatter"
	result, err := pkg.Scrape(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var metadataTitle string
	if result.Metadata.Title != nil {
		metadataTitle = string(*result.Metadata.Title)
	}
	if result.StatusCode != 200 {
		t.Errorf("equals mismatch: got %v", result.StatusCode)
	}
	if string(metadataTitle) != `Test` {
		t.Errorf("equals mismatch: got %v", metadataTitle)
	}
	if strings.Contains(string(result.Markdown.Content), `---`) {
		t.Errorf("expected NOT to contain %s, got %v", `---`, result.Markdown.Content)
	}
	if !strings.Contains(string(result.Markdown.Content), `Hello World`) {
		t.Errorf("expected to contain %s, got %v", `Hello World`, result.Markdown.Content)
	}
}

func Test_MarkdownWithCitations(t *testing.T) {
	// Markdown includes citation conversion with numbered references
	engine, createErr := pkg.CreateEngine(nil)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/markdown_with_citations"
	result, err := pkg.Scrape(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.StatusCode != 200 {
		t.Errorf("equals mismatch: got %v", result.StatusCode)
	}
	if len(result.Markdown.Content) == 0 {
		t.Errorf("expected non-empty value")
	}
}
