// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:54c213327848cba0faf4a29b7f850b65736a71616fa1b2e6d71e6fa0f4ee69e9
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: validation
package e2e_test

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	pkg "github.com/xberg-io/crawlberg/packages/go"
)

func Test_ValidationBrowserEndpointInvalid(t *testing.T) {
	// Browser endpoint must be a valid ws:// or wss:// URL, not http://
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"browser":{"endpoint":"http://not-websocket:3000","mode":"always"}}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_browser_endpoint_invalid"
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `endpoint`) && !strings.Contains(fmt.Sprintf("%T", err), `endpoint`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `endpoint`, err.Error(), err)
		}
	}
}

func Test_ValidationInvalidAuthConfig(t *testing.T) {
	// auth object with empty username in basic auth is rejected
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"auth":{"password":"secret","type":"basic","username":""}}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_invalid_auth_config"
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `auth`) && !strings.Contains(fmt.Sprintf("%T", err), `auth`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `auth`, err.Error(), err)
		}
	}
}

func Test_ValidationInvalidExcludeRegex(t *testing.T) {
	// Invalid regex in exclude_paths is rejected
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"exclude_paths":["(unclosed"]}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_invalid_exclude_regex"
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `exclude_path`) && !strings.Contains(fmt.Sprintf("%T", err), `exclude_path`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `exclude_path`, err.Error(), err)
		}
	}
}

func Test_ValidationInvalidIncludeRegex(t *testing.T) {
	// Invalid regex in include_paths is rejected
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"include_paths":["[invalid"]}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_invalid_include_regex"
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `include_path`) && !strings.Contains(fmt.Sprintf("%T", err), `include_path`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `include_path`, err.Error(), err)
		}
	}
}

func Test_ValidationInvalidProxyUrl(t *testing.T) {
	// proxy with invalid URL like 'not-a-url' is rejected
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"proxy":{"url":"not-a-url"}}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_invalid_proxy_url"
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `proxy`) && !strings.Contains(fmt.Sprintf("%T", err), `proxy`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `proxy`, err.Error(), err)
		}
	}
}

func Test_ValidationInvalidRetryCode(t *testing.T) {
	// Retry code outside 100-599 is rejected
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"retry_codes":[999]}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_invalid_retry_code"
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `retry code`) && !strings.Contains(fmt.Sprintf("%T", err), `retry code`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `retry code`, err.Error(), err)
		}
	}
}

func Test_ValidationMaxConcurrentZero(t *testing.T) {
	// max_concurrent=0 is rejected as invalid config (minimum is 1)
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"max_concurrent":0}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_max_concurrent_zero"
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `max_concurrent`) && !strings.Contains(fmt.Sprintf("%T", err), `max_concurrent`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `max_concurrent`, err.Error(), err)
		}
	}
}

func Test_ValidationMaxDepthTooHigh(t *testing.T) {
	// max_depth=200 exceeds limit of 100
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"max_depth":200}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_max_depth_too_high"
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `max_depth`) && !strings.Contains(fmt.Sprintf("%T", err), `max_depth`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `max_depth`, err.Error(), err)
		}
	}
}

func Test_ValidationMaxPagesZero(t *testing.T) {
	// max_pages=0 is rejected as invalid config
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"max_pages":0}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_max_pages_zero"
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `max_pages`) && !strings.Contains(fmt.Sprintf("%T", err), `max_pages`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `max_pages`, err.Error(), err)
		}
	}
}

func Test_ValidationMaxRedirectsTooHigh(t *testing.T) {
	// max_redirects > 100 is rejected as invalid config
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"max_redirects":200}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_max_redirects_too_high"
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `max_redirects`) && !strings.Contains(fmt.Sprintf("%T", err), `max_redirects`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `max_redirects`, err.Error(), err)
		}
	}
}

func Test_ValidationNegativeBodySize(t *testing.T) {
	// max_body_size set to -1 is rejected as invalid config
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"max_body_size":0}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_negative_body_size"
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `body_size`) && !strings.Contains(fmt.Sprintf("%T", err), `body_size`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `body_size`, err.Error(), err)
		}
	}
}

func Test_ValidationSsrfAllowlistedLoopback(t *testing.T) {
	// SSRF allowlist permits a loopback mock server while private-network protection remains enabled
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"respect_robots_txt":false,"ssrf":{"allowlist":[{"type":"cidr","value":"127.0.0.0/8"}],"deny_private":true,"max_redirects":5},"ssrf_deny_private_explicit":true}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		t.Fatalf("create handle failed: %v", createErr)
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_ssrf_allowlisted_loopback"
	result, err := pkg.Scrape(engine, url)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var metadataTitle string
	if result.Metadata.Title != nil {
		metadataTitle = string(*result.Metadata.Title)
	}
	if result.StatusCode != 200 {
		t.Errorf("equals mismatch: got %v", result.StatusCode)
	}
	if string(metadataTitle) != `Allowlisted` {
		t.Errorf("equals mismatch: got %v", metadataTitle)
	}
}

func Test_ValidationSsrfIpv4MappedIpv6Denied(t *testing.T) {
	// SSRF policy rejects an IPv4 loopback address embedded in an IPv6 literal
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"ssrf":{"deny_private":true},"ssrf_deny_private_explicit":true}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := `http://[::ffff:127.0.0.1]/`
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `ssrf_policy_violation`) && !strings.Contains(fmt.Sprintf("%T", err), `ssrf_policy_violation`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `ssrf_policy_violation`, err.Error(), err)
		}
	}
}

func Test_ValidationSsrfLoopbackDenied(t *testing.T) {
	// scrape() rejects loopback addresses by default SSRF policy
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"ssrf_deny_private_explicit":true}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := `http://127.0.0.1:9/`
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `ssrf_policy_violation`) && !strings.Contains(fmt.Sprintf("%T", err), `ssrf_policy_violation`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `ssrf_policy_violation`, err.Error(), err)
		}
	}
}

func Test_ValidationSsrfNat64LoopbackDenied(t *testing.T) {
	// SSRF policy rejects an IPv4 loopback address embedded in the well-known NAT64 prefix
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"ssrf":{"deny_private":true},"ssrf_deny_private_explicit":true}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := `http://[64:ff9b::7f00:1]/`
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `ssrf_policy_violation`) && !strings.Contains(fmt.Sprintf("%T", err), `ssrf_policy_violation`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `ssrf_policy_violation`, err.Error(), err)
		}
	}
}

func Test_ValidationTimeoutZero(t *testing.T) {
	// Zero request timeout is rejected as invalid config
	var engineConfig pkg.CrawlConfig
	if err := json.Unmarshal([]byte(`{"request_timeout":0}`), &engineConfig); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	engine, createErr := pkg.CreateEngine(&engineConfig)
	if createErr != nil {
		assert.Error(t, createErr)
		return
	}
	url := os.Getenv("MOCK_SERVER_URL") + "/fixtures/validation_timeout_zero"
	_, err := pkg.Scrape(engine, url)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
	if err != nil {
		if !strings.Contains(err.Error(), `request_timeout`) && !strings.Contains(fmt.Sprintf("%T", err), `request_timeout`) {
			t.Errorf("expected error to match %s, got message=%q type=%T", `request_timeout`, err.Error(), err)
		}
	}
}
